<?php

/**
 * UlsAssessmentTestFeedback
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessmentTestFeedback extends BaseUlsAssessmentTestFeedback
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	static function getfeedbackassessment($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select c.value_name,a.*,i.ques_name from uls_assessment_test_feedback a
			left join (SELECT `ques_id`,`ques_name` FROM `uls_questionnaire_master`) i on i.ques_id=a.ques_id
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)c ON c.master_code = 'STATUS' AND c.value_code=a.status
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assess_test_id=$id order by a.feed_assess_test_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function getfeedback_assessment($id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.* from uls_assessment_test_feedback a
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=".$id."  and a.position_id=".$pos_id;
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	static function get_feedback_group($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select c.assessment_name,p.position_name,a.* from uls_assessment_test_feedback a
			left join (SELECT `assess_test_id`,`position_id`,`assessment_id` FROM `uls_assessment_test` ) t on t.assess_test_id=a.assess_test_id
			LEFT JOIN (SELECT `assessment_id`,`assessment_name`,`start_date`,`end_date` FROM `uls_assessment_definition`)c ON c.assessment_id =t.assessment_id
			left join(SELECT `position_id`,`position_name` FROM `uls_position`) p on p.position_id=t.position_id
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.feed_assess_test_id=$id order by a.feed_assess_test_id asc";
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	static function viewfeedback_count_report($id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$pos_ids=!empty($pos_id)?" and a.position_id=".$pos_id."":"";
			$query="SELECT a.* FROM `uls_assessment_test_feedback` a
			WHERE a.`assessment_id`=".$id." ".$pos_ids." and a.parent_org_id=".$CI->session->userdata('parent_org_id');
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
}