<?php

/**
 * UlsAssessmentEmployeeDevCompetencies
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessmentEmployeeDevCompetencies extends BaseUlsAssessmentEmployeeDevCompetencies
{
	function preInsert($event){
		 $CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	public static function get_emp_competency_final($ass_id,$pos_id,$emp_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select c.comp_def_id,c.comp_def_name,s.scale_id,s.scale_name,a.* from uls_assessment_employee_dev_competencies a
		left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) c on c.comp_def_id=a.comp_def_id
		left join(SELECT `scale_id`,`scale_name` FROM `uls_level_master_scale`) s on s.scale_id=a.scale_id
		where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=".$ass_id." and a.position_id=".$pos_id." and a.employee_id=".$emp_id;
		$testdetails=UlsMenu::callpdo($query);
        return $testdetails;
	}
	
	public static function get_emp_competency_view($ass_id,$pos_id,$emp_id,$comp_id,$scale_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT a.* FROM uls_assessment_employee_dev_competencies a
		WHERE a.assessment_id=".$ass_id." and a.position_id=".$pos_id." and a.employee_id=".$emp_id." and  a.comp_def_id=".$comp_id." and a.scale_id=".$scale_id;
		$testdetails=UlsMenu::callpdorow($query);
        return $testdetails;
    }
}