<?php

/**
 * UlsAssessmentPosition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessmentPosition extends BaseUlsAssessmentPosition
{
	 function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_by=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
    }
	
	static function getassessmentpositions($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.position_id as position_id,b.position_name as position_name, c.value_name as status, a.*,b.position_desc from uls_assessment_position a
			left join (select position_id,position_name,position_desc from uls_position group by position_id)b on b.position_id=a.position_id
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)c ON c.master_code = 'STATUS' AND c.value_code=a.assessment_pos_status
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id order by a.position_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	public static function get_assessment_position($id){
		$query="SELECT a.* FROM uls_assessment_position a
		WHERE a.position_id=".$id;
		$testdetails=UlsMenu::callpdorow($query);
        return $testdetails;
    } 
	
	public static function get_assessment_position_info($id,$ass_id){
		$query="SELECT a.*,b.position_name FROM uls_assessment_position a
		left join(SELECT `position_id`,`position_name` FROM `uls_position`) b on a.position_id=b.position_id
		WHERE a.position_id=".$id." and a.assessment_id=".$ass_id;
		$testdetails=UlsMenu::callpdorow($query);
        return $testdetails;
    } 
	
	public static function get_assessment_position_info_emp($id,$ass_id){
		$query="SELECT a.*,b.`assessment_name`,b.`assessment_cycle_type`,b.`assessment_type`,b.`self_ass_type`,b.end_date FROM uls_assessment_position a
		left join(SELECT `assessment_id`,`assessment_name`,`assessment_cycle_type`,`assessment_type`,`self_ass_type`,end_date FROM `uls_assessment_definition`) b on a.assessment_id=b.assessment_id
		WHERE a.position_id=".$id." and a.assessment_id=".$ass_id;
		$testdetails=UlsMenu::callpdorow($query);
        return $testdetails;
    } 
	
	public static function get_assessment_position_dup($id,$ass_id){
		$query="SELECT a.*,b.position_name,c.`assessment_id`,c.`assessment_name` FROM uls_assessment_position a
		left join(SELECT `position_id`,`position_name` FROM `uls_position`) b on a.position_id=b.position_id
		left join(SELECT `assessment_id`,`assessment_name`,`assessment_cycle_type`,`assessment_type`,`self_ass_type`,end_date FROM `uls_assessment_definition`) c on a.assessment_id=c.assessment_id
		WHERE a.position_id=".$id." and a.assessment_id!=".$ass_id;
		$testdetails=UlsMenu::callpdo($query);
        return $testdetails;
    } 
	
	public static function get_assessment_position_report($id,$ass_id){
		$query="SELECT a.* FROM uls_assessment_position a
		left join(SELECT `assessment_id`,`assessment_name`,`assessment_cycle_type`,`assessment_type`,`self_ass_type`,end_date,ass_methods FROM `uls_assessment_definition`) b on a.assessment_id=b.assessment_id
		WHERE a.position_id=".$id." and b.ass_methods='Y' and a.assessment_id!=".$ass_id;
		$testdetails=UlsMenu::callpdorow($query);
        return $testdetails;
    }
}