
<?php

/**
 * UlsAssessmentTestQuestions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessmentTestQuestions extends BaseUlsAssessmentTestQuestions
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	static function gettestquestions($assess_test_id,$test_id,$test_type,$emp_id,$ass_id){
		$sql="SELECT group_concat(distinct(a.`question_id`)) as q_id,a.`competency_id`,count(*)  as q_count,d.comp_def_name,s.scale_name,a.position_id,d.comp_def_id,s.scale_id,ac.assessment_pos_level_id,r.report_id,rs.assessed_scale_id,s.scale_number FROM `uls_assessment_test_questions` a
		left join(SELECT `assessment_id`,`assessment_pos_com_id`,`assessment_pos_level_scale_id`,`assessment_type`,assessment_pos_level_id,position_id FROM `uls_assessment_competencies` where assessment_id=".$ass_id.") ac on ac.assessment_pos_com_id=a.competency_id and ac.position_id=a.position_id
		left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) d on d.comp_def_id=ac.assessment_pos_com_id
		left join (SELECT `scale_id`,`scale_name`,scale_number FROM `uls_level_master_scale`) s on s.scale_id=ac.assessment_pos_level_scale_id
		left join (select report_id,assessment_id,position_id,competency_id,assessed_scale_id,development_area,employee_id,assessor_id from uls_assessment_report where employee_id=$emp_id and assessment_id=".$ass_id." and assessor_id=".$_SESSION['asr_id'].")r on r.assessment_id=ac.assessment_id and r.position_id=ac.position_id and r.competency_id=ac.assessment_pos_com_id 
		left join (select report_id,assessed_scale_id,assessment_type from uls_assessment_report_bytype where assessment_type='$test_type' and assessment_id=".$ass_id.")rs on rs.report_id=r.report_id
		WHERE `assess_test_id`=".$assess_test_id." and `test_id`=".$test_id." and a.assessment_id=".$ass_id." group by `competency_id` ";
		return UlsMenu::callpdo($sql);
	}
	
	static function gettestempcompquestions($assess_test_id,$test_id,$test_type,$emp_id,$ass_id,$comp_ids){
		$sql="SELECT group_concat(distinct(a.`question_id`)) as q_id,a.`competency_id`,count(*)  as q_count,d.comp_def_name,s.scale_name,a.position_id,d.comp_def_id,s.scale_id,ac.assessment_pos_level_id,r.report_id,rs.assessed_scale_id,s.scale_number FROM `uls_assessment_test_questions` a
		left join(SELECT `assessment_id`,`assessment_pos_com_id`,`assessment_pos_level_scale_id`,`assessment_type`,assessment_pos_level_id,position_id FROM `uls_assessment_competencies` where assessment_id=".$ass_id.") ac on ac.assessment_pos_com_id=a.competency_id and ac.position_id=a.position_id
		left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) d on d.comp_def_id=ac.assessment_pos_com_id
		left join (SELECT `scale_id`,`scale_name`,scale_number FROM `uls_level_master_scale`) s on s.scale_id=ac.assessment_pos_level_scale_id
		left join (select report_id,assessment_id,position_id,competency_id,assessed_scale_id,development_area,employee_id,assessor_id from uls_assessment_report where employee_id=$emp_id and assessment_id=".$ass_id." and assessor_id=".$_SESSION['asr_id'].")r on r.assessment_id=ac.assessment_id and r.position_id=ac.position_id and r.competency_id=ac.assessment_pos_com_id 
		left join (select report_id,assessed_scale_id,assessment_type from uls_assessment_report_bytype where assessment_type='$test_type' and assessment_id=".$ass_id.")rs on rs.report_id=r.report_id
		WHERE `assess_test_id`=".$assess_test_id." and `test_id`=".$test_id." and a.assessment_id=".$ass_id."  and ac.assessment_pos_com_id in (".$comp_ids.") group by `competency_id` ";
		return UlsMenu::callpdo($sql);
	}
	
	static function gettestquestionsbycomp($assess_test_id,$test_id,$test_type,$emp_id,$ass_id,$comp){
		$sql="SELECT group_concat(distinct(a.`question_id`)) as q_id,a.`competency_id`,count(*)  as q_count,d.comp_def_name,s.scale_name,a.position_id,d.comp_def_id,s.scale_id,ac.assessment_pos_level_id,r.report_id,rs.assessed_scale_id,s.scale_number FROM `uls_assessment_test_questions` a
		left join(SELECT `assessment_id`,`assessment_pos_com_id`,`assessment_pos_level_scale_id`,`assessment_type`,assessment_pos_level_id,position_id FROM `uls_assessment_competencies` where assessment_id=".$ass_id.") ac on ac.assessment_pos_com_id=a.competency_id and ac.position_id=a.position_id
		left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) d on d.comp_def_id=ac.assessment_pos_com_id
		left join (SELECT `scale_id`,`scale_name`,scale_number FROM `uls_level_master_scale`) s on s.scale_id=ac.assessment_pos_level_scale_id
		left join (select report_id,assessment_id,position_id,competency_id,assessed_scale_id,development_area,employee_id,assessor_id from uls_assessment_report where employee_id=$emp_id and assessment_id=".$ass_id." and assessor_id=".$_SESSION['asr_id'].")r on r.assessment_id=ac.assessment_id and r.position_id=ac.position_id and r.competency_id=ac.assessment_pos_com_id 
		left join (select report_id,assessed_scale_id,assessment_type from uls_assessment_report_bytype where assessment_type='$test_type' and assessment_id=".$ass_id.")rs on rs.report_id=r.report_id
		WHERE `assess_test_id`=".$assess_test_id." and `test_id`=".$test_id." and a.assessment_id=".$ass_id." and a.competency_id='$comp' group by `competency_id` ";
		return UlsMenu::callpdorow($sql);
	}
	
	static function getquestions_info($assess_test_id,$test_id){
		$sql="SELECT a.`question_id` as q_id,a.`competency_id`,d.comp_def_name,q.question_name,a.test_quest_id,a.assessment_test_id,a.question_bank_id  FROM `uls_assessment_test_questions` a
		left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) d on d.comp_def_id=a.competency_id
		left join(SELECT `question_id`,`question_name` FROM `uls_questions`) q on q.question_id=a.question_id
		WHERE `assess_test_id`=".$assess_test_id." and `test_id`=".$test_id."";
		return UlsMenu::callpdo($sql);
	}
	
	static function getcasesquestions_info($assess_test_id,$test_id){
		$sql="SELECT a.`question_id` as q_id,a.`competency_id`,d.comp_def_name,q.casestudy_quest as question_name  FROM `uls_assessment_test_questions` a
		left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) d on d.comp_def_id=a.competency_id
		left join(SELECT `casestudy_quest_id`,`casestudy_quest` FROM `uls_case_study_questions`) q on q.casestudy_quest_id=a.question_id
		WHERE `assess_test_id`=".$assess_test_id." and `test_id`=".$test_id."";
		return UlsMenu::callpdo($sql);
	}
	
	public static function get_question_count_ass($id){
		$testdetails=array();
		if(!empty($id) && is_numeric($id)){
			$query="SELECT count(assessment_test_id) as te_count FROM uls_assessment_test_questions a
			WHERE a.assess_test_id=".$id;
			$testdetails=UlsMenu::callpdorow($query);
		}
		return $testdetails;
    } 
	
	public static function get_question_val($id,$assess_test_id){
		$testdetails=array();
		if(!empty($id) && is_numeric($id)){
			$query="SELECT *,e.comp_def_id,e.comp_def_name,f.scale_name,f.scale_id FROM uls_assessment_test_questions a
			left join (select question_id,question_name,level_id,question_type,scale_id from uls_questions) c on a.question_id=c.question_id
			left join (select comp_def_id,comp_def_name,comp_def_level from uls_competency_definition) e on a.competency_id=e.comp_def_id
			left join (select scale_id,scale_name,level_id from uls_level_master_scale) f on c.level_id=f.level_id and c.scale_id=f.scale_id
			WHERE a.assessment_test_id=".$id." and a.assess_test_id=".$assess_test_id;
			$testdetails=UlsMenu::callpdorow($query);
		}
		return $testdetails;
    }
	
	public static function get_question_ids($assess_test_id,$comp_def_id){
		$testdetails=array();
		if(!empty($assess_test_id) && is_numeric($assess_test_id)){
			$query="SELECT count(assessment_test_id) as te_count,group_concat(a.question_id) as question_ids FROM uls_assessment_test_questions a
			WHERE a.assess_test_id=".$assess_test_id." and a.competency_id=".$comp_def_id;
			$testdetails=UlsMenu::callpdorow($query);
		}
		return $testdetails;
    }
	
	static function get_inbasket_questions_info($assess_test_id,$test_id){
		$sql="SELECT a.`question_id` as q_id,a.`competency_id`,d.comp_def_name,q.casestudy_quest as question_name  FROM `uls_assessment_test_questions` a
		left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) d on d.comp_def_id=a.competency_id
		left join(SELECT `casestudy_quest_id`,`casestudy_quest` FROM `uls_case_study_questions`) q on q.casestudy_quest_id=a.question_id
		WHERE `assess_test_id`=".$assess_test_id." and `test_id`=".$test_id."";
		return UlsMenu::callpdorow($sql);
	}
	
	static function get_fishbone_questions_info($assess_test_id,$test_id){
		$sql="SELECT a.`question_id` as q_id,a.`competency_id`,d.comp_def_name,q.fishbone_quest as question_name  FROM `uls_assessment_test_questions` a
		left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) d on d.comp_def_id=a.competency_id
		left join(SELECT `fishbone_quest_id`,`fishbone_quest` FROM `uls_fishbone_study_questions`) q on q.fishbone_quest_id=a.question_id
		WHERE `assess_test_id`=".$assess_test_id." and `test_id`=".$test_id."";
		return UlsMenu::callpdorow($sql);
	}
	
	static function get_interview_questions($pos_id,$test_type,$emp_id,$ass_id){
		$sql="SELECT d.comp_def_name,s.scale_name,ac.position_id,d.comp_def_id,s.scale_id,ac.assessment_pos_level_id,r.report_id,rs.assessed_scale_id,s.scale_number,r.development_area,rs.interview_ass_value FROM `uls_assessment_competencies` ac 
		left join(SELECT `comp_def_id`,`comp_def_name`,comp_def_category FROM `uls_competency_definition`) d on d.comp_def_id=ac.assessment_pos_com_id
		left join (SELECT `scale_id`,`scale_name`,scale_number FROM `uls_level_master_scale`) s on s.scale_id=ac.assessment_pos_level_scale_id
		left join (select report_id,assessment_id,position_id,competency_id,assessed_scale_id,development_area,employee_id,assessor_id from uls_assessment_report where employee_id=$emp_id and assessment_id=".$ass_id." and assessor_id=".$_SESSION['asr_id'].")r on r.assessment_id=ac.assessment_id and r.position_id=ac.position_id and r.competency_id=ac.assessment_pos_com_id 
		left join (select report_id,assessed_scale_id,assessment_type,interview_ass_value from uls_assessment_report_bytype where assessment_type='$test_type' and assessment_id=".$ass_id.")rs on rs.report_id=r.report_id
		WHERE ac.position_id=".$pos_id." and ac.assessment_id=".$ass_id."";
		//and d.comp_def_category!=10
		return UlsMenu::callpdo($sql);
	}
	
	
	
	static function get_interview_empcomp_questions($pos_id,$test_type,$emp_id,$ass_id,$comp_ids){
		$sql="SELECT d.comp_def_name,s.scale_name,ac.position_id,d.comp_def_id,s.scale_id,ac.assessment_pos_level_id,r.report_id,rs.assessed_scale_id,s.scale_number,r.development_area FROM `uls_assessment_competencies` ac 
		left join(SELECT `comp_def_id`,`comp_def_name`,comp_def_category FROM `uls_competency_definition`) d on d.comp_def_id=ac.assessment_pos_com_id
		left join (SELECT `scale_id`,`scale_name`,scale_number FROM `uls_level_master_scale`) s on s.scale_id=ac.assessment_pos_level_scale_id
		left join (select report_id,assessment_id,position_id,competency_id,assessed_scale_id,development_area,employee_id,assessor_id from uls_assessment_report where employee_id=$emp_id and assessment_id=".$ass_id." and assessor_id=".$_SESSION['asr_id'].")r on r.assessment_id=ac.assessment_id and r.position_id=ac.position_id and r.competency_id=ac.assessment_pos_com_id 
		left join (select report_id,assessed_scale_id,assessment_type from uls_assessment_report_bytype where assessment_type='$test_type' and assessment_id=".$ass_id.")rs on rs.report_id=r.report_id
		WHERE ac.position_id=".$pos_id." and ac.assessment_id=".$ass_id." and ac.assessment_pos_com_id in (".$comp_ids.") and d.comp_def_category!=5";
		return UlsMenu::callpdo($sql);
	}
	
	static function get_count_test($comp_id,$scale_id,$id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		$query="select count(a.assessment_test_id) as test_count from uls_assessment_test_questions a
		left join(SELECT `question_id`,`question_bank_id`,`scale_id` FROM `uls_questions` ) b on a.question_id=b.question_id
		left join(SELECT `question_bank_id`,`comp_def_id` FROM `uls_questionbank`) c on c.question_bank_id=b.question_bank_id
		where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.competency_id=".$comp_id." and b.scale_id=".$scale_id." and a.position_id in (".$id.") group by a.question_id ";
		$compdef=UlsMenu::callpdo($query);
		return $compdef;
	}
	
	static function get_emp_question_count_test($assid,$pos_id,$assess_test_id,$comp_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		$query="select count(*) as que_count from uls_assessment_test_questions a
		where 1 and a.`assess_test_id`=".$assess_test_id." and a.`assessment_id`=".$assid." and a.`position_id`=".$pos_id." and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.competency_id in (".$comp_id.")";
		$compdef=UlsMenu::callpdorow($query);
		return $compdef;
	}
	
	static function getquestions_info_comp($assess_test_id,$test_id,$comp_id){
		$sql="SELECT a.`question_id` as q_id,a.`competency_id`,d.comp_def_name,q.question_name,a.test_quest_id,a.assessment_test_id,a.question_bank_id  FROM `uls_assessment_test_questions` a
		left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) d on d.comp_def_id=a.competency_id
		left join(SELECT `question_id`,`question_name` FROM `uls_questions`) q on q.question_id=a.question_id
		WHERE `assess_test_id`=".$assess_test_id." and `test_id`=".$test_id." and competency_id=".$comp_id."";
		return UlsMenu::callpdo($sql);
	}
	
	static function gettestquestions_report($assess_test_id,$test_id,$test_type,$emp_id,$ass_id){
		$sql="SELECT group_concat(distinct(a.`question_id`)) as q_id,a.`competency_id`,count(*)  as q_count,d.comp_def_name,s.scale_name,a.position_id,d.comp_def_id,s.scale_id,ac.assessment_pos_level_id,s.scale_number FROM `uls_assessment_test_questions` a
		left join(SELECT `assessment_id`,`assessment_pos_com_id`,`assessment_pos_level_scale_id`,`assessment_type`,assessment_pos_level_id,position_id FROM `uls_assessment_competencies` where assessment_id=".$ass_id.") ac on ac.assessment_pos_com_id=a.competency_id and ac.position_id=a.position_id
		left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) d on d.comp_def_id=ac.assessment_pos_com_id
		left join (SELECT `scale_id`,`scale_name`,scale_number FROM `uls_level_master_scale`) s on s.scale_id=ac.assessment_pos_level_scale_id
		WHERE `assess_test_id`=".$assess_test_id." and `test_id`=".$test_id." and a.assessment_id=".$ass_id." group by `competency_id` order by a.competency_id ASC";
		return UlsMenu::callpdo($sql);
	}
	
	
}