<?php

/**
 * UlsAssessmentEmployeeReportGeneration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessmentEmployeeReportGeneration extends BaseUlsAssessmentEmployeeReportGeneration
{
	function preInsert($event){
		 $CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_by=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
    }
	
	static function get_assessment_employees_genreport($id,$pos_id,$emp_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.* from uls_assessment_employee_report_generation a
			where a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.employee_id=".$emp_id." and a.position_id=".$pos_id." and a.assessment_id=".$id." and a.gen_employee_id=".$CI->session->userdata('emp_id');
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	static function report_generation_data(){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		$query="SELECT b.full_name, b.employee_number, b.org_name,b.email, b.position_name,b.office_number,p.position_name as ass_position_name,b.location_name,b.grade_name,b.subgradename,b.bu,d.assessment_name,e.full_name as admin_full_name,e.employee_number as admin_employee_number  FROM `uls_assessment_employee_report_generation` a
		left join (select employee_id,full_name,employee_number,org_name,position_name,email,office_number,location_name,grade_name,subgradename,bu from employee_data group by employee_id)b on b.employee_id=a.employee_id
		left join (select employee_id,full_name,employee_number from employee_data group by employee_id)e on e.employee_id=a.gen_employee_id
		left join(SELECT `position_id`,`position_name` FROM `uls_position`) p on a.position_id=p.position_id
		left join(SELECT `assessment_id`,`assessment_name`,assessment_status FROM `uls_assessment_definition`) d on d.assessment_id=a.assessment_id
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id');
		$compdef=UlsMenu::callpdo($query);
		
		return $compdef;
	}
}