<?php

/**
 * UlsAssessorMaster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessorMaster extends BaseUlsAssessorMaster
{
	 function preInsert($event){
		 $CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_by=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
    }
	
	static function searchcount($name=""){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq=!empty($name)? !empty($sq)? " and assessor_name like '%".$name."%'":" and assessor_name like '%".$name."%'":"";
		$learning="select count(*) as num_count from uls_assessor_master where 1 and  parent_org_id=".$CI->session->userdata('parent_org_id').$sq;
     	$eve=UlsMenu::callpdorow($learning);                
		return $eve['num_count'];
	}
    
    static function search($start,$limit,$name=""){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq=!empty($name)? !empty($sq)? " and a.assessor_name like '%".$name."%'":" and a.assessor_name like '%".$name."%'":"";
		$learnings="select b.value_name as assesstype,c.value_name as assessstatus,a.* from uls_assessor_master a 
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'ASSESSOR_TYPE' AND a.assessor_type = b.value_code
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)c ON c.master_code = 'STATUS' AND a.assessor_status = c.value_code
		where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq limit $limit offset $start";
		$result=UlsMenu::callpdo($learnings);
		return $result;
    }
	
	static function viewassessor($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.value_name as assesstype,c.value_name as assessstatus,a.* from uls_assessor_master a 
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'ASSESSOR_TYPE' AND a.assessor_type = b.value_code
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)c ON c.master_code = 'STATUS' AND a.assessor_status = c.value_code
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessor_id=$id";
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	static function check_assessor($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.value_name as assesstype,c.value_name as assessstatus,a.* from uls_assessor_master a 
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'ASSESSOR_TYPE' AND a.assessor_type = b.value_code
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)c ON c.master_code = 'STATUS' AND a.assessor_status = c.value_code
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.employee_id=$id";
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	
}