<?php

/**
 * UlsAssessmentSkillEvaluationMaster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessmentSkillEvaluationMaster extends BaseUlsAssessmentSkillEvaluationMaster
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	static function get_assessment_skill($id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select  b.`question_id`,b.`question_name`,a.* from uls_assessment_skill_evaluation_master a
			left join (SELECT `question_id`,`question_name`,`scale_id` FROM `uls_questions`) b on b.question_id=a.value_id
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id and a.position_id=".$pos_id;
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function get_assessment_skill_values($type){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		$query="SELECT b.`question_id`,b.`question_name`,b.`scale_id`,b.question_bank_id FROM `uls_questionbank` a 
		left join(SELECT `question_id`,`question_name`,`scale_id`,question_bank_id FROM `uls_questions`) b on a.question_bank_id=b.question_bank_id
		where a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.comp_def_id=13 and b.scale_id=".$type."";
		$compdef=UlsMenu::callpdo($query);
		
		return $compdef;
	}
	
	static function get_assessment_skill_manager($id,$pos_id,$atest_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select  b.`question_id`,b.`question_name`,b.question_type,a.* from uls_assessment_skill_evaluation_master a
			left join (SELECT `question_id`,`question_name`,`scale_id`,question_type FROM `uls_questions`) b on b.question_id=a.value_id
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id and a.position_id=".$pos_id." and a.assess_test_id=".$atest_id;
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function get_assessment_skill_manager_count($id,$pos_id,$atest_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select  count(a.`ass_value_id`) as skill_count from uls_assessment_skill_evaluation_master a
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id and a.position_id=".$pos_id." and a.assess_test_id=".$atest_id;
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
}