<?php

/**
 * UlsAssessorCertifiedInstruments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessorCertifiedInstruments extends BaseUlsAssessorCertifiedInstruments
{
	 function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_by=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
    }
	
	static function getassessorinstruments($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.value_name as instrumentname,c.value_name as inststatus,a.* from uls_assessor_certified_instruments a
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'BEHAVORIAL_INSTRUMENT' AND a.assessor_instrument_name = b.value_code
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)c ON c.master_code = 'STATUS' AND a.assessor_instrument_status = c.value_code
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessor_id=$id";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
}