<?php

/**
 * UlsAssessmentTest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessmentTest extends BaseUlsAssessmentTest
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	public static function get_ass_position($id,$pos_id,$ass_type){
		$query="SELECT a.* FROM uls_assessment_test a
		WHERE a.assessment_id=".$id." and a.position_id=".$pos_id." and a.assessment_type='".$ass_type."'";
		$testdetails=UlsMenu::callpdorow($query);
        return $testdetails;
    } 
	
	public static function get_ass_position_inbasket($id,$pos_id,$ass_type){
		$query="SELECT a.* FROM uls_assessment_test a
		WHERE a.assessment_id=".$id." and a.position_id=".$pos_id." and a.assessment_type='".$ass_type."'";
		$testdetails=UlsMenu::callpdo($query);
        return $testdetails;
    }
	
	public static function test_details($test){
		$query="SELECT a.*,c.assessment_name FROM uls_assessment_test a
		left join (select assessment_id,assessment_name from uls_assessment_definition) c on a.assessment_id=c.assessment_id
		WHERE a.assess_test_id=".$test;
		$testdetails=UlsMenu::callpdorow($query);
        return $testdetails;
    } 
	
	static function assessment_test_vital($id,$limit,$level,$level_sel="",$comp){
		//$comp_ids=!empty($comp)?"where competency_id in (".$comp.")":"";
		$level_query=!empty($level_sel)?"c.scale_id in (".$level.",".$level_sel.")":"c.scale_id=".$level."";
		$query="select b.test_id as test_ids,b.test_quest_id,b.competency_id,b.question_id,c.question_name,c.scale_id,b.question_bank_id,a.assessment_id,a.position_id from uls_competency_test a left join (select test_quest_id,question_id,competency_id,test_id,question_bank_id from uls_competency_test_questions  ) b on a.test_id=b.test_id left join (select question_id,question_name,scale_id from uls_questions) c on b.question_id=c.question_id where a.test_id=".$id." and ".$level_query." and  b.competency_id=".$comp." ORDER BY RAND( )  limit ".$limit." ";
		$role=UlsMenu::callpdo($query);
		return $role;		
	}
	
	static function assessment_test_vital_count($id,$level,$level_sel="",$comp){
		//$comp_ids=!empty($comp)?"where competency_id in (".$comp.")":"";
		$level_query=!empty($level_sel)?"scale_id in (".$level.",".$level_sel.")":"scale_id=".$level."";
		$query="select b.test_id as test_ids,b.test_quest_id,b.competency_id,b.question_id,c.question_name,c.scale_id,b.question_bank_id,a.assessment_id,a.position_id from uls_competency_test a
		left join (select test_quest_id,question_id,competency_id,test_id,question_bank_id from uls_competency_test_questions ) b on a.test_id=b.test_id 
		left join (select question_id,question_name,scale_id from uls_questions where ".$level_query.") c on b.question_id=c.question_id where a.test_id=".$id." and b.competency_id=".$comp."  ORDER BY RAND( )";
		$role=UlsMenu::callpdo($query);
		//echo "<br>";
		return $role;		
	}
	
	static function assessment_view_final($id){
		$query="select b.assessment_test_id,b.test_quest_id,b.competency_id,c.question_id,c.question_name,c.level_id,d.type_flag,e.comp_def_name,e.comp_def_id,f.scale_name,f.scale_id,b.assess_test_id,a.lang_process from uls_assessment_test a
		left join (select assessment_test_id,test_quest_id,question_id,competency_id,assess_test_id from uls_assessment_test_questions) b on a.assess_test_id=b.assess_test_id
		left join (select question_id,question_name,level_id,question_type,scale_id from uls_questions) c on b.question_id=c.question_id
		left join (select type_flag from uls_questions_type) d on c.question_type=d.type_flag
		left join (select comp_def_id,comp_def_name,comp_def_level from uls_competency_definition) e on b.competency_id=e.comp_def_id
		left join (select scale_id,scale_name,level_id from uls_level_master_scale) f on c.level_id=f.level_id and c.scale_id=f.scale_id
		where a.assess_test_id=".$id;
		$role=UlsMenu::callpdo($query);
		return $role;		
	}
	
	static function assessment_view_finals($id){
		$query="select b.assessment_test_id,b.test_quest_id,b.competency_id,c.question_id,c.question_name,c.level_id,d.type_flag,e.comp_def_name,e.comp_def_id,f.scale_name,f.scale_id,b.assess_test_id from uls_assessment_test a
		left join (select assessment_test_id,test_quest_id,question_id,competency_id,assess_test_id from uls_assessment_test_questions) b on a.assess_test_id=b.assess_test_id
		left join (select question_id,question_name,level_id,question_type,scale_id from uls_questions) c on b.question_id=c.question_id
		left join (select type_flag from uls_questions_type) d on c.question_type=d.type_flag
		left join (select comp_def_id,comp_def_name,comp_def_level from uls_competency_definition) e on b.competency_id=e.comp_def_id
		left join (select scale_id,scale_name,level_id from uls_level_master_scale) f on c.level_id=f.level_id and c.scale_id=f.scale_id
		where a.assess_test_id=".$id." order by c.scale_id DESC";
		$role=UlsMenu::callpdo($query);
		return $role;		
	}
	
	static function assessment_testemp($id,$pos_id){
		$query="select a.* from uls_assessment_test a where a.assessment_id=".$id." and a.position_id=".$pos_id." ORDER BY a.`assessment_type` DESC";
		$role=UlsMenu::callpdo($query);
		return $role;		
	}
	
	static function assessment_test($id,$pos_id){
		$query="select a.* from uls_assessment_test a where a.assessment_id=".$id." and a.position_id=".$pos_id." and a.assessment_type!='BEHAVORIAL_INSTRUMENT'";
		$role=UlsMenu::callpdo($query);
		return $role;		
	}
	
	static function assessment_test_report($id,$pos_id){
		$pos_ids=!empty($pos_id)?" and a.position_id=".$pos_id."":"";
		$pos_id_group=!empty($pos_id)?" and a.position_id=".$pos_id."":" group by a.assessment_type";
		$query="select a.* from uls_assessment_test a where a.assessment_id=".$id." $pos_ids $pos_id_group";
		$role=UlsMenu::callpdo($query);
		return $role;		
	}
	
	static function assessment_test_report_status($id,$pos_id){
		$pos_ids=!empty($pos_id)?" and a.position_id=".$pos_id."":"";
		$query="select a.* from uls_assessment_test a where a.assessment_id=".$id." $pos_ids";
		$role=UlsMenu::callpdo($query);
		return $role;		
	}
	
	public static function test_question_value($q_id){
		$query="SELECT a.* FROM uls_question_values a WHERE a.question_id=".$q_id." order by a.scorting_order ASC";
		$testdetails=UlsMenu::callpdo($query);
        return $testdetails;
    } 
	
	public static function get_ass_position_test($id,$pos_id,$ass_type){
		$query="SELECT a.* FROM uls_assessment_test a
		WHERE a.assessment_id=".$id." and a.position_id=".$pos_id." and a.assessment_type='".$ass_type."'";
		$testdetails=UlsMenu::callpdorow($query);
        return $testdetails;
    } 
	
	static function assessment_test_questions($id,$ass_id,$pos_id,$ass_type){
		$query="select b.test_id as test_ids,b.test_quest_id,b.competency_id,b.question_id,c.question_name,c.scale_id,b.question_bank_id,a.assessment_id,a.position_id from uls_competency_test a left join (select test_quest_id,question_id,competency_id,test_id,question_bank_id from uls_competency_test_questions  ORDER BY RAND( )) b on a.test_id=b.test_id left join (select question_id,question_name,scale_id from uls_questions) c on b.question_id=c.question_id where a.test_id=".$id." and a.assessment_id=".$ass_id." and  a.position_id=".$pos_id." and a.test_type_flag='".$ass_type."'";
		$role=UlsMenu::callpdo($query);
		return $role;		
	}
	
	static function assessment_test_question_casestudy($id,$ass_id,$pos_id,$ass_type){
		$query="select b.test_id as test_ids,b.test_quest_id,b.competency_id,b.question_id,c.casestudy_quest,a.assessment_id,a.position_id from uls_competency_test a left join (select test_quest_id,question_id,competency_id,test_id from uls_competency_test_questions  ORDER BY RAND( )) b on a.test_id=b.test_id left join (SELECT `casestudy_quest_id`,`casestudy_id`,`casestudy_quest` FROM `uls_case_study_questions`) c on b.question_id=c.casestudy_quest_id where a.test_id=".$id." and a.assessment_id=".$ass_id." and  a.position_id=".$pos_id." and a.test_type_flag='".$ass_type."'";
		$role=UlsMenu::callpdo($query);
		return $role;		
	}
	
	static function assessment_test_question_fishbone($id,$ass_id,$pos_id,$ass_type){
		$query="select b.test_id as test_ids,b.test_quest_id,b.competency_id,b.question_id,c.fishbone_quest,a.assessment_id,a.position_id from uls_competency_test a left join (select test_quest_id,question_id,competency_id,test_id from uls_competency_test_questions  ORDER BY RAND( )) b on a.test_id=b.test_id left join (SELECT `fishbone_quest_id`,`fishbone_id`,`fishbone_quest` FROM `uls_fishbone_study_questions`) c on b.question_id=c.fishbone_quest_id where a.test_id=".$id." and a.assessment_id=".$ass_id." and  a.position_id=".$pos_id." and a.test_type_flag='".$ass_type."'";
		$role=UlsMenu::callpdo($query);
		return $role;		
	}
	
	static function assessment_test_employee($id){
		$query="select a.*,b.`assessment_name`,b.`assessment_cycle_type`,b.`assessment_type` from uls_assessment_test a 
		left join(SELECT `assessment_id`,`assessment_name`,`assessment_cycle_type`,`assessment_type` FROM `uls_assessment_definition`) b on a.assessment_id=b.assessment_id
		where a.assess_test_id=".$id;
		$role=UlsMenu::callpdorow($query);
		return $role;		
	}
	
	static function assessment_test_score_count($id,$emp_id,$c_id){
		/* $query="select count(fa.correct_flag) as correct from uls_assessment_test a
		LEFT JOIN(select position_id,employee_id,assessment_id,status from uls_assessment_employees) fe on (fe.position_id=a.position_id and fe.assessment_id=a.assessment_id)
		LEFT JOIN(select user_test_response_id,employee_id,user_test_question_id, event_id, text, correct_flag,response_value_id  from uls_utest_responses_assessment where correct_flag='C') fa on (fa.employee_id=fe.employee_id and fa.event_id=a.assess_test_id)
		LEFT JOIN(select assess_test_id,test_id,question_id, competency_id from uls_assessment_test_questions) fc on (fa.user_test_question_id=fc.question_id and fa.event_id=fc.assess_test_id)
		where a.assess_test_id=".$id." and fe.employee_id=".$emp_id." and fe.status='A' and fc.competency_id=".$c_id;
		$role=UlsMenu::callpdorow($query);
		return $role; */
		$query="select count(fa.correct_flag) as correct from uls_assessment_test a
		LEFT JOIN(select assess_test_id,test_id,question_id, competency_id from uls_assessment_test_questions) fc on (a.assess_test_id=fc.assess_test_id)
		LEFT JOIN(select user_test_response_id,employee_id,user_test_question_id, event_id, text, correct_flag,response_value_id  from uls_utest_responses_assessment where correct_flag='C') fa on (fa.user_test_question_id=fc.question_id and fa.event_id=a.assess_test_id)
		
		where a.assess_test_id=".$id." and fa.employee_id=".$emp_id." and fc.competency_id=".$c_id;
		$role=UlsMenu::callpdorow($query);
		return $role;			
	}
	
	static function assessment_test_score_count_total($id,$emp_id,$c_id){
		/* echo $query="select count(fa.correct_flag) as t_correct from uls_assessment_test a
		LEFT JOIN(select position_id,employee_id,assessment_id,status from uls_assessment_employees) fe on (fe.position_id=a.position_id and fe.assessment_id=a.assessment_id)
		LEFT JOIN(select user_test_response_id,employee_id,user_test_question_id, event_id, text, correct_flag,response_value_id  from uls_utest_responses_assessment) fa on (fa.employee_id=fe.employee_id and fa.event_id=a.assess_test_id)
		LEFT JOIN(select assess_test_id,test_id,question_id, competency_id from uls_assessment_test_questions) fc on (fa.user_test_question_id=fc.question_id and fa.event_id=fc.assess_test_id)
		where a.assess_test_id=".$id." and fe.employee_id=".$emp_id." and fe.status='A' and fc.competency_id=".$c_id;
		$role=UlsMenu::callpdorow($query);
		return $role;		 */
		 $query="select count(fc.assessment_test_id) as t_correct from uls_assessment_test a
		LEFT JOIN(select assessment_test_id,assess_test_id,test_id,question_id, competency_id from uls_assessment_test_questions) fc on (a.assess_test_id=fc.assess_test_id)
		where a.assess_test_id=".$id." and fc.competency_id=".$c_id;
		$role=UlsMenu::callpdorow($query);
		return $role;		
	}
	
	static function assessment_test_count($id,$comp){
		$query="select count(b.test_quest_id) as test_count from uls_competency_test a left join (select test_quest_id,competency_id,test_id from uls_competency_test_questions  ORDER BY RAND( )) b on a.test_id=b.test_id where a.test_id=".$id." and  b.competency_id=".$comp;
		$role=UlsMenu::callpdorow($query);
		return $role;		
	}
	
	static function view_assessment_position($id){
		$query="SELECT a. *,b.position_id as p_id,b.position_name,a.assess_test_id FROM uls_assessment_test a 
		LEFT JOIN (SELECT position_id,position_name FROM uls_position GROUP BY position_id)b ON a.position_id = b.position_id 
		WHERE 1 and a.parent_org_id=".$_SESSION['parent_org_id']." and a.assess_test_id=$id";
		$level=UlsMenu::callpdorow($query);
		return $level;
	}
	
	static function get_assessment_position($assess_id,$position_id){
		$query="SELECT b.value_name as assess_type,a.*,c.weightage FROM `uls_assessment_test` a
		left join (select value_id, value_code, value_name, master_code from uls_admin_values group by value_id)b on b.value_code=a.assessment_type and b.master_code='ASSESS_METHOD'
		left join(SELECT `assessment_pos_weightage_id`,`assessment_id`,`position_id`,`assessment_type`,`weightage` FROM `uls_assessment_competencies_weightage`) c on c.assessment_id=a.assessment_id and c.position_id=a.position_id and a.assessment_type=c.assessment_type
		WHERE a.`assessment_id`=$assess_id and a.position_id=$position_id ORDER BY a.`assessment_type` DESC";
		$level=UlsMenu::callpdo($query);
		return $level;
	}
	
	static function get_assessment_position_new($assess_id,$position_id){
		$query="SELECT b.value_name as assess_type,a.*,c.weightage FROM `uls_assessment_test` a
		left join (select value_id, value_code, value_name, master_code from uls_admin_values group by value_id)b on b.value_code=a.assessment_type and b.master_code='ASSESS_METHOD'
		left join(SELECT `assessment_pos_weightage_id`,`assessment_id`,`position_id`,`assessment_type`,`weightage` FROM `uls_assessment_competencies_weightage`) c on c.assessment_id=a.assessment_id and c.position_id=a.position_id and a.assessment_type=c.assessment_type
		WHERE a.`assessment_id`=$assess_id and a.position_id=$position_id and a.assessment_type!='BEHAVORIAL_INSTRUMENT' ORDER BY a.`assessment_type` DESC";
		$level=UlsMenu::callpdo($query);
		return $level;
	}
	
	static function get_assessment_position_beh($assess_id,$position_id){
		$query="SELECT b.value_name as assess_type,a.* FROM `uls_assessment_test` a
		left join (select value_id, value_code, value_name, master_code from uls_admin_values group by value_id)b on b.value_code=a.assessment_type and b.master_code='ASSESS_METHOD'
		WHERE a.`assessment_id`=$assess_id and a.position_id=$position_id and a.assessment_type='BEHAVORIAL_INSTRUMENT' ORDER BY a.`assessment_type` DESC";
		$level=UlsMenu::callpdorow($query);
		return $level;
	}
	
	static function assessment_results($ass_id,$pos_id,$emp_id){
		$query="SELECT b.comp_def_id, b.comp_def_name as comp_def_name,s.scale_number as req_number,group_concat(a.assessed_scale_id) as ass_level,ass.scale_number,avg(ass.scale_number) as final_value,b.comp_def_name_alt FROM `uls_assessment_report` a 
		left join (select scale_id,scale_name,scale_number,level_id from uls_level_master_scale group by scale_id)s on s.scale_id=a.require_scale_id
		left join (select scale_id,scale_name,scale_number from uls_level_master_scale group by scale_id)ass on ass.scale_id=a.assessed_scale_id
		left join (select comp_def_id,comp_def_name,comp_def_short_desc,comp_def_name_alt from uls_competency_definition group by comp_def_id)b on b.comp_def_id=a.competency_id
		WHERE a.assessment_id=$ass_id and  a.`position_id`=$pos_id and a.`employee_id`=$emp_id and a.assessor_id is not NULL group by a.competency_id";
		$role=UlsMenu::callpdo($query);
		return $role;		
	}
	
	static function assessment_results_avg($ass_id,$pos_id,$emp_id){
		$query="SELECT b.comp_def_id, b.comp_def_name as comp_def_name,s.scale_number as req_number,a.assessed_scale_id,ass.scale_number as ass_scale_number,a.assessor_id,c.assessor_val,a.development_area,a.require_scale_id,s.scale_name as req_scale_name,t.comp_cri_code,b.comp_def_name_alt FROM `uls_assessment_report` a 
		left join(SELECT `assessment_pos_assessor_id`,`assessment_id`,`position_id`,`assessor_val`,assessor_id FROM `uls_assessment_position_assessor`) c on c.assessor_id=a.assessor_id and a.assessment_id=c.assessment_id and a.`position_id`=c.position_id
		left join (select scale_id,scale_name,scale_number,level_id from uls_level_master_scale group by scale_id)s on s.scale_id=a.require_scale_id
		left join (select scale_id,scale_name,scale_number from uls_level_master_scale group by scale_id)ass on ass.scale_id=a.assessed_scale_id
		left join (select comp_def_id,comp_def_name,comp_def_short_desc,comp_def_name_alt from uls_competency_definition group by comp_def_id)b on b.comp_def_id=a.competency_id
		left join(SELECT `comp_position_id`,`comp_position_competency_id`,`comp_position_criticality_id` FROM `uls_competency_position_requirements`) p on p.comp_position_id=a.position_id and p.comp_position_competency_id=a.competency_id
		left join(SELECT `comp_cri_id`,`comp_cri_code`,`comp_cri_name` FROM `uls_competency_criticality`) t on t.comp_cri_id=p.comp_position_criticality_id
		WHERE a.assessment_id=$ass_id and  a.`position_id`=$pos_id and a.`employee_id`=$emp_id and a.assessor_id is not NULL group by a.assessor_id,a.competency_id";
		$role=UlsMenu::callpdo($query);
		return $role;		
	}
	
	static function get_count_inbasket($comp_id,$scal_id,$id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		$query="SELECT c.`value_id`,c.`question_id`,c.`comp_def_id`,c.`scale_id` FROM `uls_assessment_test` a 
		left join(SELECT `inb_assess_test_id`,`assess_test_id`,`position_id`,`inbasket_id` FROM `uls_assessment_test_inbasket`) i on i.assess_test_id=a.assess_test_id
		left join(SELECT `question_id`,`question_bank_id`,assess_test_id FROM `uls_assessment_test_questions`) b on b.assess_test_id=i.assess_test_id
		left join(SELECT `value_id`,`question_id`,`comp_def_id`,`scale_id` FROM `uls_question_values`) c on c.question_id=b.question_id
		WHERE a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.`position_id` in (".$id.") and a.`assessment_type`='INBASKET' and c.comp_def_id=".$comp_id." and c.scale_id=".$scal_id." group by c.question_id,c.comp_def_id,c.scale_id";
		$compdef=UlsMenu::callpdo($query);
		return $compdef;
	}
	
	static function get_count_casestudy($comp_id,$scal_id,$id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		$query="SELECT c.`case_map_id`,c.`casestudy_quest_id`,c.`casestudy_id`,c.`comp_def_id`,c.`scale_id` FROM `uls_assessment_test` a 
		left join(SELECT `case_assess_test_id`,`assess_test_id`,`casestudy_id` FROM `uls_assessment_test_casestudy`) i on i.assess_test_id=a.assess_test_id
		left join(SELECT `case_map_id`,`casestudy_quest_id`,`casestudy_id`,`comp_def_id`,`scale_id` FROM `uls_case_study_comp_map`) c on c.casestudy_id=i.casestudy_id
		WHERE a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.`position_id` in (".$id.") and a.`assessment_type`='CASE_STUDY' and c.comp_def_id=".$comp_id." and c.scale_id=".$scal_id." group by c.casestudy_quest_id,c.comp_def_id,c.scale_id";
		$compdef=UlsMenu::callpdo($query);
		return $compdef;
	}
	
	static function get_question_check($id,$pos_id,$comp_id,$que_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		$query="SELECT count(*) as q_count,a.question_id,b.question_name,group_concat(a.position_id) FROM `uls_assessment_test_questions` a 
		left join(SELECT `question_id`,`question_name` FROM `uls_questions`) b on a.question_id=b.question_id WHERE a.`assessment_id`=".$id." and a.question_id=".$que_id." and a.competency_id=".$comp_id." and a.position_id!=".$pos_id." group by a.question_id";
		$compdef=UlsMenu::callpdorow($query);
		return $compdef;
	}
	
	static function assessment_test_feedback($id,$pos_id){
		$query="select a.* from uls_assessment_test a where a.assessment_id=".$id." and a.position_id=".$pos_id." and a.assessment_type='FEEDBACK'";
		$role=UlsMenu::callpdo($query);
		return $role;		
	}
	
	public static function get_ass_position_inbasket_comp($id,$pos_id,$comp_id,$ass_type){
		$query="SELECT distinct(d.`comp_def_id`) as comp_id,b.`assess_test_id`,b.`position_id`,b.`assessment_id`,b.`test_id`,b.`inbasket_id`,b.`assessment_type`,c.`question_id` FROM uls_assessment_test a
		left join(SELECT `assess_test_id`,`position_id`,`assessment_id`,`test_id`,`inbasket_id`,`assessment_type` FROM `uls_assessment_test_inbasket`) b on a.assessment_id=b.assessment_id and a.position_id=b.position_id and a.assess_test_id=b.assess_test_id
		left join(SELECT `assess_test_id`,`test_quest_id`,`test_id`,`question_id`,`question_bank_id` FROM `uls_assessment_test_questions`) c on c.assess_test_id=b.assess_test_id
		left join(SELECT `question_id`,`comp_def_id` FROM `uls_question_values`) d on d.question_id=c.question_id
		WHERE a.assessment_id=".$id." and a.position_id=".$pos_id." and a.assessment_type='".$ass_type."' and d.comp_def_id=".$comp_id." group by d.`comp_def_id`";
		$testdetails=UlsMenu::callpdorow($query);
        return $testdetails;
    } 
	
	public static function get_ass_position_case_comp($id,$pos_id,$comp_id,$ass_type){
		$query="SELECT distinct(d.`comp_def_id`) as comp_id,b.`assess_test_id`,b.`position_id`,b.`assessment_id`,b.`test_id`,b.`casestudy_id`,c.`question_id` FROM uls_assessment_test a
		left join(SELECT `assess_test_id`,`position_id`,`assessment_id`,`test_id`,`casestudy_id` FROM `uls_assessment_test_casestudy`) b on a.assessment_id=b.assessment_id and a.position_id=b.position_id and a.assess_test_id=b.assess_test_id
		left join(SELECT `assess_test_id`,`test_quest_id`,`test_id`,`question_id`,`question_bank_id` FROM `uls_assessment_test_questions`) c on c.assess_test_id=b.assess_test_id
		left join(SELECT `casestudy_id`,`comp_def_id` FROM `uls_case_study_comp_map`) d on d.casestudy_id=b.casestudy_id
		WHERE a.assessment_id=".$id." and a.position_id=".$pos_id." and a.assessment_type='".$ass_type."' and d.comp_def_id=".$comp_id." group by d.`comp_def_id`";
		$testdetails=UlsMenu::callpdorow($query);
        return $testdetails;
    } 
	
	static function get_assessment_position_report($assess_id,$position_id){
		$query="SELECT b.value_name as assess_type,a.* FROM `uls_assessment_test` a
		left join (select value_id, value_code, value_name, master_code from uls_admin_values group by value_id)b on b.value_code=a.assessment_type and b.master_code='ASSESS_METHOD'
		WHERE a.`assessment_id`=$assess_id and a.position_id=$position_id ORDER BY a.`assessment_type` DESC";
		$level=UlsMenu::callpdo($query);
		return $level;
	}
	
}