<?php

/**
 * UlsAssessmentFeedbackEmployees
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessmentFeedbackEmployees extends BaseUlsAssessmentFeedbackEmployees
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
	static function view_feedback($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select e.`employee_number`,e.`full_name`,e.`position_name`,e.`location_name`,p.`position_name` as ass_position_name,a.* from uls_assessment_feedback_employees a
			left join(SELECT `employee_id`,`employee_number`,`full_name`,`position_name`,`location_name` FROM `employee_data`) e on e.employee_id=a.employee_id
			left join(SELECT `position_id`,`position_name` FROM `uls_position`) p on p.position_id=a.position_id
			where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id and a.status='A'";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
  
}