<?php

/**
 * UlsAssessmentTestCasestudy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessmentTestCasestudy extends BaseUlsAssessmentTestCasestudy
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	static function getcasestudyassessment($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select c.value_name,t.test_name,a.*,t.casestudy_id,i.casestudy_name from uls_assessment_test_casestudy a 
			left join (SELECT `test_id`,`test_name`,casestudy_id FROM `uls_competency_test`) t on t.test_id=a.test_id
			left join (SELECT `casestudy_name`,casestudy_id FROM `uls_case_study_master`) i on i.casestudy_id=t.casestudy_id
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)c ON c.master_code = 'STATUS' AND c.value_code=a.status
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assess_test_id=$id order by a.case_assess_test_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function viewcasestudy_count($id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="SELECT a.* FROM `uls_assessment_test_casestudy` a
			WHERE a.`assessment_id`=".$id." and a.position_id=".$pos_id." and a.parent_org_id=".$CI->session->userdata('parent_org_id');
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function viewcasestudy_count_report($id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$pos_ids=!empty($pos_id)?" and a.position_id=".$pos_id."":"";
			$pos_id_group=!empty($pos_id)?" and a.position_id=".$pos_id."":" group by a.assessment_type";
			$query="SELECT a.* FROM `uls_assessment_test_casestudy` a
			WHERE a.`assessment_id`=".$id." ".$pos_ids." and a.parent_org_id=".$CI->session->userdata('parent_org_id')." ".$pos_id_group."";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function viewcasestudy_count_report_status($id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$pos_ids=!empty($pos_id)?" and a.position_id=".$pos_id."":"";
			$query="SELECT a.* FROM `uls_assessment_test_casestudy` a
			WHERE a.`assessment_id`=".$id." ".$pos_ids." and a.parent_org_id=".$CI->session->userdata('parent_org_id');
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function get_casestudy_values($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select  a.* FROM uls_assessment_test_casestudy a where(a.parent_org_id=".$CI->session->userdata('parent_org_id')."  and a.casestudy_id=".$id.")";
        return UlsMenu::callpdo($query);
	}
}