<?php

/**
 * UlsAssessmentEmployeeDevRating
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessmentEmployeeDevRating extends BaseUlsAssessmentEmployeeDevRating
{
	function preInsert($event){
		 $CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	public static function get_emp_rating($ass_id,$pos_id,$emp_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT a.* FROM uls_assessment_employee_dev_rating a
		WHERE a.assessment_id=".$ass_id." and a.position_id=".$pos_id." and a.employee_id=".$emp_id;
		$testdetails=UlsMenu::callpdo($query);
        return $testdetails;
    }
	
	public static function get_emp_rating_details($emp_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT c.comp_def_name,i.comp_def_level_ind_name,a.* FROM uls_assessment_employee_dev_rating a
		left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) c on c.comp_def_id=a.comp_def_id
		left join(SELECT `comp_def_level_ind_id`,`comp_def_level_ind_name` FROM `uls_competency_def_level_indicator`) i on i.comp_def_level_ind_id=a.comp_def_level_ind_id
		WHERE a.employee_id=".$emp_id;
		$testdetails=UlsMenu::callpdo($query);
        return $testdetails;
    }
	
	static function get_status_assessment_loc_tra_report($loc_id,$org_id,$emp_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($loc_id) && is_numeric($loc_id)){
			$sq=!empty($loc_id)? " and a.location_id='$loc_id'":"";
			$sq.=!empty($org_id)? " and a.org_id='$org_id'":"";
			$sq.=!empty($emp_id)? " and a.employee_id='$emp_id'":"";
			$query="select b.full_name, b.employee_number, b.org_name,b.email, ss.position_name as map_pos_name,b.office_number,c.comp_def_name,s.scale_name,i.comp_def_level_ind_name,po.position_structure,b.position_id,po.position_name as pos_name,a.* from uls_assessment_employee_dev_rating a
			left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) c on c.comp_def_id=a.comp_def_id
			left join(SELECT `scale_id`,`scale_name` FROM `uls_level_master_scale`) s on s.scale_id=a.scale_id
			left join(SELECT `comp_def_level_ind_id`,`comp_def_level_ind_name` FROM `uls_competency_def_level_indicator`) i on i.comp_def_level_ind_id=a.comp_def_level_ind_id
			left join (select employee_id,full_name,employee_number,org_name,position_name,email,office_number,position_id from employee_data group by employee_id)b on b.employee_id=a.employee_id
			left join(SELECT `position_id`,`position_structure`,`position_name`,position_structure_id FROM `uls_position`) po on po.position_id=b.position_id
			left join(SELECT `position_id`,`position_structure`,`position_name`,position_structure_id FROM `uls_position` where position_structure='S') ss on ss.position_id=po.position_structure_id
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." ".$sq." order by a.org_id,a.employee_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	
	public static function get_element_details($comp_id,$scale_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT count(a.employee_id) as emp_count,c.comp_def_name,i.comp_def_level_ind_id as ind_id,i.comp_def_level_ind_name,a.* FROM uls_assessment_employee_dev_rating a
		left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) c on c.comp_def_id=a.comp_def_id
		left join(SELECT `comp_def_level_ind_id`,`comp_def_level_ind_name` FROM `uls_competency_def_level_indicator`) i on i.comp_def_level_ind_id=a.comp_def_level_ind_id
		WHERE a.comp_def_id=".$comp_id." and a.scale_id=".$scale_id." group by comp_def_level_ind_id ORDER BY COUNT(a.employee_id) DESC";
		$testdetails=UlsMenu::callpdo($query);
        return $testdetails;
    }
	
	public static function get_element_emp_details($comp_id,$scale_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT e.`employee_number`,e.`full_name`,e.`position_name`,e.`location_name` FROM uls_assessment_employee_dev_rating a 
		left join(SELECT `employee_id`,`employee_number`,`full_name`,`position_name`,`location_name` FROM `employee_data`) e on e.employee_id=a.employee_id
		WHERE a.comp_def_id=".$comp_id." and a.scale_id=".$scale_id." group by a.employee_id";
		$testdetails=UlsMenu::callpdo($query);
        return $testdetails;
    }
	
	static function get_training_need_emp_details($comp_id,$scale_id,$ele_id){
		$results=UlsMenu::callpdo("SELECT e.`employee_number`,e.`full_name`,e.`position_name`,e.`location_name` FROM uls_assessment_employee_dev_rating a 
		left join(SELECT `employee_id`,`employee_number`,`full_name`,`position_name`,`location_name` FROM `employee_data`) e on e.employee_id=a.employee_id
		WHERE a.comp_def_id=".$comp_id." and a.scale_id=".$scale_id." and a.comp_def_level_ind_id=".$ele_id);
		echo "<div class='table-wrap' style='height: 400px;overflow-y: auto;'>
			<div class='table-responsive' id='assesstable'>
				<table id='datable_2' class='table table-bordered' >
					<thead>
						<th>S.No</th>
						<th>Employee Code</th>
						<th>Employee Name</th>
						<th>Designation</th>
						<th>Location</th>
					</thead>
					<tbody>";
					foreach($results as $key=>$result){
						echo "<tr>
						<td>".($key+1)."</td>
						<td>".$result['employee_number']."</td>
						<td>".$result['full_name']."</td>
						<td>".$result['position_name']."</td>
						<td>".$result['location_name']."</td>
						</tr>";
					}
		echo "</tbody>
				</table>
			</div>
		</div>";
	}
	
	public static function get_report_info($com_id,$scale_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT a.* FROM uls_assessment_employee_dev_rating a
		WHERE a.comp_def_id=".$com_id." and a.scale_id=".$scale_id;
		$testdetails=UlsMenu::callpdorow($query);
        return $testdetails;
    }
	
	public static function get_employee_info($comp_id,$scale_id,$ele_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT e.`employee_number`,e.`full_name`,e.`position_name`,e.`location_name` FROM uls_assessment_employee_dev_rating a 
		left join(SELECT `employee_id`,`employee_number`,`full_name`,`position_name`,`location_name` FROM `employee_data`) e on e.employee_id=a.employee_id
		WHERE a.comp_def_id=".$comp_id." and a.scale_id=".$scale_id." and a.comp_def_level_ind_id in (".$ele_id.") group by a.employee_id";
		$testdetails=UlsMenu::callpdo($query);
        return $testdetails;
    }
	
	public static function get_emp_rating_view($ass_id,$pos_id,$emp_id,$comp_id,$scale_id,$ele_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT a.* FROM uls_assessment_employee_dev_rating a
		WHERE a.assessment_id=".$ass_id." and a.position_id=".$pos_id." and a.employee_id=".$emp_id." and  a.comp_def_id=".$comp_id." and a.scale_id=".$scale_id." and a.comp_def_level_ind_id=".$ele_id;
		$testdetails=UlsMenu::callpdorow($query);
        return $testdetails;
    }
	
	public static function get_emp_rating_view_final($ass_id,$pos_id,$emp_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT a.`program_name` as pro_name,c.comp_def_name,c.comp_def_id,s.scale_name,s.level_id,s.scale_number,a.comp_def_pro_id,s.scale_id FROM uls_competency_def_level_indicator_programs a left join(SELECT `dev_rating_id`,`comp_def_level_ind_id`,`comp_def_id`,`scale_id`,employee_id,assessment_id,position_id FROM `uls_assessment_employee_dev_rating`) b on a.comp_def_level_ind_id=b.comp_def_level_ind_id and a.comp_def_id=b.comp_def_id and a.comp_def_level_id=b.scale_id 
		left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) c on c.comp_def_id=b.comp_def_id
		left join(SELECT `scale_id`,`scale_name`,level_id,scale_number FROM `uls_level_master_scale`) s on s.scale_id=b.scale_id
		where b.assessment_id=".$ass_id." and b.position_id=".$pos_id." and b.employee_id=".$emp_id." group by a.`program_name` order by c.comp_def_name,a.`program_name` ASC";
		$testdetails=UlsMenu::callpdo($query);
        return $testdetails;
	}
	
	public static function get_emp_indicator_final($ass_id,$pos_id,$emp_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select c.comp_def_name,s.scale_name,i.comp_def_level_ind_name,a.* from uls_assessment_employee_dev_rating a
		left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) c on c.comp_def_id=a.comp_def_id
		left join(SELECT `scale_id`,`scale_name` FROM `uls_level_master_scale`) s on s.scale_id=a.scale_id
		left join(SELECT `comp_def_level_ind_id`,`comp_def_level_ind_name` FROM `uls_competency_def_level_indicator`) i on i.comp_def_level_ind_id=a.comp_def_level_ind_id
		where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=".$ass_id." and a.position_id=".$pos_id." and a.employee_id=".$emp_id." order by a.comp_def_id ASC";
		$testdetails=UlsMenu::callpdo($query);
        return $testdetails;
	}
	
}