<?php

/**
 * UlsAssessmentEmployeeSelectPrograms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessmentEmployeeSelectPrograms extends BaseUlsAssessmentEmployeeSelectPrograms
{
	function preInsert($event){
		 $CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	public static function get_emp_rating_final($ass_id,$pos_id,$emp_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT b.`program_name` as pro_name,c.comp_def_name,c.comp_def_id,s.scale_name,s.level_id,s.scale_number,b.comp_def_pro_id,s.scale_id,a.ass_scale_id,a.tna_year FROM uls_assessment_employee_select_programs a 
		left join(SELECT `comp_def_pro_id`,`comp_def_level_ind_id`,`comp_def_id`,`comp_def_level_id`,`program_name` FROM `uls_competency_def_level_indicator_programs`) b on b.comp_def_pro_id=a.comp_def_pro_id
		left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) c on c.comp_def_id=b.comp_def_id
		left join(SELECT `scale_id`,`scale_name`,level_id,scale_number FROM `uls_level_master_scale`) s on s.scale_id=b.comp_def_level_id
		where a.assessment_id=".$ass_id." and a.position_id=".$pos_id." and a.employee_id=".$emp_id." group by b.program_name order by a.tna_year,c.comp_def_name,b.`program_name` ASC";
		$testdetails=UlsMenu::callpdo($query);
        return $testdetails;
	}
	
	public static function get_emp_rating_final_next($ass_id,$pos_id,$emp_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT b.`program_name` as pro_name,c.comp_def_name,c.comp_def_id,s.scale_name,s.level_id,s.scale_number,b.comp_def_pro_id,s.scale_id,a.ass_scale_id,a.tna_year FROM uls_assessment_employee_select_programs a 
		left join(SELECT `comp_def_pro_id`,`comp_def_level_ind_id`,`comp_def_id`,`comp_def_level_id`,`program_name` FROM `uls_competency_def_level_indicator_programs`) b on b.comp_def_pro_id=a.comp_def_pro_id
		left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) c on c.comp_def_id=b.comp_def_id
		left join(SELECT `scale_id`,`scale_name`,level_id,scale_number FROM `uls_level_master_scale`) s on s.scale_id=b.comp_def_level_id
		where a.assessment_id=".$ass_id." and a.position_id=".$pos_id." and a.employee_id=".$emp_id."  and a.tna_year=2 group by b.program_name order by a.tna_year,c.comp_def_name,b.`program_name` ASC";
		$testdetails=UlsMenu::callpdo($query);
        return $testdetails;
	}
}