<?php

/**
 * UlsAssessmentEmployeeFinalReport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessmentEmployeeFinalReport extends BaseUlsAssessmentEmployeeFinalReport
{
	function preInsert($event){
		 $CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_by=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
    }
	
	static function get_assessment_employees_report($id,$pos_id,$emp_id,$comp_id,$scale_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.* from uls_assessment_employee_final_report a
			where a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.employee_id=".$emp_id." and a.position_id=".$pos_id." and a.assessment_id=".$id." and a.competency_id=".$comp_id." and a. require_scale_id=".$scale_id;
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	
	
	static function get_assessment_employees_report_final($id,$pos_id,$emp_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.*,b.comp_def_name,r.scale_name from uls_assessment_employee_final_report a
			left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) b on b.comp_def_id=a.competency_id
			left join(SELECT `scale_id`,`scale_number`,`scale_name` FROM `uls_level_master_scale`) r on r.scale_id=a.require_scale_id
			where a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.employee_id=".$emp_id." and a.position_id=".$pos_id." and a.assessment_id=".$id." group by a.`competency_id` order by a.competency_id ASC";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function get_assessment_employees_report_final_comp($id,$pos_id,$emp_id,$comp_ids){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.*,b.comp_def_name,r.scale_name from uls_assessment_employee_final_report a
			left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) b on b.comp_def_id=a.competency_id
			left join(SELECT `scale_id`,`scale_number`,`scale_name` FROM `uls_level_master_scale`) r on r.scale_id=a.require_scale_id
			where a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.employee_id=".$emp_id." and a.position_id=".$pos_id." and a.assessment_id=".$id." and a.competency_id in (".$comp_ids.") group by a.`competency_id` order by a.competency_id ASC";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function get_assessment_employees_comp_final($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.*,b.comp_def_name,e.`employee_number`,e.`full_name`,e.`org_name`,e.`position_name`,e.`grade_name`,e.`location_name`,r.rating_number,r.rating_name_scale from uls_assessment_employee_final_report a
			left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) b on b.comp_def_id=a.competency_id
			left join(SELECT `employee_id`,`employee_number`,`full_name`,`org_name`,`position_name`,`grade_name`,`location_name` FROM `employee_data`) e on e.employee_id=a.employee_id
			left join(SELECT `scale_id`,`rating_id`,`rating_number`,`rating_name_scale` FROM `uls_level_master_scale`) r on r.scale_id=a.require_scale_id
			where a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=".$id;
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
}