<?php

/**
 * UlsAssessmentCompetencies
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessmentCompetencies extends BaseUlsAssessmentCompetencies
{
	 function preInsert($event){
		 $CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_by=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
    }
	
	static function getassessmentcompetencies($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.comp_def_name as comp_def_name, c.level_name as level_name, d.scale_name as scale_name, e.value_name as assesstype, a.* from uls_assessment_competencies a
			left join (select comp_def_id,comp_def_name from uls_competency_definition group by comp_def_id)b on b.comp_def_id=a.assessment_pos_com_id
			left join (select level_id,level_name from uls_level_master group by level_id)c on c.level_id=a.assessment_pos_level_id
			left join (select scale_id,scale_name from uls_level_master_scale group by scale_id)d on d.scale_id=a.assessment_pos_level_scale_id
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)e ON e.master_code = 'ASSESS_METHOD' AND e.value_code=a.assessment_type
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id order by a.assessment_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function getassessmentcompetencies_test($id,$pos_id,$ass_type,$test_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.comp_position_id,b.comp_position_competency_id,b.comp_position_level_id,b.comp_position_level_scale_id,b.comp_position_criticality_id,a.assessment_pos_comp_id,f.comp_cri_id as cri_ids,t.test_id,c.comp_def_name,e.scale_name,a.assessment_type,a.assessment_scale_id,a.assessment_que_count  from  uls_assessment_competencies a
			left join(select comp_position_id,comp_position_competency_id,comp_position_level_id,comp_position_level_scale_id,comp_position_criticality_id from uls_competency_position_requirements ) b on a.position_id=b.comp_position_id and a.assessment_pos_com_id=b.comp_position_competency_id and a.assessment_pos_level_id=b.comp_position_level_id and a.assessment_pos_level_scale_id=b.comp_position_level_scale_id
			left join(select test_id,assessment_id,position_id from uls_competency_test ) t on t.assessment_id=a.assessment_id and t.position_id=a.position_id
			left join(select comp_def_id,comp_def_name,comp_def_level from uls_competency_definition ) c on b.comp_position_competency_id=c.comp_def_id
			left join(select level_id,level_name from uls_level_master) d on c.comp_def_level=d.level_id
			left join(select scale_id,scale_name,level_id from uls_level_master_scale) e on b.comp_position_level_scale_id=e.scale_id
			left join (select comp_cri_id,comp_cri_name from uls_competency_criticality) f 	on b.comp_position_criticality_id=f.comp_cri_id
			where a.position_id=".$pos_id." and t.test_id=".$test_id." and find_in_set('".$ass_type."',a.assessment_type)>0 and a.assessment_id=".$id;
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function getassessment_competencies($id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.comp_def_id, b.comp_def_name as comp_def_name, c.level_name as level_name,d.scale_id, d.scale_name as scale_name, e.value_name as assesstype,f.comp_cri_name, a.* from uls_assessment_competencies a
			left join (select comp_def_id,comp_def_name from uls_competency_definition group by comp_def_id)b on b.comp_def_id=a.assessment_pos_com_id
			left join (select level_id,level_name from uls_level_master group by level_id)c on c.level_id=a.assessment_pos_level_id
			left join (select scale_id,scale_name from uls_level_master_scale group by scale_id)d on d.scale_id=a.assessment_pos_level_scale_id
			left join(select comp_position_id,comp_position_competency_id,comp_position_level_id,comp_position_level_scale_id,comp_position_criticality_id from uls_competency_position_requirements ) p on a.position_id=p.comp_position_id and a.assessment_pos_com_id=p.comp_position_competency_id and a.assessment_pos_level_id=p.comp_position_level_id and a.assessment_pos_level_scale_id=p.comp_position_level_scale_id
			left join (select comp_cri_id,comp_cri_name from uls_competency_criticality) f 	on p.comp_position_criticality_id=f.comp_cri_id
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)e ON e.master_code = 'ASSESS_METHOD' AND e.value_code=a.assessment_type
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id and a.position_id=$pos_id order by a.assessment_id,f.comp_cri_name asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function getassessment_competencies_summary($id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.comp_def_id, b.comp_def_name as comp_def_name, c.level_name as level_name,d.scale_id, d.scale_name as scale_name, e.value_name as assesstype,r.report_id,rs.assessed_scale_id,r.assessed_scale_id as final_scaled_id,r.development_area, a.* from uls_assessment_competencies a
			left join (select comp_def_id,comp_def_name from uls_competency_definition group by comp_def_id)b on b.comp_def_id=a.assessment_pos_com_id
			left join (select level_id,level_name from uls_level_master group by level_id)c on c.level_id=a.assessment_pos_level_id
			left join (select scale_id,scale_name from uls_level_master_scale group by scale_id)d on d.scale_id=a.assessment_pos_level_scale_id
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)e ON e.master_code = 'ASSESS_METHOD' AND e.value_code=a.assessment_type
			left join (select report_id,assessment_id,position_id,competency_id,assessed_scale_id,development_area from uls_assessment_report)r on r.assessment_id=a.assessment_id and r.position_id=a.position_id and r.competency_id=a.assessment_pos_com_id
			left join (select report_id,assessed_scale_id from uls_assessment_report_bytype)rs on rs.report_id=r.report_id
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id and a.position_id=$pos_id order by a.assessment_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	
	static function getassessment_competencies_type($id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.comp_def_id, b.comp_def_name as comp_def_name, c.level_name as level_name,d.scale_id, d.scale_name as scale_name,f.comp_cri_id,f.comp_cri_code,f.comp_cri_name,a.* from uls_assessment_competencies a
			left join (select comp_position_id,comp_position_competency_id,comp_position_criticality_id from uls_competency_position_requirements)p on p.comp_position_id=a.position_id and p.comp_position_competency_id=a.assessment_pos_com_id
			left join (select comp_def_id,comp_def_name from uls_competency_definition group by comp_def_id)b on b.comp_def_id=a.assessment_pos_com_id
			left join (select level_id,level_name from uls_level_master group by level_id)c on c.level_id=a.assessment_pos_level_id
			left join (select scale_id,scale_name from uls_level_master_scale group by scale_id)d on d.scale_id=a.assessment_pos_level_scale_id
			left join (select comp_cri_id,comp_cri_name,comp_cri_code from uls_competency_criticality group by comp_cri_id)f on f.comp_cri_id=p.comp_position_criticality_id
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id and a.position_id=$pos_id and a.`assessment_type` like '%TEST%' order by p.comp_position_criticality_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function getassessment_competencies_emp($id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.comp_def_id, b.comp_def_name as comp_def_name, c.level_name as level_name,d.scale_id, d.scale_name as scale_name,f.comp_cri_id,f.comp_cri_code,f.comp_cri_name,a.* from uls_assessment_competencies a
			left join (select comp_position_id,comp_position_competency_id,comp_position_criticality_id from uls_competency_position_requirements)p on p.comp_position_id=a.position_id and p.comp_position_competency_id=a.assessment_pos_com_id
			left join (select comp_def_id,comp_def_name from uls_competency_definition group by comp_def_id)b on b.comp_def_id=a.assessment_pos_com_id
			left join (select level_id,level_name from uls_level_master group by level_id)c on c.level_id=a.assessment_pos_level_id
			left join (select scale_id,scale_name from uls_level_master_scale group by scale_id)d on d.scale_id=a.assessment_pos_level_scale_id
			left join (select comp_cri_id,comp_cri_name,comp_cri_code from uls_competency_criticality group by comp_cri_id)f on f.comp_cri_id=p.comp_position_criticality_id
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id and a.position_id=$pos_id order by p.comp_position_criticality_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function getassessmentcompetencies_report($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.comp_def_name as comp_def_name, c.level_name as level_name, d.scale_name as scale_name, e.value_name as assesstype,p.position_name,ci.comp_cri_name,a.* from uls_assessment_competencies a
			left join(SELECT `position_id`,`position_name`,`position_structure` FROM `uls_position`) p on p.position_id=a.position_id
			left join (select comp_def_id,comp_def_name from uls_competency_definition group by comp_def_id)b on b.comp_def_id=a.assessment_pos_com_id
			left join (select level_id,level_name from uls_level_master group by level_id)c on c.level_id=a.assessment_pos_level_id
			left join (select scale_id,scale_name from uls_level_master_scale group by scale_id)d on d.scale_id=a.assessment_pos_level_scale_id
			left join(SELECT `comp_position_req_id`,`comp_position_id`,`comp_position_competency_id`,`comp_position_level_id`,`comp_position_level_scale_id`,`comp_position_criticality_id` FROM `uls_competency_position_requirements`) pi on pi.comp_position_id=a.position_id and pi.comp_position_competency_id=a.assessment_pos_com_id
			left join(SELECT `comp_cri_id`,`comp_cri_code`,`comp_cri_name` FROM `uls_competency_criticality`) ci on ci.comp_cri_id=pi.comp_position_criticality_id
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)e ON e.master_code = 'ASSESS_METHOD' AND e.value_code=a.assessment_type
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id order by a.position_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function get_casestudy_competencies($id,$pos_id,$comp_id,$scale_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.* from uls_assessment_competencies a
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id and a.position_id=$pos_id and a.assessment_pos_com_id=".$comp_id." and a.assessment_pos_level_scale_id=".$scale_id;
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	static function get_assessment_competencies_report($id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$sq=!empty($pos_id)?" and a.position_id=".$pos_id."":"";
			$query="select b.comp_def_id,b.comp_def_name as comp_def_name,a.*,d.scale_name as scale_name,d.scale_id,ci.comp_cri_name,d.scale_number from uls_assessment_competencies a
			left join (select comp_def_id,comp_def_name,comp_def_category from uls_competency_definition group by comp_def_id)b on b.comp_def_id=a.assessment_pos_com_id
			left join (select scale_id,scale_name,scale_number from uls_level_master_scale group by scale_id)d on d.scale_id=a.assessment_pos_level_scale_id
			left join(SELECT `comp_position_req_id`,`comp_position_id`,`comp_position_competency_id`,`comp_position_level_id`,`comp_position_level_scale_id`,`comp_position_criticality_id` FROM `uls_competency_position_requirements`) pi on pi.comp_position_id=a.position_id and pi.comp_position_competency_id=a.assessment_pos_com_id
			left join(SELECT `comp_cri_id`,`comp_cri_code`,`comp_cri_name` FROM `uls_competency_criticality`) ci on ci.comp_cri_id=pi.comp_position_criticality_id
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id $sq and b.comp_def_category!=5 group by a.assessment_pos_com_id,a.assessment_pos_level_scale_id order by d.scale_number ASC";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function get_competencies_count(){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		$query="select count(distinct(a.assessment_pos_com_id)) as comp_count from uls_assessment_competencies a
		left join(SELECT `comp_def_id`,`comp_def_name`,comp_def_category FROM `uls_competency_definition`) b on a.assessment_pos_com_id=b.comp_def_id
		where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and b.comp_def_category!=5";
		$compdef=UlsMenu::callpdorow($query);
		return $compdef;
	}
	
	static function get_competencies_details(){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		$query="select b.comp_def_id,b.comp_def_name,c.scale_name,c.scale_id from uls_assessment_competencies a
		left join(SELECT `comp_def_id`,`comp_def_name`,comp_def_category FROM `uls_competency_definition`) b on a.assessment_pos_com_id=b.comp_def_id
		left join(SELECT `scale_id`,`scale_number`,`scale_name` FROM `uls_level_master_scale`) c on c.scale_id=a.assessment_pos_level_scale_id
		where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and b.comp_def_category!=5 group by a.assessment_pos_com_id,a.assessment_pos_level_scale_id";
		$compdef=UlsMenu::callpdo($query);
		return $compdef;
	}
	
	static function get_competencies_count_pos($id,$scale_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select count(distinct(s.position_id)) as pos_count,group_concat(distinct(a.position_id)) as pos_ids from uls_assessment_competencies a
			left join(SELECT `position_id`,`position_structure`,`position_name`,position_structure_id FROM `uls_position` where position_structure='S') s on s.position_id=a.position_id
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_pos_com_id=".$id." and a.assessment_pos_level_scale_id=".$scale_id;
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	static function get_comp_posdetails($comp_id,$scale_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$results=UlsMenu::callpdo("select p.position_name from uls_assessment_competencies a
		left join(SELECT `position_id`,`position_name`,`position_structure` FROM `uls_position` where position_structure='S') p on p.position_id=a.position_id
		where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_pos_com_id=".$comp_id." and a.assessment_pos_level_scale_id=".$scale_id." group by a.position_id");
		echo "<div style='height: 300px;overflow: auto;' align='center'><div class='table-responsive'>
				<table class='table table-hover table-bordered mb-0'>
					<thead>
						<tr>
							<th>S.No</th>
							<th>Position Name</th>
						</tr>
					</thead>
					<tbody>";
					foreach($results as $key=>$result){
						echo "<tr>
							<td>".($key+1)."</td>
							<td>".$result['position_name']."</td>
						</tr>";
					}
					echo "<tbody>
				</table>
			</div>
		</div>";
	}
	
	static function getassessment_competency_scale($id,$pos_id,$comp_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select d.scale_id, d.scale_name as scale_name,a.* from uls_assessment_competencies a
			left join (select level_id,level_name from uls_level_master group by level_id)c on c.level_id=a.assessment_pos_level_id
			left join (select scale_id,scale_name from uls_level_master_scale group by scale_id)d on d.scale_id=a.assessment_pos_level_scale_id
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id and a.position_id=$pos_id and a.assessment_pos_com_id=".$comp_id." order by a.assessment_id asc";
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	/* static function get_assessment_emp_competencies_report($id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$sq=!empty($pos_id)?" and a.position_id=".$pos_id."":"";
			$query="select eb.full_name, eb.employee_number, eb.org_name,eb.email, eb.position_name,eb.office_number,eb.location_name,eb.grade_name,eb.subgradename,eb.bu,b.comp_def_id,b.comp_def_name as comp_def_name,d.scale_name as scale_name,ci.comp_cri_name,d.scale_number,r.assessed_value from uls_assessment_competencies a
			left join (select comp_def_id,comp_def_name,comp_def_category from uls_competency_definition group by comp_def_id)b on b.comp_def_id=a.assessment_pos_com_id
			left join (select scale_id,scale_name,scale_number from uls_level_master_scale group by scale_id)d on d.scale_id=a.assessment_pos_level_scale_id
			left join(SELECT `comp_position_req_id`,`comp_position_id`,`comp_position_competency_id`,`comp_position_level_id`,`comp_position_level_scale_id`,`comp_position_criticality_id` FROM `uls_competency_position_requirements`) pi on pi.comp_position_id=a.position_id and pi.comp_position_competency_id=a.assessment_pos_com_id
			left join(SELECT `comp_cri_id`,`comp_cri_code`,`comp_cri_name` FROM `uls_competency_criticality`) ci on ci.comp_cri_id=pi.comp_position_criticality_id
			left join(SELECT `assessment_id`,`position_id`,`employee_id`,`status` FROM `uls_assessment_employees`) e on e.assessment_id=a.assessment_id and e.position_id=a.position_id
			left join (select employee_id,full_name,employee_number,org_name,position_name,email,office_number,location_name,grade_name,subgradename,bu from employee_data group by employee_id)eb on eb.employee_id=e.employee_id
			left join(SELECT `assessment_id`,`position_id`,`employee_id`,`competency_id`,`require_scale_id`,assessed_value FROM `uls_assessment_employee_final_report`) r on r.assessment_id=a.assessment_id and r.position_id=a.position_id and r.competency_id=a.assessment_pos_com_id and r.require_scale_id=a.assessment_pos_level_scale_id and r.employee_id=e.employee_id
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=".$id." $sq group by e.employee_id,a.assessment_pos_com_id,a.assessment_pos_level_scale_id  order by e.employee_id,e.position_id ASC";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	} */
	
	static function get_assessment_emp_competencies_report($id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$sq=!empty($pos_id)?" and a.position_id=".$pos_id."":"";
			$query="select eb.full_name, eb.employee_number, eb.org_name,eb.email, eb.position_name,eb.office_number,eb.location_name,eb.grade_name,eb.subgradename,eb.bu,b.comp_def_id,b.comp_def_name as comp_def_name,d.scale_name as scale_name,d.scale_number,r.assessed_value,p.position_name as ass_position_name from uls_assessment_employees a
			left join(SELECT `position_id`,`position_name` FROM `uls_position`) p on a.position_id=p.position_id
			left join (select employee_id,full_name,employee_number,org_name,position_name,email,office_number,location_name,grade_name,subgradename,bu from employee_data group by employee_id)eb on eb.employee_id=a.employee_id
			left join(SELECT `assessment_id`,`position_id`,`employee_id`,`competency_id`,`require_scale_id`,assessed_value FROM `uls_assessment_employee_final_report`) r on r.assessment_id=a.assessment_id and r.position_id=a.position_id and r.employee_id=a.employee_id
			left join (select comp_def_id,comp_def_name,comp_def_category from uls_competency_definition group by comp_def_id)b on b.comp_def_id=r.competency_id
			left join (select scale_id,scale_name,scale_number from uls_level_master_scale group by scale_id)d on d.scale_id=r.require_scale_id
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=".$id." $sq order by a.position_id,a.employee_id ASC";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function get_assessment_competency_scale($id,$pos_id,$comp_ids){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.* from uls_assessment_competencies a
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id and a.position_id=$pos_id and a.assessment_pos_com_id in (".$comp_ids.")";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function get_competencies_report($id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.comp_def_name as comp_def_name,a.* from uls_assessment_competencies a
			left join (select comp_def_id,comp_def_name from uls_competency_definition group by comp_def_id)b on b.comp_def_id=a.assessment_pos_com_id
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id and a.position_id=$pos_id order by a.assessment_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
}