<?php

/**
 * UlsAssessmentReportFinal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessmentReportFinal extends BaseUlsAssessmentReportFinal
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
		$this->assessor_id=$CI->session->userdata('asr_id');
        $this->last_modified_by=$CI->session->userdata('user_id');
		$this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
		$this->assessor_id=$CI->session->userdata('asr_id');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
		$this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
	static function assessment_assessor_final($ass_id,$pos_id,$emp_id,$assessor_id){
		$query="select a.* from uls_assessment_report_final a where a.assessment_id=".$ass_id." and a.position_id=".$pos_id." and a.employee_id=".$emp_id." and a.assessor_id=".$assessor_id." and a.status='A' ";
		$role=UlsMenu::callpdorow($query);
		return $role;		
	}
	
	static function assessment_report_final($ass_id,$pos_id,$emp_id){
		$query="select a.* from uls_assessment_report_final a where a.assessment_id=".$ass_id." and a.position_id=".$pos_id." and a.employee_id=".$emp_id;
		$role=UlsMenu::callpdo($query);
		return $role;		
	}
	
	static function assessment_report_final_admin($ass_id,$pos_id,$emp_id){
		$query="select a.* from uls_assessment_report_final a where a.assessment_id=".$ass_id." and a.position_id=".$pos_id." and a.employee_id=".$emp_id;
		$role=UlsMenu::callpdorow($query);
		return $role;		
	}
	
	static function assessment_assessor_report($ass_id,$pos_id,$assessor_id){
		$query="select count(*) as comp_total from uls_assessment_report_final a where a.assessment_id=".$ass_id." and a.position_id=".$pos_id." and a.assessor_id=".$assessor_id." and a.status='A' ";
		$role=UlsMenu::callpdorow($query);
		return $role;		
	}
	
	static function assessment_employee_assessor_report($ass_id){
		$query="select b.`employee_id`,b.`employee_number`,b.`full_name`,b.`org_name`,b.`position_name`,b.`location_name` ,m.assessor_name,a.* from uls_assessment_report_final a 
		left join(SELECT `employee_id`,`employee_number`,`full_name`,`org_name`,`position_name`,`location_name` FROM `employee_data`) b on b.employee_id=a.employee_id
		left join(SELECT `assessor_id`,`assessor_name` FROM `uls_assessor_master`) m on m.assessor_id=a.assessor_id
		where a.assessment_id=".$ass_id." and a.status='A' ";
		$role=UlsMenu::callpdo($query);
		return $role;		
	}
	
	static function assessment_employee_interview_assessor_report($ass_id,$pos_id){
		$query="select b.`employee_id`,b.`employee_number`,b.`full_name`,b.`org_name`,b.`position_name`,b.`location_name` ,m.assessor_name,a.* from uls_assessment_report_final a 
		left join(SELECT `employee_id`,`employee_number`,`full_name`,`org_name`,`position_name`,`location_name` FROM `employee_data`) b on b.employee_id=a.employee_id
		left join(SELECT `assessor_id`,`assessor_name` FROM `uls_assessor_master`) m on m.assessor_id=a.assessor_id
		where a.assessment_id=".$ass_id." and a.position_id=".$pos_id." and a.status='A' ";
		$role=UlsMenu::callpdo($query);
		return $role;		
	}
	
	/* static function assessment_employee_interview_assessor_report($ass_id){
		$query="select b.`employee_id`,b.`employee_number`,b.`full_name`,b.`org_name`,b.`position_name`,b.`location_name` ,m.assessor_name,e.comp_ids,a.* from uls_assessment_report_final a 
		left join(SELECT `assessment_id`,`position_id`,`employee_id`,`comp_ids` FROM `uls_assessment_employees`) e on e.assessment_id=a.assessment_id and e.position_id=a.position_id and e.employee_id=a.employee_id
		left join(SELECT `employee_id`,`employee_number`,`full_name`,`org_name`,`position_name`,`location_name` FROM `employee_data`) b on b.employee_id=a.employee_id
		left join(SELECT `assessor_id`,`assessor_name` FROM `uls_assessor_master`) m on m.assessor_id=a.assessor_id
		where a.assessment_id=".$ass_id." and a.status='A' ";
		$role=UlsMenu::callpdo($query);
		return $role;		
	} */
	
	static function get_assessment_assessor_final($id,$pos_id,$emp_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			echo $query="select a.*,c.rating_number from uls_assessment_report_final a
			inner join(SELECT `assessor_id` FROM `uls_assessment_position_assessor`) b on a.assessor_id=b.assessor_id
			left join(SELECT `scale_id`,`rating_id`,`rating_number`,`rating_name_scale` FROM `uls_rating_master_scale`) c on c.scale_id=a.scale_id
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id and a.position_id=$pos_id and a.employee_id=$emp_id ";
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
}