<?php

/**
 * UlsAssessmentCompetenciesWeightage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessmentCompetenciesWeightage extends BaseUlsAssessmentCompetenciesWeightage
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
		$this->created_by=$CI->session->userdata('username');
		$this->created_date=date('Y-m-d');
		$this->modified_by=$CI->session->userdata('username');        
		$this->modified_date=date('Y-m-d');
		$this->last_modified_by=$CI->session->userdata('user_id');
		 $this->parent_org_id=$CI->session->userdata('parent_org_id');
	}

	function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
		$this->modified_date=date('Y-m-d');
		$this->modified_by=$CI->session->userdata('username');
		$this->last_modified_by=$CI->session->userdata('user_id');
	}
	
	static function getassessmentcompetencies_weightage($id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select e.value_name as assesstype, a.* from uls_assessment_competencies_weightage a
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)e ON e.master_code = 'ASSESS_METHOD' AND e.value_code=a.assessment_type
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=".$id." and a.position_id=".$pos_id." order by a.assessment_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function getassessmentcompetencies_weightage_test($id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select e.value_name as assesstype, a.*,f.assess_test_id from uls_assessment_competencies_weightage a
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)e ON e.master_code = 'ASSESS_METHOD' AND e.value_code=a.assessment_type
			LEFT JOIN (SELECT assess_test_id, position_id, assessment_id,assessment_type FROM uls_assessment_test GROUP BY assess_test_id)f ON f.position_id=a.position_id and a.assessment_type=f.assessment_type and f.assessment_id=a.assessment_id
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id and a.position_id=$pos_id order by a.assessment_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	
}