<?php

/**
 * UlsAssessmentFeedbackAssessor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessmentFeedbackAssessor extends BaseUlsAssessmentFeedbackAssessor
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
	static function view_feedback_assessor($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.* from uls_assessment_feedback_assessor a
			where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessor_id=".$_SESSION['asr_id']." and a.assessment_id=$id";
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	static function view_assessor_feedback(){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		$query="select b.`assessor_id`,b.`assessor_name`,a.* from uls_assessment_feedback_assessor a
		left join(SELECT `assessor_id`,`assessor_name` FROM `uls_assessor_master`) b on b.assessor_id=a.assessor_id
		where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id');
		$compdef=UlsMenu::callpdo($query);
		return $compdef;
	}
}