<?php

/**
 * UlsAssessmentTestFishbone
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsAssessmentTestFishbone extends BaseUlsAssessmentTestFishbone
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	static function getfishboneassessment($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select c.value_name,t.test_name,a.*,t.fishbone_id,i.fishbone_name from uls_assessment_test_fishbone a 
			left join (SELECT `test_id`,`test_name`,fishbone_id FROM `uls_competency_test`) t on t.test_id=a.test_id
			left join (SELECT `fishbone_name`,fishbone_id FROM `uls_fishbone_master`) i on i.fishbone_id=t.fishbone_id
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)c ON c.master_code = 'STATUS' AND c.value_code=a.status
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assess_test_id=$id order by a.fish_assess_test_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function viewfishbone_count_report($id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$pos_ids=!empty($pos_id)?" and a.position_id=".$pos_id."":"";
			$query="SELECT a.* FROM `uls_assessment_test_fishbone` a
			WHERE a.`assessment_id`=".$id." ".$pos_ids." and a.parent_org_id=".$CI->session->userdata('parent_org_id');
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
}