<?php

/**
 * UlsBeiResponsesAssessment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsBeiResponsesAssessment extends BaseUlsBeiResponsesAssessment
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	static function get_test_view_details_beh($ass_test_id,$ass_id,$instrument_id){ 
        $pdo = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $testde="SELECT d.`ins_subpara_id`,d.`ins_para_id`,d.`instrument_id`,d.`ins_subpara_text`,d.`ins_subpara_text_ext`,b.instrument_type,b.instrument_scale,a.assess_test_id,d.`subpara_left`,d.`subpara_right`,d.`ins_subpara_text_lang`,d.`ins_subpara_text_ext_lang` FROM `uls_assessment_test_behavorial_inst` a
		left join (SELECT `instrument_id`,`instrument_name`,`instrument_scale`,instrument_type FROM `uls_be_instruments`) b on a.instrument_id=b.instrument_id
		left join (SELECT `ins_para_id`,`instrument_id`,`ins_para_name` FROM `uls_be_ins_parameters`) c on b.instrument_id=c.instrument_id
		left join (SELECT `ins_subpara_id`,`ins_para_id`,`instrument_id`,`ins_subpara_text`,`ins_subpara_text_ext`,`subpara_left`,`subpara_right`,`ins_subpara_text_lang`,`ins_subpara_text_ext_lang` FROM `uls_be_ins_subparameters`) d on d.ins_para_id=c.ins_para_id
		where a.assess_test_id=".$ass_test_id." and a.assessment_id=".$ass_id." and a.instrument_id=".$instrument_id. " order by d.ins_subpara_id asc";
        $stmt = $pdo->prepare($testde);
        $stmt->execute();
        $org_values=$stmt->fetchAll();
        return $org_values;         
    }
}