<?php

/**
 * UlsCompetencyPositionRequirementsKra
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsCompetencyPositionRequirementsKra extends BaseUlsCompetencyPositionRequirementsKra
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
		$this->created_by=$CI->session->userdata('username');
		$this->created_date=date('Y-m-d');
		$this->modified_by=$CI->session->userdata('username');
		$this->modified_date=date('Y-m-d');
		$this->last_modified_id=$CI->session->userdata('user_id');
	}

	function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
		$this->modified_date=date('Y-m-d');
		$this->modified_by=$CI->session->userdata('username');
		$this->last_modified_id=$CI->session->userdata('user_id');
	}

	/* static function get_comp_kra($id){
		$compname_valview_id=Doctrine_Query::create()->from('UlsCompetencyPositionRequirementsKra')->where("comp_position_req_id=".$id)->execute();
		return $compname_valview_id;
	} */

	static function getcompetencypositionrequirementskra($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		//left join (select comp_position_req_id,comp_position_level_id,comp_position_level_scale_id from uls_competency_position_requirements group by comp_position_req_id)f on f.comp_position_req_id=a.comp_position_req_idleft join (select level_id,level_name from uls_level_master group by level_id)c on c.level_id=f.comp_position_level_id left join (select scale_id,scale_name from uls_level_master_scale group by scale_id)d on d.scale_id=f.comp_position_level_scale_id
		if(!empty($id) && is_numeric($id)){
			$query="select b.kra_master_name as kra_master_name,a.* from uls_competency_position_requirements_kra a
			left join (select kra_master_id,kra_master_name from uls_kra_masters group by kra_master_id)b 
			on b.kra_master_id=a.comp_kra_steps 
			where 1 and a.comp_position_id=$id order by b.kra_master_name asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function getcompetencyposition_requirementskra($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$result=array();
		if(!empty($id) && is_numeric($id)){
			
			$query="SELECT c.`kra_master_id`,c.kra_master_name,a.* FROM `uls_competency_position_requirements` a 
			left join (SELECT `kra_master_id`,`comp_def_id`,`status` FROM `uls_kra_master_competency` where status='A') b on (a.comp_position_competency_id=b.comp_def_id)
			left join (SELECT `kra_master_id`,`kra_master_name`,`kra_status`,kra_comp_count FROM `uls_kra_masters` where kra_status='A') c on (b.kra_master_id=c.kra_master_id) 
			WHERE a.`comp_position_id`=".$id."  group by(c.kra_master_id) order by kra_master_name asc ";
			$compdef_included=UlsMenu::callpdo($query);
			foreach($compdef_included as $compdef_includeds){
				$result[]=$compdef_includeds;
			}
			
			$query="SELECT `kra_master_id`,`kra_master_name`,`kra_status`,kra_comp_count FROM `uls_kra_masters` where kra_status='A' and kra_comp_count=0 group by kra_master_id order by kra_master_name asc ";
			$compdef_nincluded=UlsMenu::callpdo($query);
			foreach($compdef_nincluded as $compdef_nincludeds){
				$result[]=$compdef_nincludeds;
			}
		}
		/* echo "<pre>";
		print_r($result); */
		return $result;
	}
	
	static function getcompetency_positionrequirementskra($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.* from uls_competency_position_requirements_kra a
			where 1 and a.comp_position_id=$id";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
}
