<?php

/**
 * UlsCompetencyDefLevelAssessment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsCompetencyDefLevelAssessment extends BaseUlsCompetencyDefLevelAssessment
{
	 function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_by=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
    }
	
	static function getcompdeflevelassessment($id,$scale=""){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$sq=!empty($scale)?" and comp_def_level_ind_id=".$scale:"";
			$query="select b.value_name as assess_method, a.* from uls_competency_def_level_assessment a 
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'ASSESS_METHOD' AND a.comp_def_assess_type = b.value_code
			where 1 and  parent_org_id=".$CI->session->userdata('parent_org_id')." $sq and comp_def_id=$id";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
}