<?php

/**
 * UlsCompetencyDefinition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsCompetencyDefinition extends BaseUlsCompetencyDefinition
{
	 function preInsert($event){
		 $CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_by=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
    }
	
	static function competencyattachedposition($comp_id){
		$results=UlsMenu::callpdo("SELECT `position_name` FROM `uls_position` WHERE `position_id` in (SELECT distinct(`comp_position_id`) FROM `uls_competency_position_requirements` WHERE `comp_position_competency_id`=$comp_id) order by position_name asc");
		echo "<ol>";
		foreach($results as $result){
			echo "<li>".$result['position_name']."</li>";
		}
		echo "</ol>";
	}
	
	static function searchcount($name="",$comp_type="",$cat_type="", $condition){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq=!empty($name)? !empty($sq)? " and comp_def_name like '%".$name."%'":" and comp_def_name like '%".$name."%'":"";
		$sq.=!empty($comp_type)? " and competency_type='$comp_type'":"";
		$sq.=!empty($cat_type)? " and comp_def_category='$cat_type'":"";
		$learning="select count(*) as num_count from uls_competency_definition where 1 and  parent_org_id=".$CI->session->userdata('parent_org_id')." and comp_structure='S'".$sq.$condition;
     	$eve=UlsMenu::callpdorow($learning);                
		return $eve['num_count'];
	}
    
    static function search($start,$limit,$name="",$comp_type="",$cat_type="",$condition){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq=!empty($name)? !empty($sq)? " and a.comp_def_name like '%".$name."%'":" and a.comp_def_name like '%".$name."%'":"";
		$sq.=!empty($comp_type)? " and a.competency_type='$comp_type'":"";
		$sq.=!empty($cat_type)? " and a.comp_def_category='$cat_type'":"";
		
		$learnings="select g.value_name as comp_type,f.positions,e.level_name as level,c.name as category,d.name as subcategory,h.name as addcategory,b.value_name as comp_status,q.ques_bank,qb.ques_bank_count,a.* from uls_competency_definition a
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'STATUS' AND a.comp_def_status = b.value_code
		LEFT JOIN (SELECT category_id, name FROM uls_category GROUP BY category_id)c ON a.comp_def_category = c.category_id 
		LEFT JOIN (SELECT category_id, name FROM uls_category GROUP BY category_id)d ON a.comp_def_sub_category = d.category_id
		LEFT JOIN (SELECT category_id, name FROM uls_category GROUP BY category_id)h ON a.comp_def_add_category = h.category_id
		LEFT JOIN (SELECT level_id, level_name FROM uls_level_master GROUP BY level_id)e ON a.comp_def_level = e.level_id
		LEFT JOIN (SELECT count(*) as positions,`comp_position_competency_id` FROM `uls_competency_position_requirements` WHERE 1 group by `comp_position_competency_id`)f  on a.comp_def_id=f.comp_position_competency_id
		LEFT JOIN (SELECT count(*) as ques_bank,`comp_def_id` FROM `uls_competency_def_que_bank` WHERE 1 group by `comp_def_id`)q  on a.comp_def_id=q.comp_def_id
		LEFT JOIN (SELECT count(*) as ques_bank_count,`comp_def_id` FROM `uls_questionbank` WHERE 1 group by `comp_def_id`)qb  on a.comp_def_id=qb.comp_def_id
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)g ON g.master_code = 'POSTYPE' AND a.competency_type = g.value_code 
		where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq $condition order by a.comp_structure DESC,a.comp_def_name asc  limit $limit offset $start";
		$result=UlsMenu::callpdo($learnings);
		return $result;
    }
	
	static function viewcompetency($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select e.level_name as level,c.name as category,d.name as subcategory,b.value_name as comp_status,a.* from uls_competency_definition a
			INNER JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'STATUS' AND a.comp_def_status = b.value_code
			LEFT JOIN (SELECT category_id, name FROM uls_category GROUP BY category_id)c ON a.comp_def_category = c.category_id 
			LEFT JOIN (SELECT category_id, name FROM uls_category GROUP BY category_id)d ON a.comp_def_sub_category = d.category_id
			LEFT JOIN (SELECT level_id, level_name FROM uls_level_master GROUP BY level_id)e ON a.comp_def_level = e.level_id
			where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.comp_def_id=$id";
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	static function competency_details($type=""){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq=!empty($type)?" and a.competency_type='$type'":"";
		$query="select a.comp_def_id,UPPER(a.comp_def_name) as comp_def_name, a.competency_type from uls_competency_definition a where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq order by a.comp_def_name asc";
		$compdef=UlsMenu::callpdo($query);		
		return $compdef;
	}
	
	
	
	static function competency_dashdetails($type="",$con=""){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq=!empty($type)?" and a.competency_type='$type'":"";
		$query="select a.comp_def_id,UPPER(a.comp_def_name) as comp_def_name, a.competency_type from uls_competency_definition a where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq $con order by a.comp_def_name asc";
		$compdef=UlsMenu::callpdo($query);		
		return $compdef;
	}
	
	static function view_competency_scale($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.*,l.scale_name,l.scale_number,l.scale_desc from uls_competency_definition a
			LEFT JOIN (SELECT level_id, level_name FROM uls_level_master GROUP BY level_id)e ON a.comp_def_level = e.level_id
			LEFT JOIN(SELECT `scale_id`,`scale_number`,`level_id`,`scale_name`, `description` as scale_desc FROM `uls_level_master_scale`)l on l.level_id=e.level_id
			where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.comp_def_id=$id order by l.scale_number ASC";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function competency_detail_single($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select a.comp_def_id,a.comp_def_name as comp_def_name, a.competency_type,a.comp_def_level,a.comp_def_name_alt from uls_competency_definition a where a.comp_def_id=".$id." and  a.parent_org_id=".$CI->session->userdata('parent_org_id');
		$compdef=UlsMenu::callpdorow($query);		
		return $compdef;
	}
	
	static function competencyattachedquestionbank($comp_id){
		$query="SELECT `name` FROM `uls_questionbank` WHERE `question_bank_id` in (SELECT distinct(`master_ques_bank_id`) FROM `uls_competency_def_que_bank` WHERE `comp_def_id`=$comp_id) order by name asc";
		$compdef=UlsMenu::callpdo($query);
		return $compdef;
	}
	
	static function competencyattachedquestion_bank($comp_id){
		$query="SELECT `name` FROM `uls_questionbank` WHERE  `comp_def_id`=$comp_id order by name asc";
		$compdef=UlsMenu::callpdo($query);
		return $compdef;
	}
}