<?php

/**
 * UlsCompetencyDefLevelMigrationMaps
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsCompetencyDefLevelMigrationMaps extends BaseUlsCompetencyDefLevelMigrationMaps
{
	 function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_by=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
    }
	
	static function getcompdeflevelmigmap($id,$scale_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.value_name as migrate_type,a.* from uls_competency_def_level_migration_maps a
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON find_in_set(b.value_code,a.comp_def_level_migrate_type)>0 AND b.master_code = 'MIGRATE_TYPE'
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.comp_def_level_ind_id=".$scale_id." and a.comp_def_id=$id";
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	static function getcompdeflevelmigmaps($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.value_name as migrate_type,a.* from uls_competency_def_level_migration_maps a
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON find_in_set(b.value_code,a.comp_def_level_migrate_type)>0 AND b.master_code = 'MIGRATE_TYPE'
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.comp_def_id=$id";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function getcompdeflevelmigmap_details($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.value_name as migrate_type,a.* from uls_competency_def_level_migration_maps a
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON find_in_set(b.value_code,a.comp_def_level_migrate_type)>0 AND b.master_code = 'MIGRATE_TYPE'
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.comp_def_level_migrate_id=$id";
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	
}