<?php

/**
 * UlsCompetencyMigrationContentMaster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsCompetencyMigrationContentMaster extends BaseUlsCompetencyMigrationContentMaster
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
		$this->created_by=$CI->session->userdata('username');
		$this->created_date=date('Y-m-d');
		$this->modified_by=$CI->session->userdata('username');        
		$this->modified_date=date('Y-m-d');
		$this->last_modified_by=$CI->session->userdata('user_id');
		 $this->parent_org_id=$CI->session->userdata('parent_org_id');
	}

	function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
		$this->modified_date=date('Y-m-d');
		$this->modified_by=$CI->session->userdata('username');
		$this->last_modified_by=$CI->session->userdata('user_id');
	}
	
	static function searchcount(){
		$CI =& get_instance();
		$CI->load->library('session');
		$learning="select count(*) as num_count from uls_competency_migration_content_master where 1 and  parent_org_id=".$CI->session->userdata('parent_org_id');
     	$eve=UlsMenu::callpdorow($learning);                
		return $eve['num_count'];
	}
	
	static function search($start,$limit){
		$CI =& get_instance();
		$CI->load->library('session');
		$learnings="select b.value_name as status_val,c.value_name as migrationtype, a.* from uls_competency_migration_content_master a
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'STATUS' AND a.status = b.value_code	
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)c ON c.master_code = 'MIGRATE_TYPE' AND a.migration_type = c.value_code 
		where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." limit $limit offset $start";
		$result=UlsMenu::callpdo($learnings);
		return $result;
    }
	
	static function get_migration_competencies($comp_id,$scale_id,$type){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($comp_id) && is_numeric($comp_id)){
			$query="select e.`migration_type`,e.`type`,e.`program_name`,e.`program_objective`,e.`program_link`,e.`status`,e.`course_id`, a.* from uls_competency_migration_content_program a
			LEFT JOIN (SELECT parent_org_id,`migration_type`,`type`,`program_name`,`program_objective`,`program_link`,`status`,`course_id` FROM `uls_competency_migration_content_master`) e ON e.course_id=a.course_id
			where 1 and e.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.comp_def_id=".$comp_id." and a.scale_id=".$scale_id." and e.migration_type='".$type."' order by a.comp_def_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function viewmigration($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$level=array();
		if(!empty($id) && is_numeric($id)){
			$query="SELECT a. * FROM uls_competency_migration_content_master a
			WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.course_id=$id";
			$level=UlsMenu::callpdorow($query);
		}
		return $level;
	}
	
	static function view_migration($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$level=array();
		if(!empty($id) && is_numeric($id)){
			$query="SELECT b.value_name as status_val,c.value_name as migrationtype, a.* FROM uls_competency_migration_content_master a
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'STATUS' AND a.status = b.value_code	
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)c ON c.master_code = 'MIGRATE_TYPE' AND a.migration_type = c.value_code
			WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.course_id=$id";
			$level=UlsMenu::callpdorow($query);
		}
		return $level;
	}
}