<?php

/**
 * UlsCompetencyTest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsCompetencyTest extends BaseUlsCompetencyTest
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
    
	public static function searchcount($test_name){
		$CI =& get_instance();
		$CI->load->library('session');
        $sq=!empty($test_name)? " and a.test_name like '%$test_name%'":"";
		$query="SELECT count(*) as numcount FROM uls_competency_test a
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'PUBLISH_STATUS' AND a.active_flag = b.value_code 
		LEFT JOIN (SELECT count(*) as questioncount, test_id FROM uls_competency_test_questions GROUP BY test_id)c ON c.test_id = a.test_id 
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq ";
		$testcount=UlsMenu::callpdorow($query);		
		return $testcount['numcount'];
    }
    
   
    public static function search($start, $limit,$test_name){
		$CI =& get_instance();
		$CI->load->library('session');
        $sq=!empty($test_name)? " and a.test_name like '%$test_name%'":"";
		$query="SELECT c.questioncount,b.value_name as publish_status, a. * FROM uls_competency_test a
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'PUBLISH_STATUS' AND a.active_flag = b.value_code 
		LEFT JOIN (SELECT count(*) as questioncount, test_id FROM uls_competency_test_questions GROUP BY test_id)c ON c.test_id = a.test_id 
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq limit $limit offset $start";
		$testdetails=UlsMenu::callpdo($query);
        return $testdetails;
    }  
	static function getquestionbanknames(){ 
		$CI =& get_instance();
		$CI->load->library('session');
		$qnames= Doctrine_Query::create()->select('question_bank_id as qid,name as qname')->from('UlsQuestionbank')->where("type='".$_REQUEST['test_type']."' and parent_org_id=".$CI->session->userdata('parent_org_id'))->execute();
		 return $qnames;
	}
	
	static function get_test_details($id){
		$CI =& get_instance();
		$CI->load->library('session');
        $test=Doctrine_Query::Create()->from('UlsCompetencyTest')->where('test_id='.$id." and parent_org_id=".$CI->session->userdata('parent_org_id'))->execute();
		return $test;
    }
	
	static function get_test_info($case){
		$CI =& get_instance();
		$CI->load->library('session');
        $test=Doctrine_Query::Create()->from('UlsCompetencyTest')->where("test_type_flag='".$case."' and parent_org_id=".$CI->session->userdata('parent_org_id'))->execute();
		return $test;
    }
	
	static function get_test_view_details($id){
		$query="SELECT b. * FROM `uls_competency_questions` b
        WHERE b.`question_id`
    		IN (
    
                    SELECT `question_id`
                    FROM `uls_competency_test_questions`
                    WHERE `test_id`
                    IN (
                    
                    SELECT `test_id`
                    FROM uls_competency_test
                    WHERE test_id =".$id."
                )
		);";
	   return  UlsMenu::callpdo($query);
      
    }
	
	static function get_test_detail(){
		$CI =& get_instance();
		$CI->load->library('session');
        $test=Doctrine_Query::Create()->from('UlsCompetencyTest')->where('parent_org_id='.$CI->session->userdata('parent_org_id'))->execute();
		return $test;
    }
	
	static function get_test_view_details_count($id){
		$query="SELECT b. * FROM `uls_competency_questions` b
        WHERE b.`question_id`
    		IN (
    
                    SELECT `question_id`
                    FROM `uls_competency_test_questions`
                    WHERE `test_id`
                    IN (
                    
                    SELECT `test_id`
                    FROM uls_competency_test
                    WHERE test_id =".$id."
                )
		);";
	   return  UlsMenu::callpdo($query);
      
    }
	
	public static function test_count($id){
		$query="SELECT c.questioncount, a.comp_assess_id FROM uls_competency_assessment a
		LEFT JOIN(SELECT comp_test_id,comp_assess_id FROM uls_competency_assessment_test) d on a.comp_assess_id=d.comp_assess_id
		LEFT JOIN (SELECT count(*) as questioncount,comp_test_id FROM uls_competency_assessment_test_questions GROUP BY 	comp_test_id)c ON c.comp_test_id = d.comp_test_id 
		WHERE a.comp_assess_id=".$id;
		$testdetails=UlsMenu::callpdorow($query);
        return $testdetails;
    }  
	
	static function get_test_details1($id){
		$CI =& get_instance();
		$CI->load->library('session');
        $test=Doctrine_Query::Create()->from('UlsCompetencyTest')->where('test_id='.$id." and parent_org_id=".$CI->session->userdata('parent_org_id'))->fetchOne();
		return $test;
    }
	
	
	
	static function get_test_detail_name($id){
		$CI =& get_instance();
		$CI->load->library('session');
        $test=Doctrine_Query::Create()->from('UlsCompetencyTest')->where("test_name='".$id."' and parent_org_id=".$CI->session->userdata('parent_org_id'))->fetchOne();
		return $test;
    }
	
	public static function test_count_assessment($id,$pos_id,$ass_type){
		$query="SELECT c.questioncount,a.* FROM uls_competency_test a
		LEFT JOIN (SELECT count(*) as questioncount,test_id FROM uls_competency_test_questions GROUP BY test_id)c ON c.test_id = a.test_id 
		WHERE a.assessment_id=".$id." and a.position_id=".$pos_id." and a.test_type_flag='".$ass_type."'";
		$testdetails=UlsMenu::callpdorow($query);
        return $testdetails;
    } 
	
	public static function test_count_assessment_int($id,$pos_id,$ass_type,$test=""){
		$test=!empty($test)?"and a.test_id=".$test."":"";
		$query="SELECT c.questioncount,a.* FROM uls_competency_test a
		LEFT JOIN (SELECT count(*) as questioncount,test_id FROM uls_competency_test_questions GROUP BY test_id)c ON c.test_id = a.test_id 
		WHERE a.assessment_id=".$id." and a.position_id=".$pos_id." and a.test_type_flag='".$ass_type."' ".$test."";
		$testdetails=UlsMenu::callpdorow($query);
        return $testdetails;
    }

	public static function test_count_assessment_inbasket($id,$pos_id,$ass_type){
		$query="SELECT c.questioncount,a.* FROM uls_competency_test a
		LEFT JOIN (SELECT count(*) as questioncount,test_id FROM uls_competency_test_questions GROUP BY test_id)c ON c.test_id = a.test_id
		WHERE a.assessment_id=".$id." and a.position_id=".$pos_id." and a.test_type_flag='".$ass_type."'";
		$testdetails=UlsMenu::callpdo($query);
        return $testdetails;
    } 	
}