<?php

/**
 * UlsCompetencyDefLevelInterviewQuestions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsCompetencyDefLevelInterviewQuestions extends BaseUlsCompetencyDefLevelInterviewQuestions
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	static function get_interview_questions($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.*,b.value_name from uls_competency_def_level_interview_questions a
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'COMP_INT_QUESTION' AND a.comp_qtype = b.value_code
			where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.comp_int_id=".$id;
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function get_interview_question_type($id,$type){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.*,b.value_name from uls_competency_def_level_interview_questions a
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'COMP_INT_QUESTION' AND a.comp_qtype = b.value_code
			where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.comp_qtype='".$type."' and a.comp_int_id=".$id;
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function get_interview_question_type_assessor($id,$type,$ass_id,$pos_id,$emp_id,$assr_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.*,b.value_name,i.interview_comments from uls_competency_def_level_interview_questions a
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'COMP_INT_QUESTION' AND a.comp_qtype = b.value_code
			left join(SELECT `report_id`,`assessment_id`,`position_id`,`employee_id`,`assessor_id`,`competency_id`,`comp_int_qid`,`interview_comments`,`require_scale_id` FROM `uls_assessment_report_bytype_interview` where `assessment_id`=".$ass_id." and `position_id`=".$pos_id." and `employee_id`=".$emp_id." and `assessor_id`=".$assr_id.") i on i.comp_int_qid=a.comp_int_qid and i.competency_id=a.comp_def_id and i.require_scale_id=a.scale_id
			where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.comp_qtype='".$type."' and a.comp_int_id=".$id."";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function get_interview_question_type_assessor_regenate($id,$type){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.*,b.value_name,i.interview_comments from uls_competency_def_level_interview_questions a
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'COMP_INT_QUESTION' AND a.comp_qtype = b.value_code
			left join(SELECT `report_id`,`assessment_id`,`position_id`,`employee_id`,`assessor_id`,`competency_id`,`comp_int_qid`,`interview_comments`,`require_scale_id` FROM `uls_assessment_report_bytype_interview`) i on i.comp_int_qid=a.comp_int_qid and i.competency_id=a.comp_def_id and i.require_scale_id=a.scale_id
			where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.comp_qtype='".$type."' and a.comp_int_id=".$id."";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function get_interview_question_type_assessor_insert($id,$type,$ass_id,$pos_id,$emp_id,$assr_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			
			$query="select a.*,i.`comp_question_name`,i.`comp_question_answer`,i.comp_qtype from uls_assessment_report_bytype_interview a
			left join(SELECT `comp_int_qid`,`comp_question_name`,`comp_question_answer`,comp_int_id,comp_qtype FROM `uls_competency_def_level_interview_questions`) i on i.comp_int_qid=a.comp_int_qid
			where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.`assessment_id`=".$ass_id." and a.`position_id`=".$pos_id." and a.`employee_id`=".$emp_id." and a.`assessor_id`=".$assr_id."  and i.comp_qtype='".$type."' and i.comp_int_id=".$id;
			
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function get_interview_question_details($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.* from uls_competency_def_level_interview_questions a
			where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.comp_int_qid=".$id;
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	
}