<?php

/**
 * UlsCompetencyDefLevelElements
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsCompetencyDefLevelElements extends BaseUlsCompetencyDefLevelElements
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	static function get_element_details($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.* from uls_competency_def_level_elements a
			where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.element_id=".$id;
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	static function getcompdeflevelelement_details($id,$scale_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.*,d.scale_name from uls_competency_def_level_elements a
			left join (select scale_id,scale_name from uls_level_master_scale group by scale_id)d on d.scale_id=a.scale_id
			where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.comp_def_id=".$id." and 	a.scale_id=".$scale_id;
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
}