<?php

/**
 * UlsCompetencyDefIntQuestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsCompetencyDefIntQuestion extends BaseUlsCompetencyDefIntQuestion
{
	 function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_by=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
    }
	
	static function getcompdefintques($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			
			$query="select b.name,a.* from uls_competency_def_int_question a
			left join (select question_bank_id,name from uls_questionbank group by question_bank_id)b on b.question_bank_id=a.master_int_ques_bank_id 
			where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.comp_def_id=$id";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function getcompdefintques_view($id,$scale_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$sql=(!empty($scale_id))?" and c.scale_id=$scale_id":"";
			$query="select c.question_name,a.* from uls_competency_def_int_question a
			left join (select question_bank_id,name from uls_questionbank group by question_bank_id)b on b.question_bank_id=a.master_int_ques_bank_id 
			left join (SELECT `question_id`,`question_bank_id`,`question_name`,scale_id FROM `uls_questions`) c on c.question_bank_id=b.question_bank_id
			where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.comp_def_id=$id $sql";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function getcompdefinterview_levels($id,$scale,$level){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="SELECT d.name,e.question_id,e.level_id,e.scale_id,c.scale_name,e.question_name FROM `uls_competency_def_int_question` a
			left join (SELECT `comp_def_id`,`comp_def_name`,`comp_def_level` FROM `uls_competency_definition`) b on a.comp_def_id=b.comp_def_id 
			left join (SELECT `scale_id`,`scale_name`,`level_id` FROM `uls_level_master_scale`) c on c.level_id=b.comp_def_level
			left join (SELECT `question_bank_id`,`comp_def_id`,`name` FROM `uls_questionbank`) d on d.question_bank_id=a.master_int_ques_bank_id and d.comp_def_id=a.comp_def_id  
			inner join (SELECT `question_id`,`question_bank_id`,`level_id`,`scale_id`,question_name FROM `uls_questions`) e on e.question_bank_id=d.question_bank_id and e.level_id=c.level_id and e.scale_id=c.scale_id
			where a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.comp_def_id=".$id." and c.scale_id=".$scale." and b.comp_def_level=".$level."";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function getcompdefinterview_ass($id,$code){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.name as qbank_name,a.*,b.question_bank_id,b.comp_def_id from uls_competency_def_int_question a
			left join (select question_bank_id,name,type,comp_def_id from uls_questionbank group by question_bank_id)b on b.question_bank_id=a.master_int_ques_bank_id 
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.comp_def_id=".$id." and b.type='".$code."'";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
}