<?php

/**
 * UlsCompetencyTestQuestions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsCompetencyTestQuestions extends BaseUlsCompetencyTestQuestions
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	static function get_testquestions($id){ 
	    if(isset($id)){
		$pdo = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
		$emp_data="select  a.question_id as qid,a.question_name as qname,a.points as points,b.type_name as qtype,f.scale_name,e.comp_def_name  FROM  uls_questions a, uls_questions_type b,uls_competency_test_questions c,uls_level_master d,uls_competency_definition e,uls_level_master_scale f where( a.question_id=c.question_id and a.question_type=b.type_flag and a.level_id=d.level_id and c.competency_id=e.comp_def_id and d.level_id=f.level_id and c.test_id in (".$id.") )";
		$stmt = $pdo->prepare($emp_data);
		$stmt->execute();
		$org_values=$stmt->fetchAll();       
		return $org_values; 
        }		
	}
	
	public static function get_test_question_ids($test_id,$comp_def_id,$question_ids){
		$testdetails=array();
		if(!empty($test_id) && is_numeric($test_id)){
			$query="SELECT a.*,c.question_name FROM uls_competency_test_questions a
			left join (select question_id,question_name,level_id,question_type,scale_id from uls_questions) c on a.question_id=c.question_id
			WHERE a.test_id=".$test_id." and a.competency_id=".$comp_def_id." and a.`question_id` not in (".$question_ids.")";
			$testdetails=UlsMenu::callpdo($query);
		}
		return $testdetails;
    }
	
	
}