<?php

/**
 * UlsCompetencyLevelIndicatorMaster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsCompetencyLevelIndicatorMaster extends BaseUlsCompetencyLevelIndicatorMaster
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_by=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
    }
	
	static function searchcount($ind_name=""){
		$CI =& get_instance();
		$CI->load->library('session');
        $sq=!empty($ind_name)? " and ind_master_name like '%$ind_name%'":"";
        $locations= Doctrine_Query::create()->select("count(*) as numcount")->from("UlsCompetencyLevelIndicatorMaster")->where("1 and parent_org_id=".$CI->session->userdata('parent_org_id')." ". $sq)->setHydrationMode(Doctrine::HYDRATE_ARRAY)->fetchOne();
        return $locations['numcount'];
    }
	
	static function search($start, $limit,$ind_name=""){
		$CI =& get_instance();
		$CI->load->library('session');
        $sq=!empty($ind_name)? " and ind_master_name like '%$ind_name%'":"";
		$query="SELECT d.value_name, c.comp_def_name, a. * FROM uls_competency_level_indicator_master a
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)d ON d.master_code = 'STATUS' AND a.status = d.value_code
		LEFT JOIN (SELECT comp_def_id, comp_def_name from uls_competency_definition group by comp_def_id)c on c.comp_def_id=a.comp_def_id
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq limit $limit offset $start";
		$locations=UlsMenu::callpdo($query);
		/*echo "<pre>";
		print_r($locations);*/
        return $locations;
    }
	
	static function indicator_master(){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		$query="select * from uls_competency_level_indicator_master where 1 and  parent_org_id=".$CI->session->userdata('parent_org_id')." order by ind_master_name Asc";
		$compdef=UlsMenu::callpdo($query);
		return $compdef;
	}
	
	static function indicator_master_new($comp_def_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		$query="select * from uls_competency_level_indicator_master where 1 and comp_def_id='".$comp_def_id."' and parent_org_id=".$CI->session->userdata('parent_org_id')." order by ind_master_name Asc";
		$compdef=UlsMenu::callpdo($query);
		return $compdef;
	}
	
	static function indicator_master_view($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT d.value_name, a. * FROM uls_competency_level_indicator_master a
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)d ON master_code = 'STATUS' AND a.status = d.value_code
		WHERE a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.ind_master_id=".$id;
		$locations=UlsMenu::callpdorow($query);
        return $locations;
    }
}