<?php

/**
 * UlsEmpStagingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsEmpStagingTable extends BaseUlsEmpStagingTable
{
  static function getEmpStageDetails($emp_ids){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT a.* from uls_emp_staging_table a where a.employee_id=".$emp_ids;
		return UlsMenu::callpdo($query);
	}
}