<?php

/**
 * UlsEmployeeCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsEmployeeCategory extends BaseUlsEmployeeCategory
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }

    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
    static function searchcount($emp_cat_name=""){
		$CI =& get_instance();
		$CI->load->library('session');
        $sq=!empty($emp_cat_name)? " and emp_cat_name like '%$emp_cat_name%'":"";
        $locations= Doctrine_Query::create()->select("count(*) as numcount")->from("UlsEmployeeCategory")->where("1 and parent_org_id=".$CI->session->userdata('parent_org_id')." ". $sq)->setHydrationMode(Doctrine::HYDRATE_ARRAY)->fetchOne();
        return $locations['numcount'];
    }
    
    static function search($start, $limit,$emp_cat_name=""){
		$CI =& get_instance();
		$CI->load->library('session');
        $sq=!empty($emp_cat_name)? " and emp_cat_name like '%$emp_cat_name%'":"";
		$query="SELECT d.value_name, a. * FROM uls_employee_category a
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)d ON master_code = 'STATUS' AND a.emp_cat_status = d.value_code
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq limit $limit offset $start";
		$locations=UlsMenu::callpdo($query);
        return $locations;
    }
	
	static function viewempcategory($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT b.value_name as val_status, a. * FROM uls_employee_category a 
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'STATUS' AND a.emp_cat_status = b.value_code 
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.emp_cat_id=$id";
		$grade=UlsMenu::callpdorow($query);
		return $grade;		
	}
	
	public static function getempcategory(){
		$CI =& get_instance();
		$CI->load->library('session');
		$parent_org_id=$CI->session->userdata('parent_org_id');
		if(!empty($parent_org_id)){
			$sub="select a.* from uls_employee_category a where a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.emp_cat_status='A'";
			return UlsMenu::callpdo($sub);
		}
	}
}