<?php

/**
 * UlsFishboneListProbable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsFishboneListProbable extends BaseUlsFishboneListProbable
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_by=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
    }
	
	static function getfishbonecause($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select c.value_name as headlist,a.* from uls_fishbone_list_probable a
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)c ON c.master_code = 'FISH_LIST' AND a.head_list = c.value_code
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.fishbone_quest_id=$id";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function get_fishbone_cause($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.* from uls_fishbone_list_probable a
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.fishbone_list_id=$id";
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
}