<?php

/**
 * UlsFeedbackEmployeeRating
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsFeedbackEmployeeRating extends BaseUlsFeedbackEmployeeRating
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	public static function get_rating_status($ass_test_id,$seeker_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$emp_dat="SELECT * FROM `uls_feedback_employee_rating` WHERE `giver_id`=".$_SESSION['emp_id']." and employee_id=".$seeker_id." and `ass_test_id`=".$ass_test_id;
		return UlsMenu::callpdorow($emp_dat);
	}
	
	public static function giver_rating_status($group_id,$giver_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$emp_dat="SELECT * FROM `uls_feedback_employee_rating` WHERE `giver_id`=".$giver_id." and `group_id`=".$group_id." and status is not NULL";
		return UlsMenu::callpdorow($emp_dat);
	}
	
	public static function giver_rating_notstarted($group_id,$giver_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$emp_dat="SELECT * FROM `uls_feedback_employee_rating` WHERE `giver_id`=".$giver_id." and `group_id`=".$group_id." and status is NULL";
		return UlsMenu::callpdorow($emp_dat);
	}
	
	public static function giver_rating_status_completed($group_id,$giver_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$emp_dat="SELECT * FROM `uls_feedback_employee_rating` WHERE `giver_id`=".$giver_id." and `group_id`=".$group_id." and status='C' and status is not NULL";
		return UlsMenu::callpdorow($emp_dat);
	}
	
	public static function giver_rating_status_inprocess($group_id,$giver_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$emp_dat="SELECT * FROM `uls_feedback_employee_rating` WHERE `giver_id`=".$giver_id." and `group_id`=".$group_id." and status='W' and status is not NULL";
		return UlsMenu::callpdorow($emp_dat);
	}
	
	static function get_assessment_feedback_employees_count($emp_id,$id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select count(b.employee_id) as count_emp from uls_assessment_employees a
			left join (SELECT `feed_id`,`employee_id`,`assessment_id` FROM `uls_feedback_employee_rating`)b on a.employee_id=b.employee_id and a.assessment_id=b.assessment_id	where a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.employee_id=".$emp_id." and a.position_id=".$pos_id." and a.assessment_id=".$id;
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	public static function seeker_status($group_id,$seeker_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$emp_dat="SELECT * FROM `uls_feedback_employee_rating` WHERE `giver_id`=".$seeker_id." and employee_id=".$seeker_id." and `group_id`=".$group_id;
		return UlsMenu::callpdorow($emp_dat);
	}
	
	public static function giver_status($group_id,$giver_id,$seeker_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$emp_dat="SELECT * FROM `uls_feedback_employee_rating` WHERE `giver_id`=".$giver_id." and employee_id=".$seeker_id." and `group_id`=".$group_id;
		return UlsMenu::callpdorow($emp_dat);
	}
	
	public static function users_opt_dashboard($group_id,$giver_id,$seeker_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$emp_dat="SELECT distinct(status) as st,giver_id as gv FROM `uls_feedback_employee_rating` WHERE `giver_id`=".$giver_id." and employee_id=".$seeker_id." and status='C' and `group_id`=".$group_id;
		return UlsMenu::callpdo($emp_dat);
	}
	
	public static function users_optw_dashboard($group_id,$giver_id,$seeker_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$emp_dat="SELECT distinct(status) as st,giver_id as gv FROM `uls_feedback_employee_rating` WHERE `giver_id`=".$giver_id." and employee_id=".$seeker_id." and status='W' and `group_id`=".$group_id;
		return UlsMenu::callpdo($emp_dat);
	}
	
	public static function giver_dashboard($group_id,$giver_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$emp_dat="SELECT count(distinct(giver_id)) as count_nn FROM `uls_feedback_employee_rating` WHERE `giver_id` in (".$giver_id.") and status='C' and `group_id`=".$group_id;
		return UlsMenu::callpdo($emp_dat);
	}
	
	public static function inprocess_users_dash($group_id,$giver_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$emp_dat="SELECT distinct(giver_id) FROM `uls_feedback_employee_rating` WHERE `giver_id` in (".$giver_id.") and status='W' and `group_id`=".$group_id;
		return UlsMenu::callpdo($emp_dat);
	}
	
	public static function inprocess_users_dash_new($group_id,$giver_id){
		$CI =& get_instance();
		$CI->load->library('session');
		echo $emp_dat="SELECT distinct(giver_id) as count FROM `uls_feedback_employee_rating` WHERE `giver_id` in (".$giver_id.") and status='W' and `group_id`=".$group_id;
		return UlsMenu::callpdorow($emp_dat);
	}
	
	public static function getselffeedbackasscomp($emp,$comp,$ass_id){
		$emp_dat="SELECT count(*),avg(`rater_value`) as val,`employee_id`,`element_competency_id` FROM `uls_feedback_employee_rating` WHERE `assessment_id`='$ass_id' and `employee_id`='$emp' and `giver_id`='$emp' and `element_competency_id`='$comp' group by `element_competency_id`";
		return UlsMenu::callpdorow($emp_dat);
	}
	
	public static function getothersfeedbackasscomp($emp,$comp,$ass_id){
		$emp_dat="SELECT count(*),avg(`rater_value`) as val,`employee_id`,`element_competency_id` FROM `uls_feedback_employee_rating` WHERE `assessment_id`='$ass_id' and `employee_id`='$emp' and `giver_id`!='$emp' and `rater_value`!=0 and `rater_value` is not null and `element_competency_id`='$comp' group by `element_competency_id`";
		return UlsMenu::callpdorow($emp_dat);
	}
	
	public static function getselffeedbackasscompelement($emp,$comp,$ass_id){
		$emp_dat="SELECT count(*),avg(a.`rater_value`) as val,a.`employee_id`,a.element_competency_id,a.ques_element_id,b.element_id_edit,c.comp_def_name FROM `uls_feedback_employee_rating` a left join uls_questionnaire_competency_element b on a.ques_element_id=b.ques_element_id left join uls_competency_definition c on a.element_competency_id=c.comp_def_id WHERE a.`assessment_id`='$ass_id' and a.`employee_id`='$emp' and a.`giver_id`='$emp' and a.`element_competency_id`='$comp'  group by a.`ques_element_id` ORDER BY `b`.`element_id_edit` ASC";
		return UlsMenu::callpdo($emp_dat);
	}
	
	public static function getothersfeedbackasscompelement($emp,$comp,$ass_id){
		$emp_dat="SELECT count(*),avg(a.`rater_value`) as val,a.`employee_id`,a.element_competency_id,a.ques_element_id,b.element_id_edit,c.comp_def_name FROM `uls_feedback_employee_rating` a left join uls_questionnaire_competency_element b on a.ques_element_id=b.ques_element_id left join uls_competency_definition c on a.element_competency_id=c.comp_def_id WHERE a.`assessment_id`='$ass_id' and a.`employee_id`='$emp' and a.`giver_id`!='$emp' and a.`element_competency_id`='$comp' and a.`rater_value`!=0 and a.`rater_value` is not null group by a.`ques_element_id` ORDER BY `b`.`element_id_edit` ASC";
		return UlsMenu::callpdo($emp_dat);
	}
	
	public static function seeker_status_data($ass_id,$group_id,$seeker_id,$ass_test_id,$ques_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$emp_dat="SELECT * FROM `uls_feedback_employee_rating` WHERE `assessment_id`=".$ass_id." and `giver_id`=".$seeker_id." and employee_id=".$seeker_id." and `group_id`=".$group_id." and ass_test_id=".$ass_test_id." and ques_id=".$ques_id;
		return UlsMenu::callpdorow($emp_dat);
	}
	
	public static function giver_rating_status_new($ass_id,$group_id,$giver_id,$ass_test_id,$ques_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$emp_dat="SELECT * FROM `uls_feedback_employee_rating` WHERE `assessment_id`=".$ass_id." and `giver_id`=".$giver_id." and `group_id`=".$group_id."  and ass_test_id=".$ass_test_id." and ques_id=".$ques_id;
		return UlsMenu::callpdorow($emp_dat);
	}
	
	public static function report_users($group_id,$seeker_id,$fid,$qid){
		$CI =& get_instance();
		$CI->load->library('session');
		$emp_dat="SELECT avg(a.rater_value) as avge, a.element_competency_id, a.element_level_scale_id,a.ques_element_id FROM `uls_feedback_employee_rating` a
		WHERE a.`giver_id`=".$seeker_id." and a.employee_id=".$seeker_id." and a.`group_id`=".$group_id." and a.assessment_id=".$fid." and a.ques_id=".$qid." and a.rater_value<>0 group by a.element_competency_id order by a.element_competency_id";
		return UlsMenu::callpdo($emp_dat);
	}
	
	public static function report_users_dashboard($group_id,$seeker_id,$fid,$qid){
		$CI =& get_instance();
		$CI->load->library('session');
		$emp_dat="SELECT avg(a.rater_value) as avge, a.element_competency_id, a.element_level_scale_id,a.ques_element_id,c.comp_def_name FROM `uls_feedback_employee_rating` a
		left join(SELECT `ques_element_id`,`ques_id`,`element_competency_id` FROM `uls_questionnaire_competency_element`) q on q.element_competency_id=a.element_competency_id and q.ques_element_id=a.ques_element_id and q.ques_id=a.ques_id
		left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) c on c.comp_def_id=a.element_competency_id
		WHERE a.`giver_id`<>".$seeker_id." and a.employee_id=".$seeker_id." and a.`group_id`=".$group_id." and a.assessment_id=".$fid." and a.ques_id=".$qid." and a.rater_value<>0 group by a.element_competency_id order by a.element_competency_id";
		return UlsMenu::callpdo($emp_dat);
	}
}