<?php

/**
 * UlsFishboneMaster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsFishboneMaster extends BaseUlsFishboneMaster
{
	function preInsert($event){
		 $CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_by=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
    }
	
	static function searchcount($name=""){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq=!empty($name)? !empty($sq)? " and fishbone_name like '%".$name."%'":" and fishbone_name like '%".$name."%'":"";
		$learning="select count(*) as num_count from uls_fishbone_master where 1 and  parent_org_id=".$CI->session->userdata('parent_org_id').$sq;
     	$eve=UlsMenu::callpdorow($learning);                
		return $eve['num_count'];
	}
    
    static function search($start,$limit,$name=""){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq=!empty($name)? !empty($sq)? " and a.fishbone_name like '%".$name."%'":" and a.fishbone_name like '%".$name."%'":"";
		$learnings="select c.value_name as fishstatus,a.* from uls_fishbone_master a
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)c ON c.master_code = 'STATUS' AND a.fishbone_status = c.value_code
		where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq limit $limit offset $start";
		$result=UlsMenu::callpdo($learnings);
		return $result;
    }
	
	static function viewfishbone($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select c.value_name as fishstatus,a.* from uls_fishbone_master a 
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)c ON c.master_code = 'STATUS' AND a.fishbone_status = c.value_code
			where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.fishbone_id=$id";
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	static function viewfishbone_ass($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="SELECT b.`fishbone_quest_id`,b.`fishbone_id`,c.fishbone_name FROM `uls_assessment_competencies` a 
			left join(SELECT `fishbone_quest_id`,`fishbone_id`,`comp_def_id`,`scale_id` FROM `uls_fishbone_comp_map`) b on a.assessment_pos_com_id=b.comp_def_id and a.assessment_pos_level_scale_id=b.scale_id
			left join(SELECT `fishbone_id`,`fishbone_name` FROM `uls_fishbone_master`) c on c.fishbone_id=b.fishbone_id
			WHERE a.`assessment_id`=".$id." and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." and c.fishbone_id is not NULL group by b.`fishbone_id`";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function viewfishbone_ass_question($id,$casestudy_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="SELECT b.`fishbone_quest_id`,b.`fishbone_id`,b.`comp_def_id`,b.`scale_id` FROM `uls_assessment_competencies` a 
			left join(SELECT `fishbone_quest_id`,`fishbone_id`,`comp_def_id`,`scale_id` FROM `uls_fishbone_comp_map`) b on a.assessment_pos_com_id=b.comp_def_id and a.assessment_pos_level_scale_id=b.scale_id
			WHERE a.`assessment_id`=".$id." and fishbone_id=$casestudy_id and a.parent_org_id=".$CI->session->userdata('parent_org_id')." group by b.fishbone_quest_id";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
}