<?php

/**
 * UlsHeirarchyMaster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsHeirarchyMaster extends BaseUlsHeirarchyMaster
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
		$this->created_by=$CI->session->userdata('username');
		$this->created_date=date('Y-m-d');
		$this->parent_org_id=$CI->session->userdata('parent_org_id'); 
		$this->modified_by=$CI->session->userdata('username');        
		$this->modified_date=date('Y-m-d');
		$this->last_modified_id=$CI->session->userdata('user_id');
	}
		
	function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
		$this->modified_date=date('Y-m-d');
		$this->modified_by=$CI->session->userdata('username');
		$this->last_modified_id=$CI->session->userdata('user_id');
	}
		
	public static function searchcount($hierarchy){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq=!empty($hierarchy)? " and a.hierarchy_name like '%$hierarchy%'":"";
		$masterlist= Doctrine_Query::create()->select("count(*) as numcount")->from("UlsHeirarchyMaster a")->where("1  and parent_org_id=".$CI->session->userdata('parent_org_id')." ".$sq)->fetchOne();
		return $masterlist['numcount'];
	}
    
	public static function search($hierarchy,$start, $limit){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq=!empty($hierarchy)? " and a.hierarchy_name like '%$hierarchy%'":"";
		$masterlist=Doctrine_Query::Create()->from('UlsHeirarchyMaster a')->where("1 and parent_org_id=".$CI->session->userdata('parent_org_id')." ".$sq)->limit($limit)->offset($start)->execute();
		return $masterlist;
	}
	//function to get all hierarchy names based on parent org id
	static function hierarchynames($orgid){
		if(!empty($orgid)){
			$hier_names="select hierarchy_id, hierarchy_name from uls_heirarchy_master where parent_org_id=".$orgid;
			return UlsMenu::callpdo($hier_names);
		}
	} 
}