<?php

/**
 * UlsLangQuestionValues
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsLangQuestionValues extends BaseUlsLangQuestionValues
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
	    $this->parent_org_id=$CI->session->userdata('parent_org_id'); 
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
    function preUpdate($event){
	    $CI =& get_instance();
		$CI->load->library('session'); 
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	static function get_all_lang_values($id){
		$query="select  a.*,b.lang_name as language_name  FROM uls_lang_question_values a, uls_language_master b where( a.lang_id=b.lang_id and a.value_id=".$id.")";
        return UlsMenu::callpdo($query);
        
    }
	
	static function get_all_lang_values_single($id,$lang){
		$query="select  a.*,b.lang_name as language_name  FROM uls_lang_question_values a, uls_language_master b where( a.lang_id=b.lang_id and a.value_id=".$id." and a.lang_id=".$lang.")";
        return UlsMenu::callpdorow($query);
        
    }
	
	static function get_all_lang_details($id){
		$query="select  a.* FROM uls_lang_question_values a where(a.comp_lang_id=".$id.")";
        return UlsMenu::callpdo($query);
    }
	
	static function get_questionlang_name($id){
		$group=Doctrine_Query::Create()->from('UlsLangQuestionValues')->where('value_id='.$id)->fetchOne();
		return $group;   
    }
}