<?php

/**
 * UlsLanguageMaster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsLanguageMaster extends BaseUlsLanguageMaster
{
	 function preInsert($event){
		 $CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	static function searchcount($lang=""){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq=!empty($level)? !empty($sq)? " and lang_name like '%".$lang."%'":" and lang_name like '%".$lang."%'":"";
		$learning="select count(*) as num_count from uls_language_master where 1 and  parent_org_id=".$CI->session->userdata('parent_org_id').$sq;
     	$eve=UlsMenu::callpdorow($learning);                
		return $eve['num_count'];
	}
    
    static function search($start,$limit,$lang=""){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq=!empty($lang)? !empty($sq)? " and a.lang_name like '%".$lang."%'":" and a.lang_name like '%".$lang."%'":"";
		$learnings="select b.value_name as language_status, a.* from uls_language_master a
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'STATUS' AND a.lang_status = b.value_code 
		where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq limit $limit offset $start";
		$result=UlsMenu::callpdo($learnings);
		return $result;
    }
	
	static function viewlanguage($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$level=array();
		if(!empty($id) && is_numeric($id)){
			$query="SELECT b.value_name as language_status, a. * FROM uls_language_master a 
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'STATUS' AND a.lang_status = b.value_code 
			WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.lang_id=$id";
			$level=UlsMenu::callpdorow($query);
		}
		return $level;
	}
	
	static function get_lan_id(){
		$group=Doctrine_Query::Create()->from('UlsLanguageMaster')->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
		return $group;   
    }
}