<?php

/**
 * UlsLevelMasterScale
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsLevelMasterScale extends BaseUlsLevelMasterScale
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_by=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
    }
	
	static function levelscale($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$level=array();
		if(!empty($id) && is_numeric($id)){
			$query="SELECT  a.* FROM uls_level_master_scale a
			WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.level_id=$id";
			$level=UlsMenu::callpdo($query);
		}
		return $level;
	}
	
	static function scale_values(){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT  a.* FROM uls_level_master_scale a
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id');
		$level=UlsMenu::callpdo($query);
		return $level;
	}
	
	static function scale_values_report(){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT  a.* FROM uls_level_master_scale a
		left join(SELECT `level_id`,`level_name`,`status` FROM `uls_level_master`) b on a.level_id=b.level_id
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and  b.status='A'";
		$level=UlsMenu::callpdo($query);
		return $level;
	}
	
	static function levelscale_detail($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$level=array();
		if(!empty($id) && is_numeric($id)){
			$query="SELECT  a.* FROM uls_level_master_scale a
			WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.scale_id=$id";
			$level=UlsMenu::callpdorow($query);
		}
		return $level;
	}
	
	static function levelscale_detail_levels($num,$levels){
		$CI =& get_instance();
		$CI->load->library('session');
		$number=($num+1);
		$level=array();
		if(!empty($num) && is_numeric($num)){
			$query="SELECT  a.* FROM uls_level_master_scale a
			WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.level_id=".$levels." and a.scale_number=".$number;
			$level=UlsMenu::callpdorow($query);
		}
		return $level;
	}
	
	static function scale_values_level_four(){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT  a.* FROM uls_level_master_scale a
		left join(SELECT `level_id`,`level_name`,`status`,level_scale FROM `uls_level_master`) b on a.level_id=b.level_id
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and  b.level_scale=4 and b.status='A' order by a.scale_number ASC";
		$level=UlsMenu::callpdo($query);
		return $level;
	}
	
	static function scale_values_level_five(){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT  a.* FROM uls_level_master_scale a
		left join(SELECT `level_id`,`level_name`,`status`,level_scale FROM `uls_level_master`) b on a.level_id=b.level_id
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and  b.level_scale=5 and b.status='A'";
		$level=UlsMenu::callpdo($query);
		return $level;
	}
	
	static function scale_values_level_two(){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT  a.* FROM uls_level_master_scale a
		left join(SELECT `level_id`,`level_name`,`status`,level_scale FROM `uls_level_master`) b on a.level_id=b.level_id
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and  b.level_scale=2";
		$level=UlsMenu::callpdo($query);
		return $level;
	}
	
	static function level_scale_detail($id,$num){
		$CI =& get_instance();
		$CI->load->library('session');
		$level=array();
		if(!empty($id) && is_numeric($id)){
			$query="SELECT  GROUP_CONCAT(`scale_id`) as scale_ids FROM uls_level_master_scale a
			WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.level_id=".$id." and a.scale_number in (".$num.")";
			$level=UlsMenu::callpdorow($query);
		}
		return $level;
	}
	
	static function level_scale_detail_tni($id,$num){
		$CI =& get_instance();
		$CI->load->library('session');
		$level=array();
		if(!empty($id) && is_numeric($id)){
			$query="SELECT  a.* FROM uls_level_master_scale a
			WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.level_id=".$id." and a.scale_number=".$num;
			$level=UlsMenu::callpdorow($query);
		}
		return $level;
	}
}