<?php

/**
 * UlsMenuCreation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsMenuCreation extends BaseUlsMenuCreation
{
	static function perpage(){
        return array(1,2,5,10,15,20,25,50,100);
    }
	
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	static function searchcount($emp_name="",$emp_number=""){
		$sq=!empty($emp_name)? (!empty($sq)? " and a.menu_name like '%$emp_name%'":" and a.menu_name like '%$emp_name%'"):"";
        $sq.=!empty($emp_number)? (!empty($sq)? " and a.system_menu_type like '$emp_number'":" and a.system_menu_type like '$emp_number'"):"";
        $menus= Doctrine_Query::create()->select("count(*) as numcount")->from("UlsMenuCreation a")->leftJoin("a.UlsActors b")->where("1 ". $sq)->setHydrationMode(Doctrine::HYDRATE_ARRAY)->fetchOne();
        return $menus['numcount'];
    }
	
	static function search($start, $limit,$emp_name="",$emp_number=""){
		$sq=!empty($emp_name)? (!empty($sq)? " and a.menu_name like '%$emp_name%'":" and a.menu_name like '%$emp_name%'"):"";
        $sq.=!empty($emp_number)? (!empty($sq)? " and a.system_menu_type like '$emp_number'":" and a.system_menu_type like '$emp_number'"):"";
        $menus= Doctrine_Query::create()->select("a.*,b.Name as actor,b.actor_id as actor_id")->from("UlsMenuCreation a")->leftJoin("a.UlsActors b")->where("1 ". $sq)->limit($limit)->offset($start)->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
        return $menus;
    }  
	
	static function make_pages($page,$limit,$total,$filePath,$url){
        //$counter=0;
        $targetpage=$filePath; $stages = 2;
        $page= $page == 0 ? 1:$page;
        $prev = $page - 1; $next = $page + 1;
        $lastpage = ceil($total/$limit);
        $LastPagem1 = $lastpage - 1;
        $paginate = '';
        $pp1=($page*$limit);
		$cou=$pp1-$limit+1;
        $pp=$pp1>$total? $total:$pp1;
		if($pp==0){$cou=$pp1-$limit+0;}else{$cou=$pp1-$limit+1;}
		//$counter=0;
		
        $paginate .= "<div class='dataTables_info' id='edit_datable_2_info' role='status' aria-live='polite'>Showing ".($cou)."-".($pp)." of $total entries</div><div class='dataTables_paginate paging_simple_numbers' id='edit_datable_2_paginate'>";
        //if($lastpage > 1){            
            // Previous
            if ($page > 1){
                $paginate.= "<a class='paginate_button previous' href='$targetpage?page=$prev&$url' aria-controls='edit_datable_2' data-dt-idx='0' tabindex='0' id='edit_datable_2_previous'><</a>";
            }
            else{
                $paginate.= "<a class='paginate_button previous disabled' aria-controls='edit_datable_2' data-dt-idx='0' tabindex='0' id='edit_datable_2_previous'><</a>";
            }
			$paginate.="<span>";
            // Pages
            if ($lastpage <= 3 + ($stages * 2)){
                // Not enough pages to breaking it up
                for ($counter = 1; $counter <= $lastpage; $counter++){
                    if ($counter == $page){
                        $paginate.= "<a class='paginate_button current' aria-controls='edit_datable_2' data-dt-idx='1' tabindex='0'>$counter</a>";
                    }
                    else{
                        $paginate.= "<a class='paginate_button ' aria-controls='edit_datable_2' data-dt-idx='$counter' tabindex='0' href='$targetpage?page=$counter&$url'>$counter</a>";
                    }
                }
            }
            elseif($lastpage > 3 + ($stages * 2)){
                if($page < 1 + ($stages * 2)){
                    for ($counter = 1; $counter < 4 + ($stages * 2); $counter++){
                        if ($counter == $page){
                            $paginate.= "<a class='paginate_button current' aria-controls='edit_datable_2' data-dt-idx='1' tabindex='0'>$counter</a>";
                        }
                        else{
                            $paginate.= "<a class='paginate_button ' aria-controls='edit_datable_2' data-dt-idx='$counter' tabindex='0' href='$targetpage?page=$counter&$url'>$counter</a>";
                        }
                    }
                    //$paginate.= "...";
                    $paginate.= "<a class='paginate_button ' aria-controls='edit_datable_2' data-dt-idx='$LastPagem1' tabindex='0' href='$targetpage?page=$LastPagem1&$url'>$LastPagem1</a>";
                    $paginate.= "<a class='paginate_button ' aria-controls='edit_datable_2' data-dt-idx='$lastpage' tabindex='0' href='$targetpage?page=$lastpage&$url'>$lastpage</a>";		
                }
                // Middle hide some front and some back
                elseif($lastpage - ($stages * 2) > $page && $page > ($stages * 2)){
                    $paginate.= "<a class='paginate_button ' aria-controls='edit_datable_2' data-dt-idx='1' tabindex='0' href='$targetpage?page=1&$url'>1</a>";
                    $paginate.= "<a class='paginate_button ' aria-controls='edit_datable_2' data-dt-idx='2' tabindex='0' <a href='$targetpage?page=2&$url'>2</a>";
                    //$paginate.= "...";
					$counter = $page - $stages;
                    for ($counter = $page - $stages; $counter <= $page + $stages; $counter++){
                        if ($counter == $page){
                            $paginate.= "<a class='paginate_button current' aria-controls='edit_datable_2' data-dt-idx='1' tabindex='0'>$counter</a>";
                        }
                        else{
                            $paginate.= "<a class='paginate_button ' aria-controls='edit_datable_2' data-dt-idx='$counter' tabindex='0' href='$targetpage?page=$counter&$url'>$counter</a>";
                        }
                    }
                    //$paginate.= "...";
                    $paginate.= "<a class='paginate_button ' aria-controls='edit_datable_2' data-dt-idx='$LastPagem1' tabindex='0' href='$targetpage?page=$LastPagem1&$url'>$LastPagem1</a>";
                    $paginate.= "<a class='paginate_button ' aria-controls='edit_datable_2' data-dt-idx='$lastpage' tabindex='0' href='$targetpage?page=$lastpage&$url'>$lastpage</a>";		
                }
                // End only hide early pages
                else{
                    $paginate.= "<a class='paginate_button ' aria-controls='edit_datable_2' data-dt-idx='1' tabindex='0' href='$targetpage?page=1&$url'>1</a>";
                    $paginate.= "<a class='paginate_button ' aria-controls='edit_datable_2' data-dt-idx='2' tabindex='0' <a href='$targetpage?page=2&$url'>2</a>";
                    //$paginate.= "...";
                    for($counter = $lastpage - (2 + ($stages * 2)); $counter <= $lastpage; $counter++){
                        if ($counter == $page){
                            $paginate.= "<a class='paginate_button current' aria-controls='edit_datable_2' data-dt-idx='1' tabindex='0'>$counter</a>";
                        }
                        else{
                            $paginate.= "<a class='paginate_button' aria-controls='edit_datable_2' data-dt-idx='$counter' tabindex='0' href='$targetpage?page=$counter&$url'>$counter</a>";
                        }
                    }
                }
            }
			$paginate.="</span>";
            // Next
			
            if ($page < $counter - 1){
                $paginate.= "<a class='paginate_button next' href='$targetpage?page=$next&$url' aria-controls='edit_datable_2' data-dt-idx='7' tabindex='0' id='edit_datable_2_next'>></a>";
            }
            else{
                $paginate.= "<a class='paginate_button next disabled' aria-controls='edit_datable_2' data-dt-idx='7' tabindex='0' id='edit_datable_2_next'>></a>";
            }          
        //}
        $paginate.= "</div>";
        return $paginate;
    }
	
	static function menutype($id){
        $menu= Doctrine_Core::getTable('UlsMenuCreation')->find($id);
        return $menu;
    }
}