<?php

/**
 * UlsMenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsMenu extends BaseUlsMenu
{
	 function preInsert($event){
        $this->created_by=$_SESSION['username'];
        $this->created_date=date('Y-m-d');
        $this->modified_by=$_SESSION['username'];        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$_SESSION['user_id'];
    }
	
    function preUpdate($event){
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$_SESSION['username'];
        $this->last_modified_id=$_SESSION['user_id'];
    }
	
    /* used fetch all rows in object format */
    static function  callpdoobj($query){
        $pdo = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $ulsmenu = $pdo->prepare($query);
        $ulsmenu->execute();
		$ulsmenu->setFetchMode(PDO::FETCH_ASSOC);
        return $ulsmenu->fetchall(PDO::FETCH_OBJ);        
    }
	
	/* used fetch one row in object format */
    static function  callpdoobjrow($query){
        $pdo = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $ulsmenu = $pdo->prepare($query);
        $ulsmenu->execute();
		$ulsmenu->setFetchMode(PDO::FETCH_ASSOC);
        return $ulsmenu->fetch(PDO::FETCH_OBJ);        
    }
    
    /* used fetch all rows in array format */
    static function  callpdo($query){
        $pdo = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $ulsmenu = $pdo->prepare($query);
        $ulsmenu->execute();
		$ulsmenu->setFetchMode(PDO::FETCH_ASSOC);
        return $ulsmenu->fetchAll();        
    }
	
	/* used fetch one row in array format */
    static function  callpdorow($query){
        $pdo = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $ulsmenu = $pdo->prepare($query);
        $ulsmenu->execute();
		$ulsmenu->setFetchMode(PDO::FETCH_ASSOC);
        return $ulsmenu->fetch();        
    }

	/* execute */
    static function  callexecute($query){
        $pdo = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $ulsmenu = $pdo->prepare($query);
        $ulsmenu->execute();     
    }
	
	static function display_children2($parent, $level,$menu,$chk,$uri){
        Global $sidemenuu;
        $chks=explode(",",$chk);
        $ulsmenulinks=UlsMenu::callpdo("SELECT a.menu_id as id, a.menu_name as name, a.link as link, a.image_link as image_link, Deriv1.Count as Count from uls_menu a  LEFT OUTER JOIN (SELECT parent_id, COUNT(*) AS Count FROM uls_menu GROUP BY parent_id) Deriv1 ON a.menu_id = Deriv1.parent_id WHERE  a.parent_id=" . $parent." and a.menu_creation_id in (".$menu.") order by a.sort_page asc");
        $sidemenuu.=$parent!=0?"<ul id='dashboard_$parent' class='collapse collapse-level-$level'>":"";
        foreach($ulsmenulinks as $row){
            if($row['Count'] > 0){ //class='active open'
				$img2=!empty($row['image_link'])?($row['image_link']):"zmdi zmdi-book";
                $sidemenuu.="<li><a  href='javascript:void(0);' data-toggle='collapse' data-target='#dashboard_".($row['id'])."'>
				<div class='pull-left'><i class='$img2 mr-20'></i><span class='right-nav-text'>" . $row['name'] . "</span></div><div class='pull-right'><i class='zmdi zmdi-caret-down'></i></div><div class='clearfix'></div></a>";				
                UlsMenu::display_children2($row['id'], $level + 1,$menu,$chk,$uri);
				$sidemenuu.="</li> <li><hr class='light-grey-hr mb-10'></li>";
                //if(in_array($row['id'],$chks)){ $sidemenuu.="</li>";}
            }
            elseif ($row['Count']==0){
                //if(in_array($row['id'],$chks)){
                    if($row['link']!="#"){
						$uri=str_replace(array("//hetero_lms/","/hetero_lms/","//cmsmvc/","/cmsmvc/"),array("","","",""),$uri);
						//$uri=str_replace('/polycab/','',$uri);
						if(strpos($row['link'],$uri)){ $sst="class='active'";}else{$sst="";}
						//$sst="";
						$img=!empty($row['image_link'])?($row['image_link']):"zmdi zmdi-book";
						if($parent==0){
							 $sidemenuu.="<li ".$sst."><a href='".BASE_URL.$row['link']."' onclick=\"link('".$row['link']."')\" ".$sst." ><div class='pull-left'><i class='$img mr-20'></i><span class='right-nav-text'>" . $row['name'] . "</span></div><div class='pull-right'></div><div class='clearfix'></div></a></li>
							 <li><hr class='light-grey-hr mb-10'></li>";
						}
						else{
							 $sidemenuu.="<li ".$sst."><a href='".BASE_URL.$row['link']."' onclick=\"link('".$row['link']."')\" ".$sst." >" . $row['name'] . "</a></li>";
						}
                       
						
                    }
                //}
            } else;
        }
        $sidemenuu.=$parent!=0?"</ul>":"";
        return $sidemenuu;
    }
	
	static function display_parent_nodes($id,$home){
		$CI =& get_instance();
		$CI->load->library('session');
        $Menu_Id=$CI->session->userdata('Menu_Id');
        if(!empty($Menu_Id)){
			$mid=array();
			$id=str_replace(array("//hetero_lms","/hetero_lms","//cmsmvc","/cmsmvc"),array("","","",""),$id);
            //unset($_SESSION['selectedmenuitem']);
            $ulsmenulinks=UlsMenu::callpdo("SELECT menu_id,parent_id,link,menu_name FROM `uls_menu` WHERE menu_creation_id=".$CI->session->userdata('Menu_Id'));
            foreach($ulsmenulinks as $row){
                $ids=$row['menu_id'];
                $data[$ids]=$row; 
            }
            foreach($data as $v){
                if($v['link']==$id){
                    $b=$v['menu_id'];
                    $current =$data[$b];
					$mid[]=$b;
                    //$current = $data[$id];
                    $parent_id = $current["parent_id"] === 0 ? 0 : $current["parent_id"];					
                    //$parents = ($current["link"]=="#")?array("<a href='#'>".$current["menu_name"]."</a>"):array("<a href='/polycab".$current["link"]."'>".$current["menu_name"]."</a>");
                    $i=0;
                    while(isset($data[$parent_id])){
                        $current = $data[$parent_id];
						$mid[]=$parent_id;
                        $parent_id = $current["parent_id"] === 0 ? 0 : $current["parent_id"];
						//isset($data[$parent_id])?print_r($data[$parent_id]):"";
                        if($i==0){$_SESSION['selectedmenuitem']=$current["menu_name"];}
                        //$parents[] = ($current["link"]=="#")?"<a href='#'>".$current["menu_name"]."</a>":"<a href='/polycab".$current["link"]."'>".$current["menu_name"]."</a>";
                        $i++;
                    }
                }
            }
			foreach($mid as $v){
				$lnk=$data[$v]['link'];
				if($data[$v]['link']=='#'){
					//echo $data[$v]['menu_name'];
					$ulsmnulnk=UlsMenu::callpdorow("SELECT menu_id,parent_id,link,menu_name FROM `uls_menu` WHERE parent_id=$v and menu_creation_id=".$CI->session->userdata('Menu_Id')." order by sort_page asc");
					$lnk=$ulsmnulnk['link'];
					if($lnk=="#"){
						$ulsmnulnk2=UlsMenu::callpdorow("SELECT menu_id,parent_id,link,menu_name FROM `uls_menu` WHERE parent_id=".$ulsmnulnk['menu_id']." and menu_creation_id=".$CI->session->userdata('Menu_Id')." order by sort_page asc");
						$lnk=$ulsmnulnk2['link'];
						if($lnk=="#"){
							$ulsmnulnk3=UlsMenu::callpdorow("SELECT menu_id,parent_id,link,menu_name FROM `uls_menu` WHERE parent_id=".$ulsmnulnk2['menu_id']." and menu_creation_id=".$CI->session->userdata('Menu_Id')." order by sort_page asc");
							$lnk=$ulsmnulnk3['link'];							
							if($lnk=="#"){
								$ulsmnulnk4=UlsMenu::callpdorow("SELECT menu_id,parent_id,link,menu_name FROM `uls_menu` WHERE parent_id=".$ulsmnulnk3['menu_id']." and menu_creation_id=".$CI->session->userdata('Menu_Id')." order by sort_page asc");
								$lnk=$ulsmnulnk4['link'];
							}							
						}
					}
				}
				$parents[] = "<a href='".BASE_URL.$lnk."'>".$data[$v]["menu_name"]."</a>";
			}
            //$parents[] =$home;
			if(!isset($parents)){$parents=array();}
			if(count($parents)<=0){$parents[] ="";}
            return implode(" ** ", array_reverse($parents));
        }
    }
	
	function display_children_child($parent, $level,$menucid,$menu,$main="",$sellist=array()){
        Global $menulist;
		
		$ulsmenulinks=UlsMenu::callpdo("SELECT a.menu_id as id, a.menu_name as name, Deriv1.Count FROM `uls_menu` a  LEFT OUTER JOIN (SELECT parent_id, COUNT(*) AS Count FROM `uls_menu` GROUP BY parent_id) Deriv1 ON a.menu_id = Deriv1.parent_id WHERE a.parent_id=" .$parent." and a.menu_creation_id=".$menucid." and a.type='".$menu."' order by a.sort_page asc");
        foreach($ulsmenulinks as $row){
            if($row['Count'] > 0){
                $dis=in_array($row['id'], $sellist) ? "disabled='disabled'" : "";
				$menulist.="<option $dis value='".$row['id']."'>".$main.$row['name']."</option>";
                $ulsmenu= new UlsMenu(); $ulsmenu->display_children_child($row['id'], $level + 1,$menucid,$menu,$main."&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",$sellist);
            }elseif ($row['Count']==0) {
                $dis=in_array($row['id'], $sellist) ? "disabled='disabled'" : "";
                $menulist.="<option $dis value='".$row['id']."'>".$main.$row['name']."</option>";	
			} else{}
		}return $menulist;
	}
	
	function menulist($id,$ch_id){
		$id=(!empty($ch_id))?$id.','.$ch_id:$id;
        if(!empty($id)){	
			
			$ulsmenulinks=UlsMenu::callpdo("SELECT a.menu_id as id, a.parent_id, a.menu_name as name, a.default_name as default_name, a.link as link, a.create_page as create_page, a.update_page as update_page, a.read_page as read_page, a.delete_page as delete_page FROM `uls_menu` a WHERE a.menu_id in ($id)");	
			$child=array();
			foreach($ulsmenulinks as $row){
				$menuid=$row['id'];
				$parentid=$row['parent_id'];
				$child[$menuid]=$parentid;				
			}
			$result = $this->parseTree($child);
			$this->printTree($result,0);	
		} 			
			
    }
	
	function parseTree($tree, $root = 0) {
    $return = array();
    # Traverse the tree and search for direct children of the root
    foreach($tree as $child => $parent) {
        # A direct child is found
        if($parent == $root) {
            # Remove item from tree (we don't need to traverse this again)
            unset($tree[$child]);
            # Append the child into result array and parse its children
            $return[] = array(
                'menuid' => $child,
                'children' => $this->parseTree($tree, $child)
            );
        }
    }
    return empty($return) ? null : $return;
	
	}
	
	function printTree($tree,$flg) {	
		if(!is_null($tree) && count($tree) > 0) {		
			echo $flg==1?"<ol class='dd-list'>":"";
			foreach($tree as $node){			
				$row=UlsMenu::callpdorow("SELECT a.menu_id as id, a.parent_id, a.menu_name as name, a.default_name as default_name, a.link as link, a.image_link as image_link, a.create_page as create_page, a.update_page as update_page, a.read_page as read_page, a.delete_page as delete_page FROM `uls_menu` a WHERE a.menu_id=".$node['menuid']);
				
				$j=$row['id']; $create_page=$row['create_page']==1 ? "checked='checked'" : ''; $update_page=$row['update_page']==1 ? "checked='checked'" : ''; $read_page=$row['read_page']==1 ? "checked='checked'" : ''; $delete_page=$row['delete_page']==1 ? "checked='checked'" : '';
				echo "<li class='dd-item' data-id='".$row['id']."'><button class='dd-collapse chk' type='button'>Collapse</button><div class='dd-handle'>" . $row['name'] . "</div><div class='dd-handle-child'><input type='hidden' name='menu[$j]' value='' ><label>Name</label><input type='text' name='name[$j]' value='".$row['name']."' ><br><br><input type='checkbox' value='1' $create_page name='create_page[$j]'>Create<input type='checkbox' value='1' $read_page name='read_page[$j]'>View <input type='checkbox' value='1' $update_page name='update_page[$j]'>Edit <input type='checkbox' value='1' $delete_page name='delete_page[$j]'>Delete<br><br><label>Link: ".$row['link']."</label><input type='hidden' value='".$row['link']."' name='link[$j]' readonly >&nbsp;&nbsp;&nbsp;&nbsp; <label>Deault Name : ".$row['default_name']."</label><input type='hidden' readonly name='default_name[$j]' value='".$row['default_name']."' ><input type='hidden' readonly name='image_link[$j]' value='".$row['image_link']."' ><a class='remove'>Remove</a></div>";
				
				$this->printTree($node['children'],1);
				echo "</li>";
			}
			echo $flg==1?"</ol>":"";
		}
	}
	
	static function parentchild($parent,$menu_id,$aa,$b){
		$child_mid='';
        foreach($aa as $key=>$a){
            $menunamee="menu";$name="name"; $default_name="default_name"; $link="link"; $create_page="create_page"; $update_page="update_page";$read_page="read_page";$delete_page="delete_page";
            $menu=!empty($_POST[$menunamee][$a->id])? Doctrine_Core::getTable('UlsMenu')->find($_POST[$menunamee][$a->id]) :new UlsMenu();
            $menu->parent_id=$parent;
            $menu->menu_name=$_POST[$name][$a->id];
            $menu->default_name=$_POST[$default_name][$a->id];
            $menu->type=$_POST['menu_type'];
            $menu->menu_creation_id=$menu_id;
            $menu->sort_page=$key;
            $menu->link=$_POST[$link][$a->id];                
            isset($_POST[$create_page][$a->id])? $menu->create_page=$_POST[$create_page][$a->id]:"";
            isset($_POST[$update_page][$a->id])? $menu->update_page=$_POST[$update_page][$a->id]:"";
            isset($_POST[$read_page][$a->id])? $menu->read_page=$_POST[$read_page][$a->id]:"";
            isset($_POST[$delete_page][$a->id])? $menu->delete_page=$_POST[$delete_page][$a->id]:"";
            $menu->save();
			if($child_mid==''){
				$child_mid=$menu->menu_id;
			}else{
				$child_mid=$child_mid.','.$menu->menu_id;
			}
            if(isset($a->children)){
                $subchild=UlsMenu::parentchild($menu->menu_id,$menu_id,$a->children,$_POST);
				$child_mid=$child_mid.','.$subchild;
            }
			
		}
		return $child_mid;
    }
	
	static function display_children($parent, $level,$menu){
        Global $menuitem;
        $ulsmenulinks=UlsMenu::callpdo("SELECT a.menu_id as id, a.menu_name as name, a.link as link, Deriv1.Count as Count from uls_menu a  LEFT OUTER JOIN (SELECT parent_id, COUNT(*) AS Count FROM uls_menu GROUP BY parent_id) Deriv1 ON a.menu_id = Deriv1.parent_id WHERE  a.parent_id=" . $parent." and a.menu_creation_id in (".$menu.") order by a.sort_page asc");
        $menuitem.="<ol  class='dd-list'>";
        foreach($ulsmenulinks as $row){            
            if($row['Count'] > 0){
                $menuitem.="<li class='dd-item dd3-item' data-id='".$row['id']."'><div class='dd-handle'><a onclick='return false;' href='".BASE_URL.$row['link']."'>" . $row['name'] . "</a></div>";
                UlsMenu::display_children($row['id'], $level + 1,$menu);
                $menuitem.="</li>";
            }
            elseif ($row['Count']==0) {
                $menuitem.="<li class='dd-item dd3-item' data-id='".$row['id']."'><div class='dd-handle'><a onclick='return false;' href='".BASE_URL.$row['link']."'>" . $row['name'] . "</a></div></li>";
            } else;
        }
        $menuitem.="</ol>";
        return $menuitem;
    }
	
	 static function usercreation_menu($parent,$level,$menu,$mid,$mainkey){
        Global $menuitem;
		$ulsmenulinks=UlsMenu::callpdo("SELECT a.menu_id as id, a.menu_name as name, a.link as link, Deriv1.Count as Count from uls_menu a  LEFT OUTER JOIN (SELECT parent_id, COUNT(*) AS Count FROM uls_menu GROUP BY parent_id) Deriv1 ON a.menu_id = Deriv1.parent_id WHERE  a.parent_id=" . $parent." and a.menu_creation_id in (".$menu.") order by a.sort_page asc");
        $menuitem.="<ol  class='dd-list'>";
        foreach($ulsmenulinks as $row){
            if($row['Count'] > 0){
                $menuitem.="<li class='dd-item dd3-item' data-id='".$row['id']."'><div class='dd3-content'><a onclick='return false;' href='".BASE_URL.$row['link']."'>" . $row['name'] . "</a><input type='checkbox' name='chk[$mainkey][]' id='chk".$row['id']."' value=".$row['id']." style='float:right; padding:3px 5px 0px 0px;' checked='checked'></div>";
                UlsMenu::usercreation_menu($row['id'], $level + 1,$menu,$mid,$mainkey);
                $menuitem.="</li>";
            }
            elseif ($row['Count']==0) {
                $menuitem.="<li class='dd-item dd3-item' data-id='".$row['id']."'><div class='dd3-content'><a onclick='return false;' href='".BASE_URL.$row['link']."'>" . $row['name'] . "</a><input type='checkbox' name='chk[$mainkey][]' id='chk".$row['id']."' value=".$row['id']." style='float:right; padding:3px 5px 0px 0px;' checked='checked'></div></li>";
            } else;
        }
        $menuitem.="</ol>";
        return $menuitem;
    }
    
    static function displays($parent, $level,$menu,$defaultmenutype,$par=false){
        $remove=$par===true?"":"Remove";
        Global $menuitem; Global $k;
        $ulsmenulinks=UlsMenu::callpdo("SELECT a.menu_id as id, a.menu_name as name, a.default_name as default_name, a.link as link, a.image_link as image_link, a.create_page as create_page, a.update_page as update_page, a.read_page as read_page, a.delete_page as delete_page, Deriv1.Count as Count from uls_menu a  LEFT OUTER JOIN (SELECT parent_id, COUNT(*) AS Count FROM uls_menu GROUP BY parent_id) Deriv1 ON a.menu_id = Deriv1.parent_id WHERE  a.parent_id=" . $parent." and a.menu_creation_id in (".$menu.") order by a.sort_page asc");
        empty($k)?"":$menuitem.="<ol  class='dd-list'>";
		$menids='';
        foreach($ulsmenulinks as $row){
            $k=1;            
            $defmenu=UlsMenu::callpdo("select b.`menu_id` as id FROM uls_menu b, `uls_menu_creation` a where a.`System_Menu_Type` = '$defaultmenutype' AND a.`Default_Menu` =1 AND a.`Menu_Creation_id` = b.`menu_creation_id` AND b.`default_name` = '".$row['default_name']."'");
            @$j=$defmenu[0]['id'];
			$menids.=($menids=='')?$j:','.$j;
            if($row['Count'] > 0){
                $create_page=$row['create_page']==1 ? "checked='checked'" : ''; $update_page=$row['update_page']==1 ? "checked='checked'" : ''; $read_page=$row['read_page']==1 ? "checked='checked'" : ''; $delete_page=$row['delete_page']==1 ? "checked='checked'" : '';
                $menuitem.="<li class='dd-item' data-id='".$j."'><button class='dd-collapse chk' type='button'>Collapse</button><div class='dd-handle'>" . $row['name'] . "</div>  <div class='dd-handle-child'><input name='menu[$j]' type='hidden' value='".$row['id']."' ><label>Name</label><input type='text' name='name[$j]' value='".$row['name']."' ><br><br><input type='checkbox' value='1' $create_page name='create_page[$j]'>Create
                <input type='checkbox' value='1' $read_page name='read_page[$j]'>View <input type='checkbox' value='1' $update_page name='update_page[$j]'>Edit <input type='checkbox' value='1' $delete_page name='delete_page[$j]'>Delete<br><br>
                <label>Link: ".$row['link']."</label><input type='hidden' value='".$row['link']."' name='link[$j]' readonly >&nbsp;&nbsp;&nbsp;&nbsp; <label>Deault Name : ".$row['default_name']."</label><input type='hidden' readonly name='default_name[$j]' value='".$row['default_name']."' ><input type='hidden' readonly name='image_link[$j]' value='".$row['image_link']."' ><a class='remove'>$remove</a></div>";
                UlsMenu::displays($row['id'], $level + 1,$menu,$defaultmenutype,$par);
                $menuitem.="</li>";
            }
            elseif ($row['Count']==0) {
                $create_page=$row['create_page']==1 ? "checked='checked'" : ''; $update_page=$row['update_page']==1 ? "checked='checked'" : ''; $read_page=$row['read_page']==1 ? "checked='checked'" : ''; $delete_page=$row['delete_page']==1 ? "checked='checked'" : '';
                $menuitem.="<li class='dd-item' data-id='".$j."'><button type='button' class='dd-collapse chk'>collapse</button><div class='dd-handle'>" . $row['name'] . "</div>  <div class='dd-handle-child'><input name='menu[$j]' type='hidden' value='".$row['id']."' ><label>Name</label><input type='text' name='name[$j]' value='".$row['name']."' ><br><br><input type='checkbox' value='1' $create_page name='create_page[$j]'>Create
                <input type='checkbox' value='1' $read_page name='read_page[$j]'>View <input type='checkbox' value='1' $update_page name='update_page[$j]'>Edit <input type='checkbox' value='1' $delete_page name='delete_page[$j]'>Delete<br><br>
                <label>Link: ".$row['link']."</label><input type='hidden' value='".$row['link']."' name='link[$j]' readonly >&nbsp;&nbsp;&nbsp;&nbsp; <label>Deault Name : ".$row['default_name']."</label><input type='hidden' readonly name='default_name[$j]' value='".$row['default_name']."' ><input type='hidden' readonly name='image_link[$j]' value='".$row['image_link']."' ><a class='remove'>$remove</a></div></li>";
            } else;
        }
        $menuitem.="</ol>";
        return $menuitem;
    }
	
    
	
    
    function display_childrens($parent, $level,$menucid,$menu,$main="",$sellist=array()){
        $ulsmenulinks=UlsMenu::callpdo("SELECT a.menu_id as id, a.menu_name as name, Deriv1.Count FROM `uls_menu` a  LEFT OUTER JOIN (SELECT parent_id, COUNT(*) AS Count FROM `uls_menu` GROUP BY parent_id) Deriv1 ON a.menu_id = Deriv1.parent_id WHERE a.parent_id=" .$parent." and a.menu_creation_id=".$menucid." and a.type='".$menu."' order by a.sort_page asc");
        foreach($ulsmenulinks as $row){
            if($row['Count'] > 0){
                $dis=in_array($row['id'], $sellist) ? "disabled='disabled'" : "";
                echo "<option $dis value='".$row['id']."'>".$main.$row['name']."</option>";
                $ulsmenu= new UlsMenu(); $ulsmenu->display_children_child($row['id'], $level + 1,$menucid,$menu,$main."&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",$sellist);
            }
			elseif ($row['Count']==0) {
                $dis=in_array($row['id'], $sellist) ? "disabled='disabled'" : "";
                echo "<option $dis value='".$row['id']."'>".$main.$row['name']."</option>";	
			}
			else{}
		}
	}
    
    
	// to get all menu id at a time
	
	static function menu_values($id){
        $query="SELECT group_concat( `menu_id` ) as menu_id FROM `uls_menu_creation` a, `uls_menu` b WHERE a.`menu_creation_id` = b.`menu_creation_id` and  a.`menu_creation_id`=".$id;
		$locations=UlsMenu::callpdorow($query);
		return $locations;
    }
	
}