<?php

/**
 * UlsNotification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsNotification extends BaseUlsNotification
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
		$this->created_time=date('Y-m-d H:i:s');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
		$this->modified_time=date('Y-m-d H:i:s');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
		$this->modified_time=date('Y-m-d H:i:s');
    }
    
    
     public static function searchcount($org_id){
        $sq=!empty($org_id)? " and a.parent_org_id= '$org_id'":"";
		$query="SELECT count(*) as numcount FROM uls_notification a
		LEFT JOIN (SELECT value_id,master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'STATUS' AND a.status = b.value_code 
		WHERE 1 $sq ";
		$testcount=UlsMenu::callpdorow($query);		
		return $testcount['numcount'];
    }
	
	public static function searchcount_org(){
	  // $sq=!empty($org_id)? " and a.parent_org_id= '$org_id'":"";
		$query="SELECT count(*) as numcount from uls_notification_types WHERE 1 ";
		$testcount=UlsMenu::callpdorow($query);		
		return $testcount['numcount'];
	
	 }
    
   
   public static function search($start, $limit,$org_id){
        $sq=!empty($org_id)? " and a.parent_org_id= '$org_id'":"";
		$query="SELECT b.value_name,a.notification_id,c.org_name,a.notification_name,a.parent_org_id FROM uls_notification a
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'STATUS' AND a.status = b.value_code 
                Left Join(select org_name,organization_id from uls_organization_master group by organization_id)c on c.organization_id=a.parent_org_id
                
		WHERE 1 $sq limit $limit offset $start";
		$compdetails=UlsMenu::callpdo($query);
        return $compdetails;
    }

   public static function search_org($start, $limit){
        //$sq=!empty($org_id)? " and a.parent_org_id= '$org_id'":"";
		$query="SELECT * from uls_notification_types WHERE 1  limit $limit offset $start";
		$compdetails=UlsMenu::callpdo($query);
        return $compdetails;
    }	
    
	static function get_notification_users($id){
      $ulsmenulinks=UlsMenu::callpdo("SELECT test_name,test_id,test_option,start_date_active,end_date_active,max_attempts from `uls_test` WHERE test_id=".$id);
       
        return $ulsmenulinks;
   } 
   
   static function get_notifications(){
       $ulsmenulinks=UlsMenu::callpdo("SELECT notification_id,notification_name  from `uls_notification`");
       return $ulsmenulinks;
        
   }
   
   static function get_notifications_users($id,$status,$type) {
       if(empty($id) and empty($type) and empty($status)){
                $dd=Doctrine_Query::Create()->select('notification_name,status,type,parent_org_id')->from('UlsNotification')->execute();
                return $dd;
                }
       else {
                $pdo = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
                 $sql=!empty($id)? "notification_id=".$id :" ";
                  $sql2=array();
                  if(!empty($id) ){  $sql=!empty($id)? "notification_id=".$id :" "; }
                  else if(!empty($status) || !empty($type) ){
                                  $sql=!empty($id)? "notification_id=".$id :" ";
                                  !empty($status) ? $sql2[]="status='".$status."'":"";
                                  !empty($type) ? $sql2[]="type='".$type."'":"";
                             $sql.=!empty($id)? " and ( ".implode(" and ",$sql2).")" :  " ( ".implode(" and ",$sql2).")";
                    } 
        
           $emp_data=UlsMenu::callpdo("select notification_id,notification_name,status,type,parent_org_id from uls_notification where (".$sql.")");
//           $emp_data="select notification_name,status,type,parent_org_id from uls_notification where (".$sql.")";
//           $stmt = $pdo->prepare($emp_data);
//           $stmt->execute();
//           $org_values=$stmt->fetchAll();
       } 
       return $emp_data;
       
   }
     
   static function get_notification_details($id){
      // $emp_data=UlsMenu::callpdo("select notification_id,notification_name,status,type,parent_org_id,to,cc,history,time,time_units from uls_notification where ( notification_id=".$id.")");
         $pdo = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
         $emp_data="SELECT `notification_id`,`parent_org_id`,`notification_name`,`comments`,`status`,`notification_time`,`time_units`,`type`,`event_type`,`history`,`mail_to`,`mail_cc` FROM `uls_notification` WHERE `notification_id`=".$id;
		 
		  $emp_data=UlsMenu::callpdorow($emp_data);
          
      return $emp_data; 
   }
   
    static function get_notification_details_forview($id){
    
   $notificat="select a.notification_id,a.`notification_name`,b.value_name as status,c.org_name,a.`comments`,a.`event_type`,a.`history`,a.`mail_to`,a.`mail_cc` from `uls_notification` a "
               . "  left join( select value_code, value_name from uls_admin_values where master_code like 'STATUS' group by master_code)b on  b.value_code=a.status "
             . " left join (select organization_id,org_name from uls_organization_master group by organization_id)c on c.organization_id=a.parent_org_id  where  a.`notification_id`=".$id;
            $emp_data=UlsMenu::callpdorow($notificat);
        return  $emp_data;
      
      
   }
   static function get_notificationhistory_details($id){
       $emp_data=UlsMenu::callpdo("SELECT  a.`notification_history_id`,a.mail_content,a.`employee_id`,a.`event_id`,a.`timestamp`,a.`mail_delivey_time` FROM `uls_notification_history` a   WHERE a.mail_status='A' and a.`notification_id`=".$id);
        return  $emp_data;
       
    }

}