<?php

/**
 * UlsNotificationHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsNotificationHistory extends BaseUlsNotificationHistory
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
    
	function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
      
    static function get_notification(){
		$CI =& get_instance();
		$CI->load->library('session');
		$emp_id=$CI->session->userdata('emp_id');
		$parent_id=$CI->session->userdata('parent_org_id');
		$notify=Doctrine_Query::Create()->from('UlsNotificationHistory')->where("employee_id='".$emp_id."' and mail_type is NULL and parent_org_id=".$parent_id)->execute();
        return $notify;
    }
}