<?php

/**
 * UlsPositionCompetencyArchive
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsPositionCompetencyArchive extends BaseUlsPositionCompetencyArchive
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
		$this->created_by=$CI->session->userdata('username');
		$this->created_date=date('Y-m-d');
		$this->modified_by=$CI->session->userdata('username');        
		$this->modified_date=date('Y-m-d');
		$this->last_modified_id=$CI->session->userdata('user_id');
	}

	function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
		$this->modified_date=date('Y-m-d');
		$this->modified_by=$CI->session->userdata('username');
		$this->last_modified_id=$CI->session->userdata('user_id');
	}
	
	static function get_competency_arc_position_details($id){
        $comlevel=Doctrine_Query::Create()->select('*')->from('UlsPositionCompetencyArchive')->where('comp_position_id='.$id)->execute();
        return $comlevel;
	}
	
	static function getcompetencypositionrequirements($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.comp_def_id,b.comp_def_name as comp_def_name,c.level_name as level_name, d.scale_name as scale_name,d.scale_id, f.comp_cri_name,f.comp_cri_id, a.* from uls_position_competency_archive a
			left join (select comp_def_id,comp_def_name from uls_competency_definition group by comp_def_id)b on b.comp_def_id=a.comp_position_competency_id
			left join (select level_id,level_name from uls_level_master group by level_id)c on c.level_id=a.comp_position_level_id
			left join (select scale_id,scale_name from uls_level_master_scale group by scale_id)d on d.scale_id=a.comp_position_level_scale_id
			left join (select comp_cri_id,comp_cri_name from uls_competency_criticality group by comp_cri_id)f on f.comp_cri_id=a.comp_position_criticality_id
			where 1 and a.comp_position_id=$id order by a.comp_position_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
}