<?php

/**
 * UlsPositionTemp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsPositionTemp extends BaseUlsPositionTemp
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	static function employee_viewpositionvalidation($val_id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($val_id) && is_numeric($val_id)){
			$query="select a.* from uls_position_temp a
			where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.val_id=$val_id and a.position_id=$pos_id and a.employee_id=".$_SESSION['emp_id'];
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	static function employee_view_position_cat($val_id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($val_id) && is_numeric($val_id)){
			$query="SELECT c.category_id,c.name FROM `uls_validation_positions` a
			left join(SELECT `comp_position_req_id`,`comp_position_id`,`comp_position_competency_id`,`comp_position_level_id`,`comp_position_level_scale_id`,`comp_position_criticality_id` FROM `uls_competency_position_requirements`) p on a.position_id=p.comp_position_id
			left join(SELECT `comp_def_id`,`comp_def_name`,`comp_def_category` FROM `uls_competency_definition`) b on p.	comp_position_competency_id=b.comp_def_id
			left join(SELECT `category_id`,`name` FROM `uls_category`) c on b.comp_def_category=c.category_id
			where a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.val_id=$val_id and a.position_id=$pos_id group by b.comp_def_category";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function get_self_validation_competencies_summary($val_id,$pos_id,$val_pos_id,$cat_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($val_id) && is_numeric($val_id)){
			$query="SELECT p.`comp_position_id`,p.`comp_position_competency_id`,p.`comp_position_level_id`,p.`comp_position_level_scale_id`,b.comp_def_id,b.comp_def_name,s.scale_name,s.scale_id,a.`pos_comp_temp_id`,a.`val_id`,a.`position_id`,a.`employee_id`,a.`required_process`,a.`competency_id`,a.`require_scale_id`,a.`assessed_scale_id`,a.`reason` FROM `uls_validation_positions` ac 
			left join(SELECT `comp_position_req_id`,`comp_position_id`,`comp_position_competency_id`,`comp_position_level_id`,`comp_position_level_scale_id`,`comp_position_criticality_id` FROM `uls_competency_position_requirements`) p on ac.position_id=p.comp_position_id
			left join (select comp_def_id,comp_def_name,comp_def_category from uls_competency_definition group by comp_def_id)b on b.comp_def_id=p.comp_position_competency_id
			left join (select scale_id,scale_name from uls_level_master_scale group by scale_id)s on s.scale_id=p.comp_position_level_scale_id
			left join(SELECT `pos_comp_temp_id`,`val_id`,`position_id`,`employee_id`,`required_process`,`competency_id`,`require_scale_id`,`assessed_scale_id`,`reason` FROM `uls_position_competency_temp` where employee_id=".$_SESSION['emp_id']." ) a on a.val_id=ac.val_id and a.position_id=ac.position_id and a.competency_id=p.comp_position_competency_id
			where 1 and ac.parent_org_id=".$CI->session->userdata('parent_org_id')." and b.comp_def_category=".$cat_id." and ac.val_pos_id=".$val_pos_id."  and ac.val_id=".$val_id." and ac.position_id=".$pos_id." order by ac.val_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	
	static function get_self_validation_kra_summary($val_id,$pos_id,$val_pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($val_id) && is_numeric($val_id)){
			$query="SELECT p.`comp_kra_id` as kra_id,p.`comp_position_id`,p.`comp_kra_dimensions`,p.`comp_kra_steps`,p.`kra_kri`,p.`kra_uom`,a.`pos_kra_temp_id`,a.`val_id`,a.`position_id`,a.`employee_id`,a.`required_process`,a.`comp_kra_id`,a.`reason`,s.kra_master_name FROM `uls_validation_positions` ac 
			left join(SELECT `comp_kra_id`,`comp_position_id`,`comp_kra_dimensions`,`comp_kra_steps`,`kra_kri`,`kra_uom` FROM `uls_competency_position_requirements_kra`) p on ac.position_id=p.comp_position_id
			left join (SELECT `kra_master_id`,`kra_master_name` FROM `uls_kra_masters`)s on s.kra_master_id=p.comp_kra_steps
			left join(SELECT `pos_kra_temp_id`,`val_id`,`position_id`,`employee_id`,`required_process`,`comp_kra_id`,`reason` FROM `uls_position_kra_temp` where employee_id=".$_SESSION['emp_id']." ) a on a.val_id=ac.val_id and a.position_id=ac.position_id and a.comp_kra_id=p.comp_kra_id
			where 1 and ac.parent_org_id=".$CI->session->userdata('parent_org_id')." and ac.val_pos_id=".$val_pos_id."  and ac.val_id=".$val_id." and ac.position_id=".$pos_id." order by ac.val_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	
	static function get_admin_validation_position($val_id,$pos_id,$val_pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($val_id) && is_numeric($val_id)){
			$query="select b.full_name, b.employee_number, b.org_name, b.position_name,b.location_name, a.*,c.`pos_temp_id`,c.`val_id`,c.`position_id`,c.`employee_id`,c.`accountabilities`,c.`responsibilities` from uls_validation_position_employees a
			left join (select employee_id,full_name,employee_number,org_name,position_name,location_name from employee_data group by employee_id)b on b.employee_id=a.employee_id
			left join(SELECT `pos_temp_id`,`val_id`,`position_id`,`employee_id`,`accountabilities`,`responsibilities` FROM `uls_position_temp`) c on a.val_id=c.val_id and  a.position_id=c.position_id and a.employee_id=c.employee_id
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.val_pos_id=".$val_pos_id." and a.position_id=".$pos_id." and a.val_id=".$val_id." order by a.val_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function getemployeecompetency($val_id,$pos_id,$comp_id,$emp_id){
		$query="SELECT rs.scale_name as ass_scale_name,r.value_name as req_process,a.* FROM `uls_position_competency_temp` a
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)r ON master_code = 'VAL_REQUIRE' AND a.required_process = r.value_code
		left join (select scale_id,scale_name from uls_level_master_scale group by scale_id)rs on rs.scale_id=a.assessed_scale_id
		WHERE `val_id`=$val_id and `position_id`=$pos_id and `competency_id`=$comp_id and employee_id=$emp_id";
		$compdef=UlsMenu::callpdorow($query);
		return $compdef;
	}
	
	static function get_admin_validation_competencies_summary($val_id,$pos_id,$val_pos_id,$cat_id,$emp_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($val_id) && is_numeric($val_id) && is_numeric($emp_id)){
			$query="SELECT p.`comp_position_id`,p.`comp_position_competency_id`,p.`comp_position_level_id`,p.`comp_position_level_scale_id`,b.comp_def_id,b.comp_def_name,s.scale_name,s.scale_id,a.`pos_comp_temp_id`,a.`val_id`,a.`position_id`,a.`employee_id`,r.value_name as req_process,a.`competency_id`,a.`require_scale_id`,a.`assessed_scale_id`,a.`reason`,rs.scale_name as ass_scale_name FROM `uls_validation_positions` ac 
			left join(SELECT `comp_position_req_id`,`comp_position_id`,`comp_position_competency_id`,`comp_position_level_id`,`comp_position_level_scale_id`,`comp_position_criticality_id` FROM `uls_competency_position_requirements`) p on ac.position_id=p.comp_position_id
			left join (select comp_def_id,comp_def_name,comp_def_category from uls_competency_definition group by comp_def_id)b on b.comp_def_id=p.comp_position_competency_id
			left join (select scale_id,scale_name from uls_level_master_scale group by scale_id)s on s.scale_id=p.comp_position_level_scale_id
			left join(SELECT `pos_comp_temp_id`,`val_id`,`position_id`,`employee_id`,`required_process`,`competency_id`,`require_scale_id`,`assessed_scale_id`,`reason` FROM `uls_position_competency_temp` where employee_id=".$emp_id." ) a on a.val_id=ac.val_id and a.position_id=ac.position_id and a.competency_id=p.comp_position_competency_id
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)r ON master_code = 'VAL_REQUIRE' AND a.required_process = r.value_code 
			left join (select scale_id,scale_name from uls_level_master_scale group by scale_id)rs on rs.scale_id=a.assessed_scale_id
			where 1 and ac.parent_org_id=".$CI->session->userdata('parent_org_id')." and b.comp_def_category=".$cat_id." and ac.val_pos_id=".$val_pos_id."  and ac.val_id=".$val_id." and ac.position_id=".$pos_id." order by ac.val_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function get_admin_validation_kra_summary($val_id,$pos_id,$val_pos_id,$emp_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($val_id) && is_numeric($val_id) && is_numeric($emp_id)){
			$query="SELECT p.`comp_kra_id` as kra_id,p.`comp_position_id`,p.`comp_kra_dimensions`,p.`comp_kra_steps`,p.`kra_kri`,p.`kra_uom`,a.`pos_kra_temp_id`,a.`val_id`,a.`position_id`,a.`employee_id`,r.value_name as req_process,a.`comp_kra_id`,a.`reason`,s.kra_master_name FROM `uls_validation_positions` ac 
			left join(SELECT `comp_kra_id`,`comp_position_id`,`comp_kra_dimensions`,`comp_kra_steps`,`kra_kri`,`kra_uom` FROM `uls_competency_position_requirements_kra`) p on ac.position_id=p.comp_position_id
			left join (SELECT `kra_master_id`,`kra_master_name` FROM `uls_kra_masters`)s on s.kra_master_id=p.comp_kra_steps
			left join(SELECT `pos_kra_temp_id`,`val_id`,`position_id`,`employee_id`,`required_process`,`comp_kra_id`,`reason` FROM `uls_position_kra_temp` where employee_id=".$emp_id." ) a on a.val_id=ac.val_id and a.position_id=ac.position_id and a.comp_kra_id=p.comp_kra_id
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)r ON master_code = 'VAL_REQUIRE' AND a.required_process = r.value_code 
			where 1 and ac.parent_org_id=".$CI->session->userdata('parent_org_id')." and ac.val_pos_id=".$val_pos_id."  and ac.val_id=".$val_id." and ac.position_id=".$pos_id." order by ac.val_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function get_position_validation_kra_summary($val_id,$pos_id,$kra,$emp_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($val_id) && is_numeric($val_id) && is_numeric($emp_id)){
			$query="SELECT r.value_name as req_process, a.`pos_kra_temp_id`, a.`val_id`, a.`position_id`, a.`employee_id`, a.`comp_kra_id`, a.`reason` FROM `uls_position_kra_temp` a  
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)r ON master_code = 'VAL_REQUIRE' AND a.required_process = r.value_code 
			where 1 and a.employee_id=".$emp_id." and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.val_id=".$val_id." and a.comp_kra_id=".$kra." and a.position_id=".$pos_id;
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
}