<?php

/**
 * UlsPositionKraArchive
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsPositionKraArchive extends BaseUlsPositionKraArchive
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
		$this->created_by=$CI->session->userdata('username');
		$this->created_date=date('Y-m-d');
		$this->modified_by=$CI->session->userdata('username');
		$this->modified_date=date('Y-m-d');
		$this->last_modified_id=$CI->session->userdata('user_id');
	}

	function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
		$this->modified_date=date('Y-m-d');
		$this->modified_by=$CI->session->userdata('username');
		$this->last_modified_id=$CI->session->userdata('user_id');
	}
	
	static function getcompetencypositionrequirementskra_arc($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.* from uls_position_kra_archive a
			where 1 and a.comp_position_id=$id";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function getcompetencypositionrequirementskra($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.kra_master_name as kra_master_name,a.* from uls_position_kra_archive a
			left join (select kra_master_id,kra_master_name from uls_kra_masters group by kra_master_id)b 
			on b.kra_master_id=a.comp_kra_steps 
			where 1 and a.comp_position_id=$id order by b.kra_master_name asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
}