<?php

/**
 * UlsPositionArchive
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsPositionArchive extends BaseUlsPositionArchive
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
	    if($this->status=='A')
		{
		$this->start_date_active=date('Y-m-d');
		$this->end_date_active=NULL;
		}
		if($this->status=='I')
		{
		$this->start_date_active=date('Y-m-d');
		$this->end_date_active=date('Y-m-d');
		}
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
         $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
	    if($this->status=='A')
		{
		$this->start_date_active=date('Y-m-d');
		$this->end_date_active=NULL;
		}
		if($this->status=='I')
		{
		$this->start_date_active=date('Y-m-d');
		$this->end_date_active=date('Y-m-d');
		}
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
		 $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
	static function pos_archive($pos_id){
        if(!empty($pos_id)){
			$CI =& get_instance();
			$CI->load->library('session');
			$org_positions=Doctrine_Query::Create()->from('UlsPositionArchive')->where("position_id=".$pos_id." and parent_org_id=".$CI->session->userdata('parent_org_id'))->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
			return $org_positions;            
        }        
    }
	
	static function searchcount($pos_name="",$position_type="",$department="",$location=""){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq="";
        $sq.=!empty($pos_name)? " and a.position_name like '%$pos_name%'":"";
		$sq.=!empty($position_type)? " and a.position_type='$position_type'":"";
		$sq.=!empty($department)? " and a.position_org_id='$department'":"";
		$sq.=!empty($location)? " and a.location_id in ('$location')":"";
		$query="SELECT count(*) as numcount FROM `uls_position_archive` a
		LEFT JOIN (SELECT organization_id, parent_org_id, org_name FROM uls_organization_master GROUP BY organization_id)b ON b.organization_id = a.`position_org_id`
		LEFT JOIN ( SELECT location_id,location_name FROM uls_location)l ON find_in_set(l.location_id,a.location_id)>0 
		LEFT JOIN (SELECT organization_id, org_name FROM uls_organization_master GROUP BY organization_id)c ON b.parent_org_id = c.organization_id
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')."  ". $sq;
        $locations=UlsMenu::callpdorow($query);
		return $locations['numcount'];
    }
    
    static function search($start, $limit,$pos_name="",$position_type="",$department="",$location=""){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq="";
        $sq.=!empty($pos_name)? " and a.position_name like '%$pos_name%'":"";
		$sq.=!empty($position_type)? " and a.position_type='$position_type'":"";
		$sq.=!empty($department)? " and a.position_org_id='$department'":"";
		$sq.=!empty($location)? " and a.location_id in ('$location')":"";
		$query="SELECT g.value_name as position_type, d.value_name, c.org_name as postion_parent_org_name, b.org_name as position_org_name, a.*,e.conp_profile,f.kra,group_concat(l.location_name) as loc_name FROM `uls_position_archive` a
		LEFT JOIN (SELECT organization_id, parent_org_id, org_name FROM uls_organization_master GROUP BY organization_id)b ON b.organization_id = a.`position_org_id`
		LEFT JOIN (SELECT organization_id, org_name FROM uls_organization_master GROUP BY organization_id)c ON b.parent_org_id = c.organization_id
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)d ON d.master_code = 'STATUS' AND a.status = d.value_code 
		left join(SELECT count(*) as conp_profile,`comp_position_id` FROM `uls_position_competency_archive` where 1 group by comp_position_id) e on a.position_id=e.comp_position_id
		left join(SELECT count(*) as kra,`comp_position_id` FROM `uls_position_kra_archive` where 1 group by comp_position_id) f on a.position_id=f.comp_position_id
		LEFT JOIN ( SELECT location_id,location_name FROM uls_location)l ON find_in_set(l.location_id,a.location_id)>0 
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)g ON g.master_code = 'POSTYPE' AND a.position_type = g.value_code 
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq group by a.position_id  order by a.position_name asc limit $limit offset $start";
		$locations=UlsMenu::callpdo($query);
        return $locations;
    }
	
	
	static function viewposition($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT group_concat(distinct(f.location_name)) as location_name,c.org_name as position_org_name, b. value_name,group_concat(distinct(d.position_name)) as reportsto,group_concat(distinct(e.position_name)) as reportees_name, g.grade_name, h.org_name as bu_name,p.org_name as parent_organisation, a. * FROM `uls_position_archive` a 
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON master_code = 'STATUS' AND a.status = b.value_code 
		LEFT JOIN (SELECT organization_id, org_name FROM uls_organization_master where org_type='DEPART' GROUP BY organization_id)c ON c.organization_id = a.position_org_id
		LEFT JOIN (SELECT organization_id, org_name FROM uls_organization_master where org_type='PO' GROUP BY organization_id)p ON p.organization_id = a.parent_org_id
		LEFT JOIN (SELECT location_id, location_name FROM uls_location GROUP BY location_id)f ON find_in_set(f.location_id,a.location_id)>0
		LEFT JOIN (SELECT position_id, position_name FROM uls_position_archive group by position_id)d ON find_in_set(d.position_id,a.reports_to)>0
		left join (select position_id, position_name from uls_position_archive group by position_id)e on find_in_set(e.position_id,a.reportees)>0
		LEFT JOIN (SELECT grade_id, grade_name FROM uls_grade GROUP BY grade_id)g ON g.grade_id = a.grade_id
		LEFT JOIN (SELECT organization_id, org_name FROM uls_organization_master where org_type='BU' GROUP BY organization_id)h ON h.organization_id = a.bu_id
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.position_id=$id";
		$role=UlsMenu::callpdorow($query);
		return $role;		
	}
}