<?php

/**
 * UlsQuestionnaireCompetency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsQuestionnaireCompetency extends BaseUlsQuestionnaireCompetency
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	static function view_questionnaire_comp($id,$ques_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select c.`ques_comp_id`,c.`ques_id`,c.`ques_competency_id`,c.`ques_level_scale_id`,cd.`comp_def_id`,cd.`comp_def_name`,s.`scale_id`,s.`scale_name` from uls_competency_position_requirements a
			left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) cd on cd.comp_def_id=a.comp_position_competency_id
			left join(SELECT `scale_id`,`scale_number`,`scale_name` FROM `uls_level_master_scale`) s on s.scale_id=a.comp_position_level_scale_id
			LEFT JOIN (SELECT `ques_comp_id`,`ques_id`,`ques_competency_id`,`ques_level_scale_id` FROM `uls_questionnaire_competency` where ques_id=".$ques_id.")c ON c.ques_competency_id = a.comp_position_competency_id
			where 1 and a.comp_position_id=$id";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function view_questionnaire_comp_details($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select cd.`comp_def_name`,s.`scale_name` from uls_questionnaire_competency a
			left join(SELECT `comp_def_id`,`comp_def_name` FROM `uls_competency_definition`) cd on cd.comp_def_id=a.ques_competency_id
			left join(SELECT `scale_id`,`scale_number`,`scale_name` FROM `uls_level_master_scale`) s on s.scale_id=a.ques_level_scale_id
			where 1 and a.ques_id=$id";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
}