<?php

/**
 * UlsQuestionbank
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsQuestionbank extends BaseUlsQuestionbank
{  
    
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');  
	    if($this->active_flag=='P'){
			$this->start_date_active=date('Y-m-d');
			$this->end_date_active=NULL;
		}
		if($this->active_flag=='N'){
			$this->start_date_active=date('Y-m-d');
			$this->end_date_active=date('Y-m-d');
		}
		$this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
	    if($this->active_flag=='P'){
			$this->start_date_active=date('Y-m-d');
			$this->end_date_active=NULL;
		}
		if($this->active_flag=='N'){
			$this->start_date_active=date('Y-m-d');
			$this->end_date_active=date('Y-m-d');
		}
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
    
	public static function searchcount($question_bank,$qtype){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq="";
        $sq=!empty($question_bank)? " and a.name like '%$question_bank%'":"";
		$sq.=!empty($qtype)? " and a.type='$qtype'":" and (a.type='COMP_TEST' || a.type='COMP_INTERVIEW')";
		$query="SELECT count(*) as numcount FROM uls_questionbank a
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON master_code = 'PUBLISH_STATUS' AND a.active_flag = b.value_code 
		LEFT JOIN (SELECT count(*) as questioncount, question_bank_id FROM uls_questions GROUP BY question_bank_id)c ON c.question_bank_id = a.question_bank_id 
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.active_flag='P' $sq ";
		$masterlist=UlsMenu::callpdorow($query);		
		return $masterlist['numcount'];
    }
    
    public static function search($start, $limit,$question_bank,$qtype){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq="";
        $sq.=!empty($question_bank)? " and a.name like '%$question_bank%'":"";
		$sq.=!empty($qtype)? " and a.type='$qtype'":" and (a.type='COMP_TEST' || a.type='COMP_INTERVIEW')";
		$query="SELECT c.questioncount,b.value_name as publish_status,d.value_name as ass_type, a. * FROM uls_questionbank a
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'PUBLISH_STATUS' AND a.active_flag = b.value_code 
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)d ON d.master_code = 'ASSESSMENT_TYPE' AND a.type = d.value_code 
		LEFT JOIN (SELECT count(*) as questioncount, question_bank_id FROM uls_questions GROUP BY question_bank_id)c ON c.question_bank_id = a.question_bank_id 
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.active_flag='P' $sq  order by a.name ASC  limit $limit offset $start";
		$masterlist=UlsMenu::callpdo($query);
        return $masterlist;
    }
	
	static function get_questionbank(){
		$CI =& get_instance();
		$CI->load->library('session'); 
		$group=Doctrine_Query::Create()->from('UlsQuestionbank')->where("parent_org_id=".$CI->session->userdata('parent_org_id'))->execute();
		return $group;
	}
	
	static function get_questionbank_id($id){
		$CI =& get_instance();
		$CI->load->library('session'); 
		$group=Doctrine_Query::Create()->from('UlsQuestionbank')->where('question_bank_id='.$id." and parent_org_id=".$CI->session->userdata('parent_org_id'))->fetchOne();
		return $group;
	}
	
	static function get_questionbank_id_deatils($id){
		$CI =& get_instance();
		$CI->load->library('session'); 
		$group=Doctrine_Query::Create()->from('UlsQuestionbank')->where('question_bank_id='.$id." and parent_org_id=".$CI->session->userdata('parent_org_id'))->fetchOne();
		return $group;
	}
	
	static function view_questionbank($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.value_name as comp_def_status,d.value_name as types,a.*,c.comp_def_name from uls_questionbank a
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'PUBLISH_STATUS' AND a.active_flag = b.value_code
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)d ON d.master_code = 'ASSESSMENT_TYPE' AND a.type = d.value_code
			LEFT JOIN (SELECT comp_def_id, comp_def_name FROM uls_competency_definition GROUP BY comp_def_id)c ON a.comp_def_id = c.comp_def_id
			where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.question_bank_id=$id";
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
	
	static function get_questions_data($id){
		$CI =& get_instance();
		$CI->load->library('session'); 
		$query="select a.question_bank_id, a.question_id as id,a.question_name as question_name,a.question_type as question_type,a.points,b.correct_flag as correct_flag ,b.text as text,b.explanation from uls_questions a"
		. "  Left Join(select question_id,correct_flag,text,explanation from uls_question_values group by value_id )b on a.question_id=b.question_id "
		. " where a.question_bank_id=".$id." and a.question_id=b.question_id and  a.parent_org_id=".$CI->session->userdata('parent_org_id');
		$group=UlsMenu::callpdo($query);
		return $group;
	}
	
	static function get_questionbank_form_question($id){
		$CI =& get_instance();
		$CI->load->library('session'); 
		$qbank=Doctrine_Query::Create()->select('question_bank_id')->from('UlsQuestions')->where('question_id='.$id." and parent_org_id=".$CI->session->userdata('parent_org_id'))->fetchOne();
		
		return $qbank;
	}
	
	//Funciton to get all the question banks based on parent org id....
	static function questionbanks($bankid){
		$question_bank=Doctrine_Query::Create()->from('UlsQuestionbank')->where("parent_org_id=".$bankid." and type in ('COMP_TEST','COMP_INTERVIEW')")->orderBy("name asc")->execute();
		return $question_bank;
	}
	
	static function get_questionbank_comp($id,$code){
		$CI =& get_instance();
		$CI->load->library('session');
		$group=array();
		if(!empty($id)){
			$query="select a.* from uls_questionbank a where a.comp_def_id=".$id." and a.type='".$code."' and a.parent_org_id=".$CI->session->userdata('parent_org_id');
			$group=UlsMenu::callpdo($query);
		}
		
		return $group;
	}
	
	static function get_questions_data_levels($id,$scale_id,$add_scale_id=""){
		$CI =& get_instance();
		$CI->load->library('session');
		if(empty($add_scale_id)){
			$scale="a.scale_id=".$scale_id;
		}
		else{
			$scale="a.scale_id in (".$scale_id.",".$add_scale_id.")";
		}
		//$q_count=!empty($que_count)?"LIMIT ".$que_count."":"";
		$query="select a.question_bank_id, a.question_id as id,a.question_name as question_name,a.question_type as question_type,a.points from uls_questions a"
		. " where a.question_bank_id=".$id." and $scale and a.parent_org_id=".$CI->session->userdata('parent_org_id');
		$group=UlsMenu::callpdo($query);
		return $group;
	}
	
	static function get_questions_data_level_comp($id,$scale_id,$comp_id){
		$CI =& get_instance();
		$CI->load->library('session'); 
		$query="select a.question_bank_id, a.question_id as id,a.question_name as question_name,a.question_type as question_type,a.points from uls_questions a
		left join(SELECT `question_bank_id`,`comp_def_id`,`name` FROM `uls_questionbank`) b on a.question_bank_id=b.question_bank_id
		where a.question_bank_id =".$id." and a.scale_id=".$scale_id." and b.comp_def_id=".$comp_id." and a.parent_org_id=".$CI->session->userdata('parent_org_id');
		$group=UlsMenu::callpdo($query);
		return $group;
	}
	

	
	static function get_questions_data_inbasket($id){
		$CI =& get_instance();
		$CI->load->library('session'); 
		$query="select a.question_bank_id, a.question_id as id,a.question_name as question_name,a.question_type as question_type,a.points,b.inbasket_id from uls_questions a
		left join(SELECT `question_bank_id`,`comp_def_id`,`name`,inbasket_id FROM `uls_questionbank`) b on a.question_bank_id=b.question_bank_id
		where b.inbasket_id =".$id." and a.parent_org_id=".$CI->session->userdata('parent_org_id');
		$group=UlsMenu::callpdorow($query);
		return $group;
	}
	
	static function get_questionbank_casestudy($code){
		$CI =& get_instance();
		$CI->load->library('session');
		$group=array();
		if(!empty($code)){
			$query="select a.* from uls_questionbank a where a.type='".$code."' and a.parent_org_id=".$CI->session->userdata('parent_org_id');
			$group=UlsMenu::callpdo($query);
		}
		
		return $group;
	}
	
	static function get_questions_level($id){
		$CI =& get_instance();
		$CI->load->library('session'); 
		$query="SELECT a.`question_bank_id`,a.`comp_def_id`,c.level_id,c.level_name FROM `uls_questionbank` a 
		left join(SELECT `comp_def_id`,`comp_def_level` FROM `uls_competency_definition`) b on a.comp_def_id=b.comp_def_id
		left join(SELECT `level_id`,`level_name` FROM `uls_level_master`) c on b.comp_def_level=c.level_id
		WHERE a.`question_bank_id`=".$id;
		$group=UlsMenu::callpdorow($query);
		return $group;
	}
	
	static function get_questions_level_count($id){
		$CI =& get_instance();
		$CI->load->library('session'); 
		$query="SELECT a.`question_bank_id`,a.`comp_def_id`,c.level_id,c.level_name,s.scale_name,s.scale_number,s.scale_id FROM `uls_questionbank` a 
		inner join(SELECT `comp_def_id`,`comp_def_level` FROM `uls_competency_definition`) b on a.comp_def_id=b.comp_def_id
		inner join(SELECT `level_id`,`level_name` FROM `uls_level_master`) c on b.comp_def_level=c.level_id
		inner join(SELECT `scale_id`,`scale_name`,scale_number,level_id FROM `uls_level_master_scale`)s on s.level_id=c.level_id
		WHERE a.`question_bank_id` in (".$id.") ORDER BY  s.scale_number ASC ";
		$group=UlsMenu::callpdo($query);
		return $group;
	}
	
	static function get_questions_inbasket_level_count($id){
		$CI =& get_instance();
		$CI->load->library('session'); 
		$query="SELECT q.`q_id`,b.`comp_def_id`,c.level_id,c.level_name,s.scale_name,s.scale_number,s.scale_id FROM `uls_competency_definition` b left join(SELECT `level_id`,`level_name` FROM `uls_level_master` ) c on b.comp_def_level=c.level_id left join(SELECT `scale_id`,`scale_name`,scale_number,level_id FROM `uls_level_master_scale`)s on s.level_id=c.level_id left join(SELECT count(`question_id`) as q_id,`comp_def_id`,`scale_id` FROM `uls_question_values` group by scale_id,comp_def_id) q on b.comp_def_id=q.comp_def_id and q.scale_id=s.scale_id WHERE b.`comp_def_id`=".$id." ORDER BY s.scale_number ASC";
		$group=UlsMenu::callpdo($query);
		return $group;
	}

	static function get_question_csv($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select d.type_name,s.scale_name,a.question_bank_id, a.question_id as id,a.question_name as question_name,a.question_type as question_type,a.points,a.sequence,a.active_flag from uls_questions a
		left join(SELECT `scale_id`,`scale_name`,scale_number FROM `uls_level_master_scale` group by scale_id)s on s.scale_id=a.scale_id
		left join(SELECT type_flag,type_name FROM `uls_questions_type` group by type_id)d on a.question_type=d.type_flag
		where a.question_bank_id=".$id." and a.parent_org_id=".$CI->session->userdata('parent_org_id');
		$group=UlsMenu::callpdo($query);
		return $group;
	}
	
	static function get_answer_csv($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select * from uls_question_values where question_id in (select question_id from uls_questions where question_bank_id=".$id." and parent_org_id=".$CI->session->userdata('parent_org_id').")";
		$group=UlsMenu::callpdo($query);
		return $group;
	}
	
	static function get_questions_data_pdf($id){
		$CI =& get_instance();
		$CI->load->library('session'); 
		//left join(SELECT `scale_id`,`scale_name`,scale_number FROM `uls_level_master_scale` group by scale_id)s on s.scale_id=a.scale_ids.scale_name,
		$query="select a.question_bank_id, a.question_id as id,a.question_name as question_name,a.question_type as question_type,a.points,b.correct_flag as correct_flag ,b.text as text,b.explanation from uls_questions a
		Left Join(select question_id,correct_flag,text,explanation from uls_question_values group by value_id )b on a.question_id=b.question_id
		
		where a.question_bank_id=".$id." and a.parent_org_id=".$CI->session->userdata('parent_org_id');
		$group=UlsMenu::callpdo($query);
		return $group;
	}
	
	static function get_questions_report($id,$limit){
		$CI =& get_instance();
		$CI->load->library('session'); 
		$query="select a.question_bank_id, a.question_id as id,a.question_name as question_name,a.question_type as question_type,a.points from uls_questions a"
		
		. " where a.question_id in (".$id.") and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." limit 0,".$limit;
		$group=UlsMenu::callpdo($query);
		return $group;
	}
	
	static function get_questions_scale_count($comp_id,$scale_id){
		$CI =& get_instance();
		$CI->load->library('session'); 
		$query="select a.question_bank_id, a.question_id as id,a.question_name as question_name,a.question_type as question_type,a.points from uls_questions a
		left join(SELECT `question_bank_id`,`comp_def_id`,`name` FROM `uls_questionbank`) b on a.question_bank_id=b.question_bank_id
		where a.scale_id=".$scale_id." and b.comp_def_id=".$comp_id." and a.parent_org_id=".$CI->session->userdata('parent_org_id');
		$group=UlsMenu::callpdo($query);
		return $group;
	}
}