<?php

/**
 * UlsQuestions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsQuestions extends BaseUlsQuestions
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
		if($this->active_flag=='P'){
			$this->start_date_active=date('Y-m-d');
			$this->end_date_active=NULL;
		}
		if($this->active_flag=='N'){
			$this->start_date_active=date('Y-m-d');
			$this->end_date_active=date('Y-m-d');
		}
		$this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
	function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
		if($this->active_flag=='P'){
			$this->start_date_active=date('Y-m-d');
			$this->end_date_active=NULL;
		}
		if($this->active_flag=='N'){
			$this->start_date_active=date('Y-m-d');
			$this->end_date_active=date('Y-m-d');
		}
		$this->modified_date=date('Y-m-d');
		$this->modified_by=$CI->session->userdata('username');
		$this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	public static function searchcount($question_name,$id){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq=!empty($question_name)? " and a.question_name like '%$question_name%'":"";
		$query="SELECT count(*) as numcount FROM uls_questions a
		WHERE 1 and  a.question_bank_id=".$id." and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq ";
		$masterlist=UlsMenu::callpdorow($query);
		return $masterlist['numcount'];
	}
	
	public static function search($start, $limit,$question_bank,$id){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq=!empty($question_bank)? " and a.question_name like '%$question_bank%'":"";
		$query="SELECT c.questioncount,b.value_name as publish_status, a. * FROM uls_questionbank a
		WHERE 1 and  a.question_bank_id=".$id." and a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq limit $limit offset $start";
		$masterlist=UlsMenu::callpdo($query);
		return $masterlist;
	}
	
	static function get_allquestions($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select  a.question_id as qid,a.question_name as qname,a.start_date_active as stdate,a.points as points,a.end_date_active as endate,a.active_flag,b.type_name as qtype,c.scale_name  FROM uls_questions a, uls_questions_type b, uls_level_master_scale c where( a.question_type=b.type_flag  and a.scale_id=c.scale_id and a.parent_org_id=".$CI->session->userdata('parent_org_id')."  and a.question_bank_id=".$id.")";
		return UlsMenu::callpdo($query);
	}
	
	static function get_activequestions($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select  a.question_id as qid,a.question_name as qname,a.start_date_active as stdate,a.points as points,a.end_date_active as endate,b.type_name as qtype  FROM uls_questions a, uls_questions_type b where( a.question_type=b.type_flag and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.active_flag='P' and ((CURDATE() BETWEEN start_date_active AND end_date_active) or (start_date_active <= CURDATE() and end_date_active is null)) and a.question_bank_id=".$id.")";
		return UlsMenu::callpdo($query);
	}
	
	public static function get_questions($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select a.question_bank_id as bid,a.question_id as qid,a.points as points,a.question_category as quest_cat, a.question_type as type,a.sequence as sequence, a.question_name as qname,a.points as points,a.active_flag as publish,a.start_date_active as stdate,a.end_date_active as endate,b.type_name as qtype,b.type_id as tid,a.multi_language,a.level_id,a.scale_id  FROM uls_questions a, uls_questions_type b where( a.question_type=b.type_flag and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.question_id=".$id.")";
		return UlsMenu::callpdorow($query);
	}
	
	public static function get_question_vlaues($id){
		$dd=Doctrine_Query::Create()->from('UlsQuestionValues')->where('question_id='.$id)->execute();
		return $dd;
	}
	
	public static function get_questins_fortest(){
		$CI =& get_instance();
		$CI->load->library('session');
		$dd=Doctrine_Query::Create()->from('UlsQuestions')->where('parent_org_id='.$CI->session->userdata('parent_org_id'))->execute();
		return $dd;
	}
	
	public static function get_selectd_questions($ids){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select  a.question_id as qid,a.question_name as qname,a.start_date_active as stdate,a.end_date_active as endate,a.points as points,b.type_name as qtype  FROM uls_questions a, uls_questions_type b where( a.question_type=b.type_flag and a.question_id in (".$ids.") and a.parent_org_id=".$CI->session->userdata('parent_org_id')." )";
		return UlsMenu::callpdo($query); 
	}
	
	public static function get_questions_view($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select question_name as qname, question_type as type,question_bank_id as id FROM uls_questions  where(question_id=".$id."  and parent_org_id=".$CI->session->userdata('parent_org_id')." )";
		return UlsMenu::callpdo($query);
	}
	
	public static function get_questions_view_vlaues($id){
		$query="select correct_flag as flag, text as options FROM uls_question_values  where(question_id=".$id.")";
		return UlsMenu::callpdo($query);
	}
	
	//Functions for Test Data Migration
	static function questionsformigration($quest_type,$quest_name,$parent_id,$questionbank,$scale_id){
		if(!empty($quest_type) && !empty($quest_name)){
			$trimed_questtype=str_replace(' ','',$quest_type);
			$trimed_questname=str_replace(' ','',$quest_name);
			$quest_query="select q.question_id from uls_questions q where q.parent_org_id=".$parent_id." and q.question_bank_id=".$questionbank." and q.scale_id=".$scale_id." and REPLACE(q.question_name,' ','')='".$trimed_questname."' and REPLACE(q.question_type,' ','')='".$quest_type."'";
			return UlsMenu::callpdo($quest_query);
		}
	}
	
	static function quest_valuesmigration($answer,$option1,$option2,$option3,$parent_id,$questid){
		if(!empty($questid)){
			// $trimed_catname=str_replace(' ','',$catname);
			// $trimed_progname=str_replace(' ','',$progname);
			// $prog_query="select c.category_id, p.program_id from uls_category c
			// LEFT JOIN (select program_id, category_id, program_name from uls_program) p ON p.category_id=c.category_id and REPLACE(p.program_name,' ','')='".$trimed_progname."'
			// where REPLACE(c.name,' ','')='".$trimed_catname."' and c.parent_org_id=".$parent_id."";
			// return UlsMenu::callpdo($prog_query);
		 }
	}
	//End of data migrations
	
	//Function to get last record of questionnaire
	public static function last_questionnaire(){
		if(isset($_REQUEST['id']) && isset($_REQUEST['type'])){
			if($_REQUEST['type']=='PROG_EVAL'){
				$data="select question_id, question_name from uls_questions where question_bank_id=".$_REQUEST['id'];
				return UlsMenu::callpdo($data);
			}
		}
	}
	
	public static function get_questions_new($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select a.question_bank_id as bid,a.question_bank_id as qid,a.points as points,a.question_category as quest_cat, a.question_type as type,a.sequence as sequence, a.question_name as qname,a.question_type as qtype,a.points as points,a.active_flag as publish,a.start_date_active as stdate,a.end_date_active as endate,b.type_name as qtype,b.type_id as tid  FROM uls_questions a, uls_questions_type b where( a.question_type=b.type_flag and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.question_id=".$id.")";    
		return UlsMenu::callpdorow($query);
	}
	
	public static function get_questions_count_comp($c_id,$limit,$s_id,$type){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT b.question_id as ques_id,b.question_name FROM `uls_questionbank` a
		left join(SELECT `question_id`,`question_bank_id`,`scale_id`,question_name FROM `uls_questions`) b on a.`question_bank_id`=b.`question_bank_id`
		where a.comp_def_id=".$c_id." and b.scale_id=".$s_id." and a.type='".$type."' limit $limit" ;    
		return UlsMenu::callpdo($query);
	}
	
	public static function get_questions_count($c_id,$type,$s_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT count(b.question_id) as test_count FROM `uls_questionbank` a
		left join(SELECT `question_id`,`question_bank_id`,`scale_id`,question_name FROM `uls_questions`) b on a.`question_bank_id`=b.`question_bank_id`
		where a.comp_def_id=".$c_id." and b.scale_id=".$s_id." and a.type='".$type."'";    
		return UlsMenu::callpdorow($query);
	}
}