<?php

/**
 * UlsQuestionValues
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsQuestionValues extends BaseUlsQuestionValues
{
	function preInsert($event){
	     $CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	static function get_allquestion_values($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select  a.* FROM uls_question_values a where(a.parent_org_id=".$CI->session->userdata('parent_org_id')."  and a.question_id=".$id.")";
        return UlsMenu::callpdo($query);
	}
	
	static function get_allquestion_values_competency($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select  a.*,e.comp_def_name,e.comp_def_name_alt,l.scale_name FROM uls_question_values a
		LEFT JOIN (SELECT comp_def_id, comp_def_name,comp_def_name_alt FROM uls_competency_definition GROUP BY comp_def_id)e ON a.comp_def_id = e.comp_def_id
		LEFT JOIN(SELECT `scale_id`,`scale_number`,`level_id`,`scale_name` FROM `uls_level_master_scale`)l on l.scale_id=a.scale_id
		where(a.parent_org_id=".$CI->session->userdata('parent_org_id')."  and a.question_id=".$id." ) order by a.scorting_order ASC";
        return UlsMenu::callpdo($query);
	}
	
	static function get_allquestion_values_competency_assessor($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select  a.*,e.comp_def_name,l.scale_name FROM uls_question_values a
		LEFT JOIN (SELECT comp_def_id, comp_def_name FROM uls_competency_definition GROUP BY comp_def_id)e ON a.comp_def_id = e.comp_def_id
		LEFT JOIN(SELECT `scale_id`,`scale_number`,`level_id`,`scale_name` FROM `uls_level_master_scale`)l on l.scale_id=a.scale_id
		where(a.parent_org_id=".$CI->session->userdata('parent_org_id')."  and a.question_id=".$id." and a.priority_inbasket is NOT NULL ) order by a.priority_inbasket ASC";
        return UlsMenu::callpdo($query);
	}
	
	static function get_allquestion_values_competency_unique($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT e.comp_def_name,l.scale_name FROM `uls_questionbank` b 
		LEFT JOIN(SELECT `question_id`,`question_bank_id` FROM `uls_questions` ) q on q.`question_bank_id`=b.`question_bank_id`
		LEFT JOIN(SELECT `value_id`,`question_id`,`comp_def_id`,`scale_id`,scorting_order FROM `uls_question_values` group by comp_def_id) a on a.`question_id`=q.`question_id`
		LEFT JOIN (SELECT comp_def_id, comp_def_name FROM uls_competency_definition GROUP BY comp_def_id)e
		 ON a.comp_def_id = e.comp_def_id
		LEFT JOIN(SELECT `scale_id`,`scale_number`,`level_id`,`scale_name` FROM `uls_level_master_scale`)l
		 on l.scale_id=a.scale_id
		where(b.parent_org_id=".$CI->session->userdata('parent_org_id')." and b.inbasket_id=$id) order by a.scorting_order ASC";
        return UlsMenu::callpdo($query);
	}
	
	static function get_allquestion_values_competency_unique_assessor($id,$test_type,$emp_id,$ass_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT e.comp_def_name,l.scale_name,r.report_id,rs.assessed_scale_id,qi.position_id,a.comp_def_id,a.scale_id,e.comp_def_level,qi.inb_assess_test_id FROM `uls_questionbank` b 
		LEFT JOIN(SELECT `question_id`,`question_bank_id` FROM `uls_questions` ) q on q.`question_bank_id`=b.`question_bank_id`
		LEFT JOIN(SELECT `value_id`,`question_id`,`comp_def_id`,`scale_id`,scorting_order FROM `uls_question_values` ) a on a.`question_id`=q.`question_id`
		LEFT JOIN (SELECT comp_def_id, comp_def_name,comp_def_level FROM uls_competency_definition GROUP BY comp_def_id)e
		 ON a.comp_def_id = e.comp_def_id
		LEFT JOIN(SELECT `scale_id`,`scale_number`,`level_id`,`scale_name` FROM `uls_level_master_scale`)l
		 on l.scale_id=a.scale_id
		LEFT join(SELECT inb_assess_test_id,`assess_test_id`,`assessment_pos_id`,`position_id`,`assessment_id`,`inbasket_id`,`assessment_type` FROM `uls_assessment_test_inbasket`) qi on qi.inbasket_id=b.inbasket_id
		left join (select report_id,assessment_id,position_id,competency_id,assessed_scale_id,development_area,employee_id,assessor_id from uls_assessment_report where employee_id=".$emp_id." and assessment_id=".$ass_id." and assessor_id=".$_SESSION['asr_id'].")r on r.assessment_id=qi.assessment_id and r.position_id=qi.position_id and r.competency_id=e.comp_def_id 
		left join (select report_id,assessed_scale_id,assessment_type,inb_assess_test_id from uls_assessment_report_bytype where assessment_type=$test_type and assessment_id=".$ass_id." and inb_assess_test_id=$id)rs on rs.report_id=r.report_id and rs.inb_assess_test_id=qi.inb_assess_test_id
		where(b.parent_org_id=".$CI->session->userdata('parent_org_id')." and qi.inb_assess_test_id=$id) group by a.comp_def_id order by e.comp_def_name ASC";
        return UlsMenu::callpdo($query);
	}
	
	static function get_allquestion_values_delete($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select  a.`value_id`,b.`question_id`,c.`inbasket_id` FROM uls_question_values a
		left join(SELECT `question_id`,`question_bank_id` FROM `uls_questions`) b on a.question_id=b.question_id
		left join(SELECT `question_bank_id`,`inbasket_id` FROM `uls_questionbank`) c on b.question_bank_id=c.question_bank_id
		where a.`value_id`=".$id;
        return UlsMenu::callpdorow($query);
	}
	
	static function get_allquestion_comp_values($comp_id,$scale_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select  a.`value_id`,a.text FROM uls_question_values a
		where a.`comp_def_id`=".$comp_id." and a.scale_id=".$scale_id;
        return UlsMenu::callpdo($query);
	}
	
	static function get_allquestion_values_edit($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select  a.* FROM uls_question_values a
		where a.`value_id`=".$id;
        return UlsMenu::callpdorow($query);
	}
	
	static function get_allquestion_values_inbasket($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select  a.*,e.comp_def_name,l.scale_name,l.scale_id as scale_id FROM uls_question_values a
		LEFT JOIN (SELECT comp_def_id, comp_def_name FROM uls_competency_definition GROUP BY comp_def_id)e ON a.comp_def_id = e.comp_def_id
		LEFT JOIN(SELECT `scale_id`,`scale_number`,`level_id`,`scale_name` FROM `uls_level_master_scale`)l on l.scale_id=a.scale_id
		where a.parent_org_id=".$CI->session->userdata('parent_org_id')."  and a.value_id=".$id." order by e.comp_def_name ASC";
        return UlsMenu::callpdorow($query);
	}
	
	static function get_all_question_values($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select  a.*,e.comp_def_name FROM uls_question_values a
		LEFT JOIN (SELECT comp_def_id, comp_def_name FROM uls_competency_definition GROUP BY comp_def_id)e ON a.comp_def_id = e.comp_def_id
		where a.parent_org_id=".$CI->session->userdata('parent_org_id')."  and a.question_id=".$id." order by e.comp_def_name ASC";
        return UlsMenu::callpdo($query);
	}
}