<?php

/**
 * UlsRatingMaster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsRatingMaster extends BaseUlsRatingMaster
{
	function preInsert($event){
		 $CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_by=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
    }
	
	static function searchcount($level=""){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq=!empty($level)? !empty($sq)? " and a.rating_name like '%".$rating."%'":" and a.rating_name like '%".$rating."%'":"";
		$learning="select count(*) as num_count from uls_rating_master where 1 and  parent_org_id=".$CI->session->userdata('parent_org_id').$sq;
     	$eve=UlsMenu::callpdorow($learning);                
		return $eve['num_count'];
	}
    
    static function search($start,$limit,$rating=""){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq=!empty($level)? !empty($sq)? " and a.rating_name like '%".$rating."%'":" and a.rating_name like '%".$rating."%'":"";
		$learnings="select b.value_name as rating_status, a.* from uls_rating_master a 
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'STATUS' AND a.status = b.value_code 
		where 1 and  a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq limit $limit offset $start";
		$result=UlsMenu::callpdo($learnings);
		return $result;
    }
	
	static function viewrating($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$level=array();
		if(!empty($id) && is_numeric($id)){
			$query="SELECT b.value_name as rating_status, a. * FROM uls_rating_master a 
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'STATUS' AND a.status = b.value_code 
			WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.rating_id=$id";
			$level=UlsMenu::callpdorow($query);
		}
		return $level;
	}
	
	static function rating_details(){
		$CI =& get_instance();
		$CI->load->library('session');
		$level=array();
		$query="SELECT b.value_name as rating_status, a. * FROM uls_rating_master a 
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'STATUS' AND a.status = b.value_code 
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id');
		$level=UlsMenu::callpdo($query);
		return $level;
	}
}