<?php

/**
 * UlsRoleCreation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsRoleCreation extends BaseUlsRoleCreation
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->role_code=strtoupper($this->role_code);
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        //$this->parent_org_id=$_SESSION['parent_org_id'];
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->role_code=strtoupper($this->role_code);
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	static function searchcount($rolename="",$rolecode=""){
        $sq=!empty($rolename)? " and a.role_name like '%$rolename%'":"";
        $sq.=!empty($rolecode)? (!empty($sq)? " and a.role_code like '$rolecode'":" and a.role_code like '$rolecode'"):"";
        $roles= Doctrine_Query::create()->select("count(*) as numcount")->from("UlsRoleCreation a")->where("1 ". $sq)->setHydrationMode(Doctrine::HYDRATE_ARRAY)->fetchOne();
        return $roles['numcount'];
    }
    
    static function search($start, $limit,$rolename="",$rolecode=""){
        $sq=!empty($rolename)? " and a.role_name like '%$rolename%'":"";
        $sq.=!empty($rolecode)? (!empty($sq)? " and a.role_code like '$rolecode'":" and a.role_code like '$rolecode'"):"";
        $roles= UlsMenu::callpdo("select a.*,b.org_name from uls_role_creation a, uls_organization_master b where 1 and a.parent_org_id=b.organization_id $sq limit $limit offset $start");
        foreach($roles as $key=>$role){
            $roles[$key]["start_date"]= date('d-m-Y',strtotime($role["start_date"]));
            $roles[$key]["end_date"]=(($role['end_date']!='') && ($role['end_date']!='NULL'))? date('d-m-Y',strtotime($role["end_date"])):"";
            //$roles[$key]["Organization"]=$role["UlsOrganizationMaster"]["Org_Name"];
            //unset($roles[$key]["UlsOrganizationMaster"]);
        }
        return $roles;
    }
	
	static function viewrole($id){
		$query="SELECT a.role_id, a.`role_name` , a.`role_code` , s.`profile_name` , a.`parent_org_id` , a.`hierarchy_id` , a.`comment` , a.`start_date` , a.`end_date`, b.org_name, ab.org_name as security_org, c.menu_name, d.hierarchy_name FROM `uls_role_creation` a
		LEFT JOIN ( SELECT organization_id, org_name FROM uls_organization_master GROUP BY organization_id)b ON b.organization_id = a.parent_org_id
		LEFT JOIN ( SELECT organization_id, org_name FROM uls_organization_master GROUP BY organization_id)ab ON ab.organization_id = a.security_org
		LEFT JOIN ( SELECT menu_name, menu_creation_id FROM uls_menu_creation GROUP BY menu_creation_id)c ON a.menu_id = c.menu_creation_id
		LEFT JOIN ( SELECT hierarchy_name, hierarchy_id FROM uls_heirarchy_master GROUP BY hierarchy_id)d ON a.hierarchy_id = d.hierarchy_id
		LEFT JOIN ( SELECT secure_profile_id, profile_name FROM uls_security_profile GROUP BY secure_profile_id)s ON s.secure_profile_id = a.secure_profile_id WHERE a.role_id =$id";
		$role=UlsMenu::callpdorow($query);
		return $role;		
	}
	// Function to get all roles under session parent org id written by Nagaraj;
	static function getAllRoles(){
		$CI =& get_instance();
		$CI->load->library('session');
		$role=Doctrine_Query::Create()->from('UlsRoleCreation')->where("parent_org_id=".$CI->session->userdata('parent_org_id'))->execute();
		return $role;
	}
	//Function to get only trainer role for the resource definition based on session parent org id
	static function traRoles(){
		$CI =& get_instance();
		$CI->load->library('session');
		$tras="select r.role_id, r.role_name, group_concat(mn.menu_id) as menu_id from uls_role_creation r
		INNER JOIN uls_menu_creation m on m.menu_creation_id=r.menu_id and m.system_menu_type='tra'
		INNER JOIN uls_menu	mn on mn.menu_creation_id=m.menu_creation_id		
		where r.parent_org_id=".$CI->session->userdata('parent_org_id');
		return UlsMenu::callpdorow($tras);
	}
	
	//Function to get only Assessor role for the resource definition based on session parent org id
	static function assessorRoles(){
		$CI =& get_instance();
		$CI->load->library('session');
		$tras="select r.role_id, r.role_name, group_concat(mn.menu_id) as menu_id from uls_role_creation r
		INNER JOIN uls_menu_creation m on m.menu_creation_id=r.menu_id and m.system_menu_type='asr'
		INNER JOIN uls_menu	mn on mn.menu_creation_id=m.menu_creation_id		
		where r.parent_org_id=".$CI->session->userdata('parent_org_id');
		return UlsMenu::callpdorow($tras);
	}
	
	// Function to get all roles under session parent org id written by Nagaraj;
	static function getspecRoles($id){
		
		$role=Doctrine_Query::Create()->from('UlsRoleCreation')->where("role_id=".$id)->fetchOne();
		return $role;
	}
}