<?php

/**
 * UlsReports
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsReports extends BaseUlsReports
{
	public function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
    public function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	public static function searchcount($report_name){
		$sq=!empty($report_name)? " and a.report_name like '%$report_name%'":"";
		$query="SELECT count(*) as numcount FROM uls_reports a
		WHERE 1 $sq ";
		$testcount=UlsMenu::callpdorow($query);
		return $testcount['numcount'];
	}
	
	public static function search($start, $limit,$report_name){
		$sq=!empty($report_name)? " and a.report_name like '%$report_name%'":"";
		$query="SELECT  b.default_report_name, a. * FROM uls_reports a
		LEFT JOIN (SELECT default_repot_id,default_report_name FROM uls_report_default_report_types GROUP BY
		default_repot_id)b ON b.default_repot_id = a.report_type_id
		WHERE 1  $sq limit $limit offset $start";
		$testdetails=UlsMenu::callpdo($query);
		return $testdetails;
	}
	
	static function get_report_details($id){
		$query=" Select a.*,b.parameter_name,c.default_report_name,d.parameter_name as pname,ad.value_name as stat from uls_reports a 
		Left Join(select report_id,parameter_name,param_code,status from uls_report_parameters group by report_param_id)b on a.report_id=b.report_id 
		Left Join(select default_repot_id,default_report_name  from uls_report_default_report_types group by  default_repot_id )c on c.default_repot_id=a.report_type_id
		Left Join(select parameter_code,default_report_id,parameter_name from uls_report_defaultparameters group by parameter_id )d on b.param_code=d.parameter_code and a.report_type_id=d.default_report_id
		Left Join(select value_code,value_name, master_code from uls_admin_values group by value_id)ad on
		b.status=ad.value_code and master_code like 'REPORT_STATUS' where a.report_id=".$id;
		$details=UlsMenu::callpdo($query);
		return $details;
	}
	
	static function getReporttype(){
		$type=Doctrine_Query::Create()->from('UlsReportDefaultReportTypes')->execute();
		return $type;
	}
	
	static function getallreports(){
		$groups=Doctrine_Query::Create()->select('report_id as id,report_name as name')->from('UlsReports')->execute();
		return $groups;
	}
	
	static function getparamcode(){
		$param=Doctrine_Query::Create()->select('parameter_code as code,parameter_name as name,default_report_id as rid')->from('UlsReportDefaultparameters')->execute();
		return $param;
	}
	
	static function getreportparams(){
		$CI =& get_instance();
		$CI->load->library('session');
		$params1=Doctrine_Query::Create()->select('report_group_id')->from('UlsRoleCreation')->where("parent_org_id=".$CI->session->userdata('parent_org_id')."  and role_id=".$CI->session->userdata('Role_id')." and report_group_id is not null")->fetchOne();
		if(!empty($params1->report_group_id) ){
			$query="select  c.report_name as name,c.report_id as id,a.report_group_id,a.parent_org_id from uls_report_groups a LEFT JOIN(select report_group_id,report_id,visible from uls_report_group_details group by
			report_grp_details_id)b on b.report_group_id=a.report_group_id Left JOIN(select report_name,report_id from uls_reports group by report_id)c on b.report_id=c.report_id where  a.report_group_id=".$params1->report_group_id." and  b.visible='VIS' and a.parent_org_id=".$CI->session->userdata('parent_org_id');
			$params = UlsMenu::callpdo($query);
			return $params;
		}
	}
	
	static function getreportparameters($report_id){
		$query="select b.parameter_name as pname,b.param_code as code ,a.report_id,a.query_name,a.report_type_id from uls_reports a Left Join(select parameter_name,param_code,status,report_param_id,report_id from uls_report_parameters group by report_param_id)b on b.report_id=a.report_id and b.status='VIS' where a.report_id=".$report_id." order by b.report_param_id asc ";
		$params = UlsMenu::callpdo($query);
		return $params;
	}
	
	static function getassessname($ass_type){        
		$prog=Doctrine_Query::Create()->select('assessment_name as name,assessment_id as id')->from('UlsAssessmentDefinition')->where("parent_org_id=".$_SESSION['parent_org_id']." and assessment_cycle_type ='".$ass_type."'")->orderby("assessment_name ASC")->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
		return $prog;        
    }
	
	static function get_re_assessname($ass_type){        
		$prog=Doctrine_Query::Create()->select('assessment_name as name,assessment_id as id')->from('UlsAssessmentDefinition')->where("parent_org_id=".$_SESSION['parent_org_id']." and assessment_cycle_type ='".$ass_type."' and assessment_status='A'" )->orderby("assessment_name ASC")->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
		return $prog;        
    }
	
	
	
	static function getcategories(){
		$prog=Doctrine_Query::Create()->select('name as name,category_id as id')->from('UlsCategory')->where('parent_org_id='.$_SESSION['parent_org_id'].' and category_type <> "PC"')->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
		return $prog;
	}
	
	static function getprograms(){
		$prog=Doctrine_Query::Create()->select('program_name as name,program_id as id')->from('UlsProgram')->where('parent_org_id='.$_SESSION['parent_org_id'])->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
		return $prog;
	}
	
	static function getevents(){
		$CI =& get_instance();
		$CI->load->library('session');
		$roledata=Doctrine_Core::getTable("UlsRoleCreation")->findOneByRole_id($CI->session->userdata('Role_id'));
		$menucreation=Doctrine_Core::getTable("UlsMenuCreation")->findOneByMenu_creation_id($roledata->menu_id);
		//echo $menucreation->system_menu_type;
		if($menucreation->system_menu_type=='mngr'){
			if(!empty($roledata->security_org) and !empty($roledata->hierarchy_id)){
				//echo $roledata->security_org;
				$orgidsdata=UlsOrganizationMaster::getchildorgsdata_report($roledata->security_org);					
				    $orgids=$orgidsdata;
					if(!empty($orgids)){					
					 $query="select b.event_name,b.event_id,a.organization_id from uls_learner_access a Left Join(select event_id,event_name from uls_event_creation group by event_id)b on(a.event_id=b.event_id)
					where organization_id in ($orgids)";
					return UlsMenu::callpdo($query); 
					}
				 }
			else if(!empty($roledata->security_org) and empty($roledata->hierarchy_id)){
					$eventid=UlsEventCreation::secure_event_data();
					if(!empty($eventid)){
					 $eve=Doctrine_Query::Create()->select("event_name,event_id")->from("UlsEventCreation")->where(" event_id in ($eventid) and parent_org_id=".$CI->session->userdata('parent_org_id'))->execute();
                      return $eve; 
					  }
					}
			else {
        			$eve=Doctrine_Query::Create()->select('event_name,event_id')->from('UlsEventCreation')->where('parent_org_id='.$CI->session->userdata('parent_org_id'))->execute();
					return $eve; 
				 }
		    }
	  else {   
			   $eve=Doctrine_Query::Create()->select('event_name,event_id')->from('UlsEventCreation')->where('parent_org_id='.$CI->session->userdata('parent_org_id'))->execute();
               return $eve;
			}          
      }
	  
	static function geteventsbyprogram($id){
		$CI =& get_instance();
		$CI->load->library('session');  
	    $eve=Doctrine_Query::Create()->select('event_name,event_id')->from('UlsEventCreation')->where('parent_org_id='.$CI->session->userdata('parent_org_id').' and 	program_id='.$id)->execute();
         return $eve; 
	  
	}
	//Modified by Nagaraj to get the parent organization
	static function getorgs(){
		$roledata=Doctrine_Core::getTable("UlsRoleCreation")->findOneByRole_id($_SESSION['Role_id']);
		$menucreation=Doctrine_Core::getTable("UlsMenuCreation")->findOneByMenu_creation_id($roledata->menu_id);
		$parentorg="";
		if($menucreation->system_menu_type=='mngr'){
			if(!empty($roledata->security_org) and !empty($roledata->hierarchy_id)){
				$orgidsdata=UlsOrganizationMaster::getchildorgsdata_report($roledata->security_org);					
				$orgids=$orgidsdata;
				$parentorg=" organization_id in (".$orgids.") ";
			}
			else if(!empty($roledata->security_org) and empty($roledata->hierarchy_id)){
				$parentorg=" parent_org_id in (".$roledata->parent_org_id.") ";
			}
			else { 
				$parentorg=" parent_org_id in (".$roledata->parent_org_id.") ";
			}
		}
		else{
			$parentorg=" parent_org_id in (".$roledata->parent_org_id.") ";
		}
		$orgs=Doctrine_Query::Create()->select('organization_id,org_name')->from('UlsOrganizationMaster')->where("$parentorg")->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();      
        return $orgs;
    }
	
	static function getenrollmentstatus($mcode){
        $enronstatus=Doctrine_Query::Create()->select('value_code,value_name,master_code')->from('UlsAdminValues')->where('master_code="'.$mcode.'"')->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
        return $enronstatus; 
    }
	
	static function getteststatus($mcode){
		$enronstatus=Doctrine_Query::Create()->select('value_code,value_name,master_code')->from('UlsAdminValues')->where('master_code="'.$mcode.'" and (value_code="PAS" or value_code="FAI")')->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
		return $enronstatus;
	}
	
	static function getreportgroups(){
		$groups=Doctrine_Query::Create()->select('report_group_id as id, report_group_name as name')->from('UlsReportGroups')->execute();
		return $groups;
    }
	
	static function getgroupreportdetails12($id){
		$sql=($id=='')? '': ' and a.report_group_id='.$id;
		$groups=Doctrine_Query::Create()->select('a.report_group_id as id, a.report_group_name as name,b.org_name as orgname,count(report_grp_details_id) as numreports')->from('UlsReportGroups a')->LeftJOin('a.UlsOrganizationMaster b')->LeftJoin('a.UlsReportGroupDetails c')->where('a.report_group_id=c.report_group_id and a.parent_org_id=b.organization_id '.$sql)->execute();
		return $groups;
	}
	
	static function employeetrainingreport($prog,$eve,$enrol,$location,$enumber,$orgname,$fromdate,$todate){	 
		$roledata=Doctrine_Core::getTable("UlsRoleCreation")->findOneByRole_id($_SESSION['Role_id']);
		$menucreation=Doctrine_Core::getTable("UlsMenuCreation")->findOneByMenu_creation_id($roledata->menu_id);
		$parentorg="";
		if($menucreation->system_menu_type=='mngr'){
			if(!empty($roledata->security_org) and !empty($roledata->hierarchy_id)){
				$orgidsdata=UlsOrganizationMaster::getchildorgsdata_report($roledata->security_org);
				$orgids=$orgidsdata;
				$parentorg=" and empw.org_id in (".$orgids.") ";
			}
			else if(!empty($roledata->security_org) and empty($roledata->hierarchy_id)){
				$parentorg=" and empw.parent_org_id in (".$roledata->parent_org_id.") ";
			}
			else{ 
				$parentorg=" and empw.parent_org_id in (".$roledata->parent_org_id.") ";
			}
		}
		else{
			$parentorg=" and empw.parent_org_id in (".$roledata->parent_org_id.") ";
		}
		$sql="";
		$sql=$enumber!=''? " and c.employee_number='".$enumber."'": '';
		$sql.=$prog!=""?' and b.program_id='.$prog : "";
		$sql.=$eve!=''? ' and b.event_id='.$eve : "";
		$sql.=$orgname!=''? ' and a.organization_id='.$orgname : "";
		$sql.=$enrol!=''? ' and a.enrollment_status_type_id="'.$enrol.'"' : ""; 
		$sql.=$location!=''? ' and b.location_id="'.$location.'"' : ""; 			
		$query="select rvd.res_type as ven_type,rvd.name as ven_name,c.full_name as ename,c.employee_number as enumb,c.employee_id,e1.org_name as businessunit,e.org_name,f.position_name,g.grade_name,p.program_name,b.event_name,b.event_start_date,a.emp_event_start_date,a.modified_date,a.emp_event_end_date,b.event_end_date,b.event_id,ad.value_name,eloc.location_id,eloc.location_name from  uls_enrollments a "
		. " Left join(select event_id,program_id,event_name,event_end_date,event_start_date,location_id from uls_event_creation group by event_id)b on b.event_id=a.event_id "
		." LEFT JOIN(select event_id,event_sess_id,session_name from uls_event_session)es on es.event_id=b.event_id"
		. " Left Join(select location_id,location_name from uls_location group by location_id)eloc on b.location_id=eloc.location_id "
		." Left Join(select program_name,program_id from uls_program group by program_id)p on p.program_id=b.program_id "
		." Left Join(select value_code,value_name,master_code from uls_admin_values group by value_id)ad on a.enrollment_status_type_id=ad.value_code and master_code like 'SYSTEM_ENROLLMENT_STATUS'"
		. " Left Join(select employee_id,emp_type,full_name,date_of_joining,date_of_exit,employee_number from uls_employee_master group by employee_id)c on (c.employee_id=a.employee_id)  "
		. "  Left Join(select org_id,bu_id,parent_org_id,position_id,status,grade_id,location_id,employee_id from  uls_employee_work_info group by work_info_id )empw on ( a.employee_id=empw.employee_id and empw.status='A') "
		. " Left Join(select organization_id,org_name from uls_organization_master group by organization_id)e on empw.org_id=e.organization_id "
		. " Left Join(select organization_id,org_name from uls_organization_master group by organization_id)e1 on empw.bu_id=e1.organization_id "
		. " Left Join(select position_id,position_name from uls_position group by position_id )f on empw.position_id=f.position_id "
		. " Left Join(select grade_id,grade_name from uls_grade group by grade_id)g on empw.grade_id=g.grade_id "				 
		." LEFT JOIN(select resource_booking_id,resource_id,chat_id,forum_id,expert_topic_id,event_id,event_sess_id from uls_resource_book where resource_type='VEN')rv on rv.event_id=b.event_id and (rv.event_sess_id=es.event_sess_id or rv.event_sess_id is null)and rv.chat_id is null and rv.forum_id is null and rv.expert_topic_id is null"
		." LEFT JOIN(select res_venue_id as resource_def_id,name,res_type from uls_resource_venue)rvd on (rvd.resource_def_id=rv.resource_id)"		 
		." where a.parent_org_id=".$_SESSION['parent_org_id']." $parentorg  and ( b.event_start_date between '".date('Y-m-d',  strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."') ".$sql." ; SET SQL_BIG_SELECTS=1";
         $empdetail=UlsMenu::callpdo($query); 
        return $empdetail;
	} 
	
    static function programexecutionreport($catid,$resorceid,$fromdate,$todate){
        $sql=($catid!='')?'and c.category_id='.$catid:'';
        $sql.=($resorceid!='')?' and a.event_status="'.$resorceid.'"' : "";
        $query="select rd.name as full_name,rd.res_type, rvd.res_type as ven_type,rvd.name as ven_name,en.count,c.name,b.program_name,a.event_name,a.event_start_date,a.event_end_date,a.event_start_time,a.event_end_time,d.value_name,a.enrollment_start_date,a.enrollment_end_date,e.location_name,es.session_name  from uls_event_creation a "
		. " Left Join(select event_id,count(employee_id) as count from uls_enrollments group by event_id)en on en.event_id=a.event_id "
		. " Left Join(select program_id,category_id,program_name from uls_program group by program_id)b on a.program_id=b.program_id "
		. " Left Join(select category_id,name from uls_category group by category_id)c on c.category_id=b.category_id "
		. " Left Join(select value_name,value_code,master_code from uls_admin_values group by value_id)d on d.value_code=a.event_status and d.master_code like 'EVENT_STATUS' "
		. " Left Join(select location_id,location_name from uls_location group by location_id)e on a.location_id=e.location_id"
		/* . " Left Join(select resource_id,event_id,status from uls_resource_booking group by resource_booking_id)f on a.event_id=f.event_id and f.status='CON' " */
		." LEFT JOIN(select event_id,event_sess_id,session_name from uls_event_session)es on es.event_id=a.event_id"
		." LEFT JOIN(select resource_booking_id,resource_id,chat_id,forum_id,expert_topic_id,event_id,event_sess_id from uls_resource_book where resource_type='TRA')rb on rb.event_id=a.event_id and (rb.event_sess_id=es.event_sess_id or rb.event_sess_id is null)and rb.chat_id is null and rb.forum_id is null and rb.expert_topic_id is null"
		." LEFT JOIN(select res_trainer_id as resource_def_id,name,res_type from uls_resource_trainer)rd on (rd.resource_def_id=rb.resource_id)"
		." LEFT JOIN(select resource_booking_id,resource_id,chat_id,forum_id,expert_topic_id,event_id,event_sess_id from uls_resource_book where resource_type='VEN')rv on rv.event_id=a.event_id and (rv.event_sess_id=es.event_sess_id or rv.event_sess_id is null)and rv.chat_id is null and rv.forum_id is null and rv.expert_topic_id is null"
		." LEFT JOIN(select res_venue_id as resource_def_id,name,res_type from uls_resource_venue)rvd on (rvd.resource_def_id=rv.resource_id)"
		. " where a.parent_org_id=".$_SESSION['parent_org_id']." and ( a.event_start_date between '".date('Y-m-d',  strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."') ".$sql . " group by es.event_sess_id,a.event_id  ; SET SQL_BIG_SELECTS=1";
		$empdetail=UlsMenu::callpdo($query); 
		return $empdetail;
    }
	
    static function evalutionreport($prog,$eve,$sesid,$evaltype,$fromdate,$todate){
		$CI =& get_instance();
		$CI->load->library('session');
		$roledata=Doctrine_Core::getTable("UlsRoleCreation")->findOneByRole_id($CI->session->userdata('Role_id'));
		$menucreation=Doctrine_Core::getTable("UlsMenuCreation")->findOneByMenu_creation_id($roledata->menu_id);
		$parentorg="";
		if($menucreation->system_menu_type=='mngr'){
			if(!empty($roledata->security_org) and !empty($roledata->hierarchy_id)){
				$orgidsdata=UlsOrganizationMaster::getchildorgsdata_report($roledata->security_org);
				$orgids=$orgidsdata;
				$parentorg=" and empw.org_id in (".$orgids.") ";
			}
			else if(!empty($roledata->security_org) and empty($roledata->hierarchy_id)){
				$parentorg=" and empw.parent_org_id in (".$roledata->parent_org_id.") ";
			}
			else{
				$parentorg=" and empw.parent_org_id in (".$roledata->parent_org_id.") ";
			}
		}
		else{
			$parentorg=" and empw.parent_org_id in (".$roledata->parent_org_id.") ";
		}
		$sql='';
		$sql=$prog!=""?' and  b.program_id='.$prog : '';
		$sql.=$eve!=""? ' and b.event_id='.$eve : "";
		$sesid=$sesid!=''? ' and ses.event_sess_id='.$sesid : '';
		$query="select f.test_type,t1.test_id,t1.test_name as prename,gr.grade_name,l.location_name,o.org_name,o1.org_name as org_name1,a.employee_id, b.event_id,b.event_start_date,b.event_end_date,ses.event_sess_id,ses.session_name, c.program_id, c.program_name, b.event_name, a.emp_event_start_date, a.emp_event_end_date,d.full_name,d.employee_number,empw.employee_id as workempid, e.value_name as programtype,f.score as prescore,f.correct_ans as precorr,f.wrong_ans as prewrong,g.value_name as prestatus,f.version_number as preattempts from uls_enrollments a
		INNER JOIN ( select event_id,event_name,event_start_date,event_end_date,event_type,program_id from uls_event_creation group by event_id )b on a.event_id=b.event_id
		INNER JOIN(select program_id,program_name from uls_program group by program_id )c on b.program_id=c.program_id 
		INNER JOIN(select employee_id,full_name,employee_number from uls_employee_master group by employee_id)d on d.employee_id=a.employee_id 
		INNER Join(select org_id,bu_id,parent_org_id,position_id,status,grade_id,location_id,employee_id from uls_employee_work_info group by work_info_id )empw on ( a.employee_id=empw.employee_id and empw.status='A') 
		Left Join(select organization_id,org_name from uls_organization_master group by organization_id)o on empw.org_id=o.organization_id 
		Left Join(select organization_id,org_name,bu_type,org_type from uls_organization_master where org_type='BU' group by organization_id)o1 on empw.bu_id=o1.organization_id 
		Left Join(select location_id,location_name from uls_location)l on l.location_id=empw.location_id 
		Left Join(select grade_id,grade_name from uls_grade)gr on gr.grade_id=empw.grade_id 
		LEFT JOIN(select value_code,master_code,value_name from uls_admin_values group by value_id)e on b.event_type=e.value_code and e.master_code like 'EVENT_TYPE' 
		LEFT JOIN(Select session_name,event_id,event_sess_id from uls_event_session group by event_sess_id)ses on (b.event_id=ses.event_id  $sesid) 
		LEFT JOIN(select event_id, attempt_status, test_id, event_sess_id, finished_date, employee_id, score, correct_ans, wrong_ans, test_type, version_number from uls_utest_attempts where (test_type='PRE' or test_type='POST') and status='A' group by attempt_id)f on (f.employee_id=a.employee_id and (b.event_id=f.event_id  and (ses.event_sess_id=f.event_sess_id or f.event_sess_id is NULL)))
		LEFT JOIN(select test_name,test_id from uls_test)t1 on f.test_id=t1.test_id
		LEFT JOIN(select value_code,value_name,master_code from uls_admin_values group by value_id)g on
		g.value_code=f.attempt_status and g.master_code like 'TEST_STATUS'
		where a.parent_org_id=".$CI->session->userdata('parent_org_id')." and empw.parent_org_id in (".$CI->session->userdata('parent_org_id').") and (b.event_start_date between '".date('Y-m-d',  strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."') ".$sql." and f.test_id is not null group by a.employee_id,f.test_type,f.test_id,f.event_sess_id,f.event_id order by b.event_name,t1.test_name ASC; SET SQL_BIG_SELECTS=1";
		$empdetail=UlsMenu::callpdo($query);
		return $empdetail;
	}
	
	//added by sravanthi for feedback in evaluation report
	static  function evalutionfeedreport($prog,$eve,$sesid,$evaltype,$fromdate,$todate){
		$CI =& get_instance();
		$CI->load->library('session');
		$roledata=Doctrine_Core::getTable("UlsRoleCreation")->findOneByRole_id($CI->session->userdata('Role_id'));
		$menucreation=Doctrine_Core::getTable("UlsMenuCreation")->findOneByMenu_creation_id($roledata->menu_id);
		$parentorg="";
		if($menucreation->system_menu_type=='mngr'){
			if(!empty($roledata->security_org) and !empty($roledata->hierarchy_id)){
				$orgidsdata=UlsOrganizationMaster::getchildorgsdata_report($roledata->security_org);					
				$orgids=$orgidsdata;
				$parentorg=" and empw.org_id in (".$orgids.") ";
			}
			else if(!empty($roledata->security_org) and empty($roledata->hierarchy_id)){
					$parentorg=" and empw.parent_org_id in (".$roledata->parent_org_id.") ";
			}
			else { 
					$parentorg=" and empw.parent_org_id in (".$roledata->parent_org_id.") ";
				}
		}
	    else {   
			$parentorg=" and empw.parent_org_id in (".$roledata->parent_org_id.") ";
	    }
        $sql='';
		$sql=$prog!=""?' and  b.program_id='.$prog :'';
		$sql.=$eve!=""? ' and b.event_id='.$eve : "";
		$sesid=$sesid!=''? ' and ses.event_sess_id='.$sesid :'';
		$jointype=!empty($sesid)?'inner':'left';
		
		$query="SELECT hi.test_name,ses.event_sess_id,ses.session_name,gr.grade_name,l.location_name,o.org_name,a.employee_id,b.event_id,b.event_start_date,c.program_id, c.program_name, b.event_name,d.full_name,d.employee_number,b.event_end_date,q.question_category, round(avg(replace( a.text , '-%', '' )),2) as rating , a.`employee_id` , a.`event_id` , a.`event_sess_id`
		FROM `uls_utest_responses` a
		LEFT JOIN ( select event_id,event_name,event_start_date,event_end_date,event_type,program_id from uls_event_creation group by event_id )b on a.event_id=b.event_id 
		LEFT JOIN(select program_id,program_name from uls_program group by program_id )c on b.program_id=c.program_id 
		LEFT JOIN (SELECT question_id, question_category FROM uls_questions GROUP BY question_id)q ON q.question_id = a.user_test_question_id
		LEFT JOIN(select employee_id,full_name,employee_number from uls_employee_master group by employee_id)d on d.employee_id=a.employee_id 
		Left Join(select org_id,parent_org_id,position_id,status,grade_id,location_id,employee_id from  uls_employee_work_info group by work_info_id )empw on ( a.employee_id=empw.employee_id and empw.status='A') 
		Left Join(select organization_id,org_name from uls_organization_master group by organization_id)o on empw.org_id=o.organization_id 
		Left Join(select location_id,location_name from uls_location group by location_id)l on l.location_id=empw.location_id
		Left Join(select grade_id,grade_name from uls_grade group by grade_id)gr on gr.grade_id=empw.grade_id 
		$jointype JOIN(Select session_name,event_id,event_sess_id from uls_event_session group by event_sess_id)ses on (b.event_id=ses.event_id and a.`event_sess_id`=ses.event_sess_id $sesid)
		left JOIN `uls_event_sess_evaluation` ij on ij.event_id=a.event_id and  a.event_sess_id=ij.event_sess_id and ij.sess_evaluation_type='FEED'
		left JOIN `uls_events_evaluation` jk on jk.event_id=a.event_id and jk.evaluation_type='FEED'
		left JOIN uls_test hi ON ( hi.test_id = ij.test_id or  hi.test_id = jk.test_id )
		WHERE a.parent_org_id=".$CI->session->userdata('parent_org_id')." and hi.test_name is not null and (b.event_start_date>='".date('Y-m-d',  strtotime($fromdate))."' and b.event_start_date<='".date('Y-m-d',  strtotime($todate))."') and empw.parent_org_id in (".$CI->session->userdata('parent_org_id').") and q.question_category is not null" .$sql." GROUP BY a.`event_sess_id` , a.`event_id` , a.`employee_id` , q.question_category";
		$empdetail=UlsMenu::callpdo($query); 
        return $empdetail;
    }
    
	static  function individualevalutionreport($prog,$eve,$ses,$enumber,$testtype,$teststatus,$fromdate,$todate){
		$CI =& get_instance();
		$CI->load->library('session');
		$sql='';
		$sql=$prog!=""?' and  b.program_id='.$prog : '';
		$sql.=$eve!=""? ' and b.event_id='.$eve : "";
		$sql12='';
		$sql12.=$testtype!=''? " and test_type='".$testtype."'": '';
		$sql12.=$teststatus!=''? " and attempt_status='".$teststatus."'": '';
		$sesid=$ses!=''? ' and ses.event_sess_id='.$ses : '';
		$query=" select bs.user_status,a.enrollment_status_type_id,d.employee_id,d.full_name,d.employee_number,d.parent_org_id,b.event_id,c.program_id,c.program_name,b.event_name,b.event_start_date,b.event_end_date,a.emp_event_start_date,a.emp_event_end_date,e.value_name as programtype,ses.session_name,ses.sess_start_date,ses.sess_end_date,pres.value_name as prestatus,pre.score as prescore,pre.test_type as testtype, poss.value_name as poststatus,pos.score as postscore, feds.value_name as feedstatus from uls_employee_master d 
		Left Join(select enrollment_status_type_id,employee_id,emp_event_start_date,event_id,emp_event_end_date from uls_enrollments group by enrollment_id )a on (a.employee_id=d.employee_id)
		left join (select * from uls_booking_status where parent_org_id=".$CI->session->userdata('parent_org_id').")bs on bs.system_status=a.enrollment_status_type_id
		LEFT JOIN(Select session_name,sess_start_date,sess_end_date,event_id,event_sess_id from uls_event_session group by event_sess_id)ses on (a.event_id=ses.event_id $sesid ) 
		Left JOIN(select event_id,attempt_status,event_sess_id,finished_date,employee_id,status,score,correct_ans,wrong_ans,test_type,version_number from uls_utest_attempts where test_type='PRE' and status='A' group by attempt_id )pre on (a.event_id=pre.event_id and pre.employee_id=d.employee_id and (ses.event_sess_id=pre.event_sess_id or pre.event_sess_id is null)) 
		LEFT JOIN( select value_code,value_name,master_code from uls_admin_values group by value_id)pres on (pres.value_code=pre.attempt_status and pres.master_code like 'TEST_STATUS') 
		Left JOIN(select event_id,attempt_status,event_sess_id,finished_date,employee_id,status,score,correct_ans,wrong_ans,test_type,version_number from uls_utest_attempts where test_type='POST'  and status='A' group by attempt_id )pos on (a.event_id=pos.event_id and pos.employee_id=d.employee_id and (ses.event_sess_id=pos.event_sess_id or pos.event_sess_id is null)) 
		LEFT JOIN( select value_code,value_name,master_code from uls_admin_values group by value_id)poss on (poss.value_code=pos.attempt_status and poss.master_code like 'TEST_STATUS') 
		Left JOIN(select event_id,attempt_status,event_sess_id,finished_date,employee_id,score,correct_ans,wrong_ans,test_type,version_number from uls_utest_attempts where test_type='FEED' group by attempt_id )fed on (a.event_id=fed.event_id and fed.employee_id=d.employee_id and (ses.event_sess_id=fed.event_sess_id or fed.event_sess_id is null))
		LEFT JOIN( select value_code,value_name,master_code from uls_admin_values group by value_id)feds on (feds.value_code=fed.attempt_status and feds.master_code like 'TEST_STATUS') 
		LEFT JOIN ( select event_id,event_name,event_start_date,event_end_date,event_type,program_id from uls_event_creation group by event_id )b on (a.event_id=b.event_id) 
		LEFT JOIN(select program_id,program_name from uls_program group by program_id )c on b.program_id=c.program_id 
		LEFT JOIN(select value_code,master_code,value_name from uls_admin_values group by value_id)e on (b.event_type=e.value_code and e.master_code like 'EVENT_TYPE') where d.parent_org_id=".$CI->session->userdata('parent_org_id')." and d.employee_number='".$enumber."' ".$sql." ; SET SQL_BIG_SELECTS=1"; 
		$empdetail=UlsMenu::callpdo($query); 
		return $empdetail;
   }
	public static function evesessions($eveid,$sess,$fromdate,$todate){
		$sql="";
		$sql.=!empty($eveid)?" and a.event_id=".$eveid:"";
		$sql.=!empty($sess)?" and b.event_sess_id=".$sess:"";
		$sql.=(!empty($fromdate) && !empty($todate))?" and (b.sess_start_date>='".date('Y-m-d',  strtotime($fromdate))."' and b.sess_start_date<='".date('Y-m-d',  strtotime($todate))."')":"";
		$query="select a.event_id,a.event_name,b.session_name,b.event_sess_id  from uls_event_creation a 
		Left Join(select event_sess_id,sess_start_date,session_name,event_id from uls_event_session group by event_sess_id)b on (b.event_id=a.event_id) where 1 $sql ORDER BY `b`.`event_sess_id` ASC ";
		$empdetail=UlsMenu::callpdo($query);
		return $empdetail;   
    }
	
	public static function getevent($eveid,$enum){
		$sql=!empty($eveid)?" and a.event_id=$eveid ":"";
		$query="select a.event_id,a.event_name from uls_event_creation a left join uls_enrollments b on b.event_id=a.event_id where 1 $sql and b.employee_id=(select employee_id from uls_employee_master where employee_number='".$enum."')";
		//$eve=Doctrine_Core::getTable('UlsEventCreation')->findOneByEventId($eveid);
		return UlsMenu::callpdo($query);
	 }
   
	public static function feedbackdata($eve,$sess,$enumber,$fromdate,$todate){
		$sql2=!empty($eve)?" and res.event_id=$eve":"";
		$sql=!empty($sess)?" and res.event_sess_id=$sess":"";
		$query="select res.text, a.employee_id, a.full_name, res.event_id, res.event_sess_id, a.employee_number, res.response_value_id, ques.question_id, ques.question_name from uls_employee_master a 	 
		LEFT JOIN( select distinct(user_test_question_id), event_sess_id, employee_id,text,test_type, event_id,created_date,response_value_id from uls_utest_responses group by user_test_response_id)res on a.employee_id=res.employee_id and res.test_type='FEED'  $sql $sql2
		Left Join(select question_name, question_id from uls_questions group by question_id)ques on ques.question_id=res.user_test_question_id
		where a.employee_number='".$enumber."'";  
	//and res.created_date between '".date('Y-m-d',  strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."'
		$empdetail=UlsMenu::callpdo($query);
		$empdetails=array();
		foreach($empdetail as $key=>$val){
			$txtdata='';
			$txt=explode('-',$val['text']);
			$txtdata=isset($txt[1])?$txt[1]:$val['text'];
			$e=$val['event_id'];
			$s=!empty($val['event_sess_id'])?$val['event_sess_id']:0;
			$q=$val['question_id'];
			$empdetail[$e][$s][$q]=$txtdata;
		}
		return $empdetail; 
    }
	


   
    static function eventoverlapreport($eveid,$fromdate,$todate){
        $sql="";
        $sql.=$eveid!=''?' and a.event_id!='.$eveid : " ";
        $query="select c.full_name as ename,c.email,c.employee_id,c.employee_number as enumb,c.ecount,e.org_name,g.grade_name,p.program_name,b.event_name,b.event_start_date,b.event_end_date,b.event_id,eloc.location_name from  uls_enrollments a "
                 . " Left join(select event_id,program_id,event_name,event_end_date,event_start_date,location_id,delivery_method from uls_event_creation group by event_id)b on b.event_id=a.event_id "
                 . " Left Join(select location_id,location_name from uls_location group by location_id)eloc on b.location_id=eloc.location_id "
                  ." Left Join(select program_name,program_id from uls_program group by program_id)p on p.program_id=b.program_id "
                 . " Left Join(select employee_id,count(employee_id) as ecount,email,emp_type,full_name,employee_number from uls_employee_master group by employee_id)c on c.employee_id=a.employee_id "
                 . " left join(select org_id,position_id,grade_id,location_id,employee_id,from_date,to_date,status from  uls_employee_work_info group by work_info_id )d on c.employee_id=d.employee_id and date('y-m-d') between d.from_date and d.to_date and d.status='A' "
                 . " Left Join(select organization_id,org_name from uls_organization_master group by organization_id)e on d.org_id=e.organization_id "
                 . " Left Join(select grade_id,grade_name from uls_grade group by grade_id)g on d.grade_id=g.grade_id "
                 ." where a.parent_org_id=".$_SESSION['parent_org_id']." and a.enrollment_status_type_id='CON' and b.delivery_method='C' and  b.event_start_date >='".date('Y-m-d',  strtotime($fromdate))."' and b.event_end_date <='".date('Y-m-d',  strtotime($todate))."' and a.employee_id in 
				 ( select ens.employee_id from uls_enrollments ens 
				 Left Join( select event_id,event_start_date,delivery_method,event_end_date from uls_event_creation group by event_id )ev on ens.event_id=ev.event_id  and ev.event_start_date >='".date('Y-m-d',  strtotime($fromdate))."' and ((ev.event_end_date<= '".date('Y-m-d',  strtotime($todate))."') || (ev.event_end_date is null) ) and  ev.delivery_method='C' where ens.event_id=".$eveid.")
				 ".$sql . " ; SET SQL_BIG_SELECTS=1";
      // $query="select a.event_id,a.employee_id,a.emp_event_start_date,a.emp_event_end_date from uls_enrollments a ";
        $empdetail=UlsMenu::callpdo($query); 
        return $empdetail;
     }  

	static function geteventsessions($eveid){
		$sessions=Doctrine_Query::Create()->from('UlsEventSession')->where('event_id='.$eveid)->execute();
		return $sessions;
    }
	static function getusername(){
        if(isset($_SESSION['emp_id'])){
			$query="select employee_id,full_name from uls_employee_master where employee_id=".$_SESSION['emp_id'];
			$empdetail=UlsMenu::callpdorow($query); 
			return $empdetail;
        } 
	}
	
	static function getemployeedet($enum){
		$query="select * from employee_data where employee_number='".$enum."' and parent_org_id=".$_SESSION['parent_org_id'];
		$empdetail=UlsMenu::callpdorow($query); 
		return $empdetail;
	}
   
	static function budgetreport($progid,$eveid,$fromdate,$todate){
		$sql="";
		$sql.=$progid!=""?' and a.program_id='.$progid : "";
		$sql.=$eveid!=''? ' and a.event_id='.$eveid : "";
		$query="select a.event_id,a.event_name,a.event_start_date,a.event_end_date,a.actual_cost,a.budget_cost,a.budget_currency_code,a.program_id,pro.program_name,loc.location_name,enr.totalemps from uls_event_creation a 
		Left Join(select program_id,program_name from uls_program group by program_id)pro on (a.program_id=pro.program_id) 
		Left Join(select location_id,location_name from uls_location group by location_id)loc on (loc.location_id=a.location_id)
		Left Join(select count(employee_id) as totalemps,event_id from uls_enrollments where enrollment_status_type_id='CON' or enrollment_status_type_id='ATT' group by event_id)enr on (enr.event_id=a.event_id )
		where a.parent_org_id=".$_SESSION['parent_org_id']." and ( a.event_start_date between '".date('Y-m-d',  strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."') and (( a.event_end_date between  '".date('Y-m-d',  strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."') or (a.event_end_date is null) ) ".$sql. " ; SET SQL_BIG_SELECTS=1";
		// $query=" call gettestsforevalu( ".$eve_id.", ".$emp_id." ) ";
		return UlsMenu::callpdo($query);
	}
	
	static function gettotalbudjet($fromdate,$todate){
		$from=explode('-',$fromdate);
		$to=explode('-',$todate);
		$query="select budget_amount as budgetamount from uls_budget_period_definition a         		
		Left Join(select parent_org_id,budget_id from uls_budget_name_definition group by budget_id)nam on (a.budget_id=nam.budget_id)

		Left Join(select budget_name_id,budget_amount,parent_org_id from uls_budget_amount_definition group by id)amt on ( amt.budget_name_id=nam.budget_id and amt.parent_org_id=".$_SESSION['parent_org_id'].") 

		where a.period_from_year between ".$from[2]." and  ".$to[2]." and a.period_to_year between ".$from[2]." and  ".$to[2]." and nam.parent_org_id=".$_SESSION['parent_org_id'];
		return UlsMenu::callpdorow($query);
	}
		 
   
	static function budgetreportdetails($cat,$progid,$eveid,$fromdate,$todate){
		$sql="";
		$sql.=$cat!=""?' and cat.category_id='.$cat : "";
		$sql.=$progid!=""?' and a.program_id='.$progid : "";
		$sql.=$eveid!=''? ' and a.event_id='.$eveid : "";
		$query="select a.event_id, a.event_name,a.event_start_date, a.event_end_date,a.actual_cost,a.budget_cost, a.budget_currency_code,a.program_id,pro.program_name,loc.location_name,enr.totalemps,tra.event_expenses_id, tra.item_type, tra.amount  from uls_event_creation a 
		Left Join(select category_id,program_id,program_name from uls_program group by program_id)pro on (a.program_id=pro.program_id)
		Left Join(select category_id,name from uls_category group by category_id)cat on (pro.category_id=cat.category_id)
		Left Join(select location_id,location_name from uls_location group by location_id)loc on (loc.location_id=a.location_id)
		Left Join(select count(employee_id) as totalemps,event_id from uls_enrollments where enrollment_status_type_id='CON' or enrollment_status_type_id='ATT' group by event_id)enr on (enr.event_id=a.event_id )
		Left Join(select event_expenses_id,item_type,event_id,amount,event_sess_id from uls_event_expenses group by event_expenses_id)tra on (a.event_id=tra.event_id and tra.event_sess_id is null)
		where a.parent_org_id=".$_SESSION['parent_org_id']." and ( a.event_start_date between '".date('Y-m-d',  strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."') and (( a.event_end_date between  '".date('Y-m-d',  strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."') or (a.event_end_date is null) ) ".$sql. " ; SET SQL_BIG_SELECTS=1";
		// $query=" call gettestsforevalu( ".$eve_id.", ".$emp_id." ) ";
		$items=UlsMenu::callpdo($query);
		foreach($items as $key=>$item){
			$eveid=$item['event_id'];
			$itemtyp=$item['item_type'];
			$items[0][$eveid][$itemtyp]=$item['amount'];
		}
		
		return $items;
	}
	
	
	static function getemployeelearningdetails($prog,$eve,$fromdate,$todate){
		$roledata=Doctrine_Core::getTable("UlsRoleCreation")->findOneByRole_id($_SESSION['Role_id']);
		$menucreation=Doctrine_Core::getTable("UlsMenuCreation")->findOneByMenu_creation_id($roledata->menu_id);
		$parentorg="";
		if($menucreation->system_menu_type=='mngr'){
			if(!empty($roledata->security_org) and !empty($roledata->hierarchy_id)){
				$orgidsdata=UlsOrganizationMaster::getchildorgsdata_report($roledata->security_org);					
				$orgids=$orgidsdata;
				$parentorg=" and empw.org_id in (".$orgids.") ";
			}
			else if(!empty($roledata->security_org) and empty($roledata->hierarchy_id)){
				$parentorg=" and empw.parent_org_id in (".$roledata->parent_org_id.") ";
			}
			else{
				$parentorg=" and empw.parent_org_id in (".$roledata->parent_org_id.") ";
			}
		}
		else{
			$parentorg=" and empw.parent_org_id in (".$roledata->parent_org_id.") ";
		}     		
	
		$query="select a.event_id,a.parent_org_id,a.employee_id,a.enrollment_status_type_id,evename.event_name,evename.event_start_date,evename.event_end_date,progname.program_name,emp.full_name,emp.employee_number,org.org_name,pre.avg_score as prescore,pos.avg_score as posscore,his.event_sess_id,his.evaluation_id,his.maxscore,ses.session_name as maxsession,mins.minscore,mins.event_sess_id,minses.event_sess_id,minses.session_name as minsession,evefeed.spoken_english,evefeed.written_english,evefeed.listening_skills,evefeed.interaction_with_colleagues,evefeed.interaction_with_trainers,evefeed.teamwork,evefeed.punctuality,evefeed.dressing_style,evefeed.etiquette,evefeed.nourish,evefeed.focus from uls_enrollments a Left Join(select event_id,program_id,event_start_date,event_end_date,event_name from uls_event_creation group by event_id)evename on (a.event_id=evename.event_id) Left Join(select program_id,program_name from uls_program group by program_id)progname on (evename.program_id=progname.program_id)
		  Left Join(select full_name,employee_id,parent_org_id,employee_number from uls_employee_master group by employee_id)emp on (a.employee_id=emp.employee_id) LEFT JOIN(select employee_id,parent_org_id,org_id,status from uls_employee_work_info group by work_info_id)empw on (empw.employee_id=a.employee_id and empw.status='A') Left Join(select org_name,organization_id from uls_organization_master group by organization_id)org on (org.organization_id=empw.org_id) Left JOIN( SELECT format(AVG( score ),2) AS avg_score,evaluation_id,event_id,`employee_id` , test_type FROM `uls_utest_attempts` where evaluation_id is not null and test_type='PRE' and event_sess_id is null GROUP BY employee_id)pre on ( a.event_id=pre.event_id and a.employee_id=pre.employee_id ) Left JOIN( SELECT format(AVG( score ),2) AS avg_score,evaluation_id,event_id,`employee_id` , test_type FROM `uls_utest_attempts` where evaluation_id is not null and test_type='POST' and event_sess_id is null GROUP BY employee_id)pos on ( a.event_id=pos.event_id and a.employee_id=pos.employee_id )
		  Left Join(select score as maxscore,evaluation_id,event_sess_id,employee_id,event_id,test_type from uls_utest_attempts ss where score=(select max(score) from uls_utest_attempts fff where ss.event_id=fff.event_id and ss.employee_id=fff.employee_id and evaluation_id is not null and test_type='POST' and event_sess_id is null) group by employee_id )his on (a.event_id=his.event_id and a.employee_id=his.employee_id )
		  Left Join(select event_sess_id,session_name,event_id from uls_event_session group by event_sess_id)ses on (a.event_id=ses.event_id and his.event_sess_id=ses.event_sess_id) 		  
		  Left Join(select score as minscore,evaluation_id,event_sess_id,employee_id,event_id,test_type from uls_utest_attempts mmm where score=(select min(score) from uls_utest_attempts mm where mmm.event_id=mm.event_id and mmm.employee_id=mm.employee_id and evaluation_id is not null and test_type='POST' and event_sess_id is null) group by employee_id )mins on (a.event_id=mins.event_id and a.employee_id=mins.employee_id )
		 Left Join(select event_sess_id,session_name,event_id from uls_event_session group by event_sess_id)minses on (a.event_id=minses.event_id and mins.event_sess_id=minses.event_sess_id) Left Join(select spoken_english,written_english,listening_skills,interaction_with_colleagues,interaction_with_trainers,teamwork,punctuality,dressing_style,grooming,event_id,employee_id,parent_org_id,etiquette,nourish,focus from uls_event_feedback group by feedback_id )evefeed on (a.event_id=evefeed.event_id and a.employee_id=evefeed.employee_id and a.parent_org_id=evefeed.parent_org_id) where a.event_id= ".$eve." $parentorg and a.parent_org_id=".$_SESSION['parent_org_id'];
         return UlsMenu::callpdo($query);
	
	}  
		 

	/////// TNA REPORT Code ////////////////////	 
  
	static function gettnayears(){
		$CI =& get_instance();
		$CI->load->library('session');
		$tna=Doctrine_Query::Create()->select('tna_id as id, tna_year as name')->from('UlsTnaYearSetup')->where("parent_org_id=".$CI->session->userdata('parent_org_id'))->execute();
        return $tna;
    }
   
	static function gettnamanagers(){ 
		$CI =& get_instance();
		$CI->load->library('session');
		$tna=Doctrine_Query::Create()->select('distinct(supervisor_id) as empid')->from('UlsEmployeeWorkInfo')->where("status='A'  and 
		parent_org_id=".$CI->session->userdata('parent_org_id'))->execute();	
		$emps="";
		foreach($tna as $emp){
			if(empty($emps)){ $emps=$emp['empid'];}
			else { $emps=$emps.",".$emp['empid'];  }
		}
		if(!empty($emps)){
			$tna=Doctrine_Query::Create()->select('employee_id as id, full_name as name')->from('UlsEmployeeMaster')->where("employee_id in ($emps)")->execute();
		}
		else{
			$tna=array();
		}		
		return $tna;
	}
	
	static function gettnasources(){
	    $tna=Doctrine_Query::Create()->select("value_code as id, value_name as name")->from("UlsAdminValues")->where("master_code='ORG_SUB_TYPE'")->execute();
        return $tna;
	
	 }
	 static function tnareport_old($tnayear,$orgname,$tnamanager,$prog,$catid,$transource){
	  $sql=" ";
	  $sql.=$orgname!=''?' and ao.tna_parent_org_id='.$orgname : " ";
	  $sql.=$tnamanager!=''?' and a.trainer='.$tnamanager : " ";
	  $sql.=$prog!=''?' and p.program_id='.$prog : " ";
	  $sql.=$catid!=''?' and c.category_id='.$catid : " ";
	  //$sql.=$transource!=''?' and a.trainer_type='.$transource : " ";
	  $sql.=!empty($transource)? !empty($sql)?" and a.trainer_type like '%$transource'": " and  a.trainer_type like '%$transource%'":"";
	  $query="select av.value_name as tnasource,o.org_name as childorg,oa.org_name as parentorg,p.program_name,c.name,a.tna_id,a.category_id,a.program_id,a.trainer_type,a.no_of_employees,a.trainer from uls_tna_admin_program a 
	  LEFT JOIN(select value_code,value_name,master_code from uls_admin_values)av on av.value_code=a.trainer_type and av.master_code='ORG_SUB_TYPE'
	  LEFT JOIN(select category_id,name from uls_category)c on c.category_id=a.category_id 
	  LEFT JOIN(select program_id,program_name from uls_program)p on p.program_id=a.program_id 
	  LEFT JOIN(select tna_id,tna_parent_org_id,tna_child_org_id from uls_tna_admin_org_info)ao on ao.tna_id=a.tna_id 
	  LEFT JOIN(select organization_id,org_name from uls_organization_master)o on o.organization_id=ao.tna_child_org_id
      LEFT JOIN(select organization_id,org_name from uls_organization_master)oa on oa.organization_id=ao.tna_parent_org_id 	
	  where a.tna_id='".$tnayear."' ".$sql." ; SET SQL_BIG_SELECTS=1";
	  $empdetail=UlsMenu::callpdo($query); 
      return $empdetail;
          
    }
	
	static function tnareport($orgname,$department,$progloc,$level,$catid,$tnamanager,$tnayear){
		$CI =& get_instance();
		$CI->load->library('session');
		$sql=" ";
		$sql.=$orgname!=''?' and e.bu_id='.$orgname : " ";
		$sql.=$department!=''?' and ao.tna_parent_org_id='.$department : " ";
		$sql.=$catid!=''?' and c.category_id='.$catid : " ";
		//$sql.=$tnamanager!=''?' and a.trainer='.$tnamanager : " ";
		$sql.=$tnayear!=''?' and a.tna_id='.$tnayear : " ";
		$sql.=$tnamanager!=''?' and s.supervisor_id='.$tnamanager : " ";
		$query="select tap.status,e2.full_name as manager,e.employee_number, e.full_name,e.bu,e.org_name,e.grade_name,e.location_name,c.name, p.program_name, a.parent_org_id, a.tna_id, a.category_id, a.month_id, a.days, a.criticality, a.trainer,tae.program_name as other_program,e.zone_name,et.value_name,a.mngr_acceptance,a.admin_prg_id from uls_tna_admin_program a 
		LEFT JOIN(select category_id,name from uls_category)c on c.category_id=a.category_id 
		LEFT JOIN(select program_id,program_name from uls_program)p on p.program_id=a.program_id 
		LEFT JOIN(select tna_id,program_id,employee_id,program_name,admin_prg_id from uls_tna_admin_employees)tae on a.admin_prg_id=tae.admin_prg_id
		LEFT JOIN(select status,tna_id,employee_id from uls_tna_admin_year where admin_year_id in(select max(admin_year_id) from uls_tna_admin_year group by tna_id,employee_id))tap on tap.tna_id=tae.tna_id and tap.employee_id=tae.employee_id
		LEFT JOIN(select * from employee_data)e on e.employee_id=tae.employee_id
		left join(SELECT master_code,value_name,value_code FROM `uls_admin_values`) et on et.`master_code`='NEW_EMP_TYPE' and et.value_code=e.emp_type
		LEFT JOIN(select employee_id,full_name from uls_employee_master)e2 on e2.employee_id=e.supervisor_id 
		LEFT JOIN(select employee_id,supervisor_id from employee_data)s on s.supervisor_id=e2.employee_id
		where a.parent_org_id='".$CI->session->userdata('parent_org_id')."'   ".$sql." group by a.program_id,a.program_name,e.employee_number order by e.employee_number asc; SET SQL_BIG_SELECTS=1";
		$empdetail=UlsMenu::callpdo($query); 
		return $empdetail;
	}
  //////////////////End Of TNA Report Code//////////////////////

 //////////Start of Vendor Report Code. //////////////////////////
   
	static function  getvendororgs(){  
		$CI =& get_instance();
		$CI->load->library('session');
        $orgs=Doctrine_Query::Create()->select("organization_id,org_name")->from("UlsOrganizationMaster")->where("org_type1='E' and parent_org_id=".$CI->session->userdata('parent_org_id'))->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
		return $orgs;
    }
   	
	static function getvendorname(){
		$CI =& get_instance();
		$CI->load->library('session');
		$arr=array();$i=0;
		$traname=Doctrine_Query::Create()->select("res_trainer_id as resource_def_id,'TRA' as structure_name, name as column2")->from("UlsResourceTrainer")->where("parent_org_id=".$CI->session->userdata('parent_org_id'))->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
		foreach($traname as $val){
			$arr[$i]=$val;
			/* $arr['structure_name']=$val['structure_name'];
			$arr['structure_name']=$val['column2']; */
			$i++;
		}
		
		$venname=Doctrine_Query::Create()->select("res_venue_id as resource_def_id,'VEN' as structure_name, name as column2")->from("UlsResourceVenue")->where("parent_org_id=".$CI->session->userdata('parent_org_id'))->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
		foreach($venname as $val){
			$arr[$i]=$val;
			/* $arr['structure_name']=$val['structure_name'];
			$arr['structure_name']=$val['column2']; */
			$i++;
		}
		return $arr;  
	}
  
	static function vendortariningreport($resourcecat,$vendorname,$res_type,$prog,$eveid,$fromdate,$todate){
		$CI =& get_instance();
		$CI->load->library('session');
		$sql="";
		$sql.=!empty($resourcecat)? !empty($sql)?" and ee.item_type = '$resourcecat'": " and  ee.item_type = '$resourcecat'":"";
		$vendorname=!empty($vendorname)?explode("-",$vendorname):array();
		if(isset($vendorname[1])){
			if($vendorname[1]=='TRA'){
				$sql.=$vendorname!=''?' and d.res_trainer_id='.$vendorname[0] : " ";
			}
			else{
				$sql.=$vendorname!=''?' and f.res_venue_id='.$vendorname[0] : " ";
			}
		}
		if(isset($vendorname[1])){
			if($vendorname[1]=='TRA'){
				$sql.=!empty($res_type)? !empty($sql)?" and d.res_type = '$res_type'": " and  d.res_type = '$res_type'":"";
			}
			else{
				$sql.=!empty($res_type)? !empty($sql)?" and f.res_type = '$res_type'": " and  f.res_type = '$res_type'":"";
			}
		}
		else{
			$sql.=!empty($res_type)? !empty($sql)?" and (d.res_type = '$res_type' or f.res_type = '$res_type')": " and  (d.res_type = '$res_type'  or f.res_type = '$res_type')":"";
		}
		$sql.=$prog!=''?' and a.program_id='.$prog : " ";
		$sql.=$eveid!=''?' and a.event_id='.$eveid : " ";
		$query="SELECT av.value_name,ee.amount,ee.exp_status,s.session_name,IF(r.resource_type='TRA',d.res_type,f.res_type) as res_type,IF(r.resource_type='TRA',d.name,f.name) as name,e.nop, p.program_name, l.location_name, a.location_id, a.program_id, a.event_name,a.event_id, a.event_end_date, a.event_start_date,s.event_sess_id FROM uls_event_creation a
		LEFT JOIN (SELECT location_id, location_name FROM uls_location)l ON l.location_id = a.location_id
		LEFT JOIN (SELECT program_id, program_name FROM uls_program)p ON p.program_id = a.program_id
		INNER JOIN(select event_expenses_id,event_id,event_sess_id,item_type,amount,exp_status,exp_resource_booking_id from uls_event_expenses group by event_expenses_id)ee on ee.event_id=a.event_id
		LEFT JOIN (SELECT event_sess_id, session_name, event_id FROM uls_event_session group by event_sess_id)s ON s.event_id = ee.event_id and s.event_sess_id=ee.event_sess_id
		LEFT JOIN (SELECT enrollment_status_type_id, event_id, count( employee_id ) AS nop FROM uls_enrollments GROUP BY event_id)e ON e.event_id = a.event_id AND ( e.enrollment_status_type_id in ('CON','ATT','NOS'))
		LEFT JOIN(select resource_booking_id,  resource_id, resource_type, chat_id, forum_id, expert_topic_id, event_id, event_sess_id from uls_resource_book)r on r.event_id=a.event_id and r.chat_id is null and r.forum_id is null and r.expert_topic_id is null and (r.event_sess_id=s.event_sess_id or r.event_sess_id is null) and r.resource_booking_id=ee.exp_resource_booking_id
		LEFT JOIN(select res_trainer_id,res_type,name from uls_resource_trainer)d on d.res_trainer_id=r.resource_id and r.resource_type='TRA'
		LEFT JOIN(select res_venue_id,res_type,name from uls_resource_venue)f on f.res_venue_id=r.resource_id and
		r.resource_type='VEN'
		LEFT JOIN(select master_code,value_code,value_name from uls_admin_values)av on av.value_code=ee.item_type and av.master_code='BUDGET_ITEM'
		where a.parent_org_id=".$CI->session->userdata('parent_org_id')." and ( a.event_start_date between '".date('Y-m-d',  strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."') and (( a.event_end_date between  '".date('Y-m-d', strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."') or (a.event_end_date is null) ) ".$sql;
		//SET SQL_BIG_SELECTS=1";
		$empdetail=UlsMenu::callpdo($query);
		return $empdetail;
	}
	////////////End Of Vendor Report Code///////////////////////////// 

	static function getprogramloaction(){
		$CI =& get_instance();
		$CI->load->library('session');	
		$venname=Doctrine_Query::Create()->select("location_id,location_name")->from("UlsLocation")->where("parent_org_id=".$CI->session->userdata('parent_org_id'))->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
		return $venname;  
	} 

	static function trainingannualcalendar($cal_id,$zone,$month){
		$sql="1";
		$sql.=!empty($cal_id)?" and a.calendar_id=$cal_id":"";
		$sql.=!empty($zone)?" and a.zone_id='$zone'":"";
		if(!empty($month)){
			$date=date("Y")."-".$month."-01";
			$month=strtoupper(date("F",strtotime($date)));
			$sql.=!empty($month)?" and e.month='$month'":"";
		}

		$query="SELECT b.program_name,c.name,a.`zone_id`,a.`calendar_month_id`,d.value_name,e.month,e.year FROM `uls_calendar_programs` a left join uls_program b on a.`program_id`=b.`program_id` left join uls_category c on a.`category_id`=c.`category_id` left join uls_admin_values d on d.master_code='LOCATION_ZONES' and d.value_code=a.`zone_id` left join uls_calendar_months e on e.calendar_month_id=a.`calendar_month_id` WHERE $sql ORDER BY `a`.`calendar_month_id` ASC";
		return UlsMenu::callpdo($query);
	}
	
	////////////Training Calendar Report ///////////////////////////	
    static function trainingcalendarreport($prog,$proglocation,$fromdate,$todate){
		$CI =& get_instance();
		$CI->load->library('session');
		$sql2="";
		//$sql2.=$org!=''?' and a.parent_org_id='.$org: " ";
		$sql2.=$prog!=''?' and a.program_id='.$prog : " ";
		$sql2.=$proglocation!=''?' and a.location_id='.$proglocation : " ";
		$query1="select a.parent_org_id,a.event_name ,a.event_id,b.program_name,c.name,a.event_status,a.event_end_date,a.event_end_time,a.event_start_date,a.event_start_time,adv.value_name as evestatus,f.location_name,zon.value_name as zone,g.name as trainer, h.name as venue from uls_event_creation a 
	    Left Join(SELECT program_id,category_id,program_name FROM uls_program group by program_id)b on (a.program_id=b.program_id)
	    Left Join(SELECT category_id,name FROM uls_category group by category_id)c on (c.category_id=b.category_id)
		Left Join(select location_id,location_name,location_zones from uls_location group by location_id)f on (a.location_id=f.location_id)
		Left Join(SELECT value_code,value_name FROM uls_admin_values WHERE master_code = 'LOCATION_ZONES')zon on zon.value_code=f.location_zones
		Left Join(SELECT value_code,value_name FROM uls_admin_values WHERE master_code = 'EVENT_STATUS')adv on (adv.value_code=a.event_status)
		LEFT JOIN (SELECT event_sess_id, session_name, event_id FROM uls_event_session group by event_sess_id)s ON s.event_id = a.event_id
		LEFT JOIN(select resource_booking_id, resource_id,resource_type,chat_id,forum_id,expert_topic_id,event_id,event_sess_id from uls_resource_book)r on r.event_id=a.event_id and r.chat_id is null and r.forum_id is null and r.expert_topic_id is null and (r.event_sess_id=s.event_sess_id or r.event_sess_id is null)
		LEFT JOIN(select res_trainer_id,res_type,name from uls_resource_trainer)g on g.res_trainer_id=r.resource_id and r.resource_type='TRA'
		LEFT JOIN(select res_venue_id,res_type,name from uls_resource_venue)h on h.res_venue_id=r.resource_id and r.resource_type='VEN'
		where a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sql2 and a.event_start_date between '".date('Y-m-d',  strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."'";
		return UlsMenu::callpdo($query1);
    }  
    static function getresourcecategory(){
	    $struct=Doctrine::getTable('UlsResourceStructure')->findAll();
        return $struct;
	}
	//Employee Trined Vs Un Trained
    static function getlevel(){  
		$CI =& get_instance();
		$CI->load->library('session');
        $level=Doctrine_Query::Create()->select("grade_id,grade_name")->from("UlsGrade")->where("parent_org_id=".$CI->session->userdata('parent_org_id'))->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
        return $level;  
    }
	//modified by sravanthi gy.training_days-DATEDIFF(e.event_end_date,e.event_start_date)
    static function trainedvsuntrained($org,$dept,$category,$proglocation,$level,$fromdate,$todate)
	{
		$CI =& get_instance();
		$CI->load->library('session');
		$sql=" ";
		$sql.=$org!=''?' and ew.bu_id='.$org : " ";
		$sql.=$dept!=''?' and ew.org_id='.$dept : " ";
		$sql.=$proglocation!=''?' and ew.location_id='.$proglocation : " ";
		$sql.=$level!=''?' and ew.grade_id='.$level : " ";
		//$cat=$category!=''?' and c.category_id='.$category : " ";
		$cat=!empty($category)?"and c1.category_id=$category":"";
		$query="select em.employee_number,em.full_name,o.org_name as business_unit ,o1.org_name as department ,l.location_name, g.grade_name,gy.training_days,en1.count,en1.durations,a.partialattended,em1.full_name as manager from uls_employee_master em 
		left join(select employee_id,bu_id,org_id,grade_id,location_id,status,supervisor_id from uls_employee_work_info)ew on ew.employee_id=em.employee_id
		LEFT JOIN(select organization_id,org_name from uls_organization_master)o on o.organization_id=ew.bu_id
		LEFT JOIN(select organization_id,org_name from uls_organization_master)o1 on o1.organization_id=ew.org_id
		LEFT JOIN(select location_id,location_name from uls_location)l on l.location_id=ew.location_id
		LEFT JOIN(select grade_id,grade_name from uls_grade)g on g.grade_id=ew.grade_id 
		LEFT JOIN(select SUM(b1.duration) as durations,count(a1.event_id) as count,a1.event_id, a1.employee_id,a1.enrollment_status_type_id from uls_enrollments a1,uls_event_creation b1,uls_program c1 where b1.program_id=c1.program_id $cat and a1.event_id=b1.event_id and (a1.enrollment_status_type_id='ATT' || a1.enrollment_status_type_id='CON' ) group by a1.employee_id )en1 on en1.employee_id=em.employee_id
		LEFT JOIN(select event_id,program_id,event_start_date,event_end_date from uls_event_creation where event_start_date between '".date('Y-m-d',  strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."')e on e.event_id=en1.event_id
		LEFT Join uls_program p on p.program_id=e.program_id
		LEFT JOIN uls_category c on c.category_id=p.category_id
		LEFT JOIN(select training_days,grade_id,category_id from uls_grade_year)gy on gy.grade_id=g.grade_id 
		LEFT JOIN(select event_id,employee_id,count(attendance_id) as partialattended,status from uls_event_attendance where status='ATT' group by employee_id)a on a.employee_id=em.employee_id
		LEFT JOIN(select full_name,employee_id from uls_employee_master)em1 on em1.employee_id=ew.supervisor_id
		where em.parent_org_id=".$CI->session->userdata('parent_org_id')."  ".$sql . " ; SET SQL_BIG_SELECTS=1"
				 ;
	 return UlsMenu::callpdo($query); 
	}
    //program feedback report code
	static function getfeedbacktemplates()
	{
		$CI =& get_instance();
		$CI->load->library('session');
	    $template=Doctrine_Query::Create()->select("test_type_flag,test_id,test_name")->from("UlsTest")->where("parent_org_id=".$CI->session->userdata('parent_org_id')." and active_flag='P' and test_type_flag='F'")->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
        return $template; 
	}
	static function getparams($feedbacktemplate)
	{
	    $questions="select q.question_name,tq.test_quest_id,tq.test_id,tq.question_id from uls_test_questions tq
	    LEFT JOIN(select question_id,question_category,question_name from uls_questions)q on q.question_id=tq.question_id 
	    where q.question_category!='T' and tq.test_id=".$feedbacktemplate;
        return UlsMenu::callpdo($questions); 
	}
	static function programfeedback($programs,$event,$feedbacktemplate,$fromdate,$todate)
	{
		$CI =& get_instance();
		$CI->load->library('session');
	    $sql="";
		$sql.=$programs!=''?' and e.program_id='.$programs : " ";
		$sql.=$event!=''?' and e.event_id='.$event : " ";
		$query="SELECT e.parent_org_id,l.location_name, p.program_name, e.event_id, e.event_name, ss.event_sess_id,ss.session_name,e.event_end_date, e.event_start_date, DATEDIFF(e.event_end_date,e.event_start_date) as duration, uq.user_test_question_id, ur.`sess_evaluation_id` , ur.`evaluation_id` , ur.utest_question_id, round(avg(replace( ur.text , '-%', '' )),2) as avgr FROM uls_utest_responses ur
		INNER JOIN uls_utest_questions uq ON ur.utest_question_id = uq.id
		INNER JOIN uls_questions u ON u.question_id = uq.user_test_question_id
		INNER JOIN uls_event_creation e ON ur.event_id = e.event_id
		Inner Join uls_program p on p.program_id=e.program_id
		left join uls_location l on e.location_id=l.location_id
		left join uls_event_session ss on e.event_id=ss.event_id and ss.event_sess_id=uq.event_sess_id
		WHERE e.parent_org_id=".$CI->session->userdata('parent_org_id')."  and e.event_start_date between '".date('Y-m-d',strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."'  AND u.question_category != 'T' AND ur.test_type = 'FEED' AND uq.test_id =".$feedbacktemplate." $sql GROUP BY ur.user_test_question_id,  ur.`evaluation_id` , ur.`sess_evaluation_id` order by e.event_id,ss.event_sess_id";
	    return UlsMenu::callpdo($query); 
	}
	//Budget Report Code start here
	static function getbudgetnames(){
		$CI =& get_instance();
		$CI->load->library('session');
		$budgetnames=Doctrine_Query::Create()->select("budget_id,budget_name")->from("UlsBudgetNameDefinition")->where("parent_org_id=".$CI->session->userdata('parent_org_id')." and status='A'")->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
		return $budgetnames;
	}
	
	static function getbudgetperiodnames($budgetid){
		$CI =& get_instance();
		$CI->load->library('session');
		$budgetperiodnames="select budget_id,parent_org_id,period_id,period_name from uls_budget_period_definition where parent_org_id=".$CI->session->userdata('parent_org_id')." and budget_id=".$budgetid;
		return UlsMenu::callpdo($budgetperiodnames); 
	}
	static function budgetvsactual($budgetname,$budgetperiod,$location,$fromdate,$todate){
		$CI =& get_instance();
		$CI->load->library('session');
	    $sql="";
		$loc=$location!=''? ' and location='.$location : '';
		$query="SELECT count(en.event_id) as eventcount,count(ew.employee_id) as count ,l.location_name,o.org_name,e.dept_budget_amount ,c.budget_amount,a.budget_id,a.budget_name FROM `uls_budget_name_definition` a 
		LEFT JOIN(select id,budget_name_id,budget_amount from uls_budget_amount_definition)c on c.budget_name_id=a.budget_id 
		LEFT JOIN(select period_amt_id,dept_budget_id,dept_name_id,dept_budget_amount from uls_budget_org_amt_definition)e on e.dept_budget_id=c.id 
		LEFT JOIN(select organization_id,org_name,location from uls_organization_master)o on o.organization_id=e.dept_name_id 
		LEFT JOIN(select location_id,location_name from uls_location)l on l.location_id=o.location 
		LEFT JOIN(select employee_id,bu_id from uls_employee_work_info)ew on ew.bu_id=o.organization_id 
		LEFT JOIN(select event_id,employee_id from uls_enrollments)en on en.employee_id=ew.employee_id
        WHERE a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.budget_id=".$budgetname." $loc group by ew.bu_id,en.employee_id" ;
		return UlsMenu::callpdo($query); 
	}
	//Training Program report code 
	public static function get_months($status){
		$pdo = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
		$query = "select mc.master_code, mv.value_code as code, mv.value_name as name from uls_admin_master mc, uls_admin_values mv where mc.master_code='".$status."' and mc.master_code=mv.master_code";
		$org_val = $pdo->prepare($query);
		$org_val->execute();
		$org_values=$org_val->fetchAll();
		return $org_values;
	}
	
	public static function calendarnames(){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT calendar_id,calendar_name FROM `uls_calendar_name` where 1 and status='A' and parent_org_id=".$CI->session->userdata('parent_org_id');
		return UlsMenu::callpdo($query);
	}
	
	public static function trainingprogram($year,$month="")
	{
		$CI =& get_instance();
		$CI->load->library('session');
	    $sql="";
		$months=!empty($month)?" AND  month( event_start_date ) =".$month."":"";
		$query="SELECT b.bu_type, l.location_name, b.org_type, b.org_name, e.special_booking_instructions, b.organization_id, e.event_id, a.event_name,a.event_start_date as event_start_date,  a.event_end_date as event_end_date, e.employee_id, count( DISTINCT (e.employee_id) ) AS employee_count
		FROM uls_event_creation a 
		LEFT JOIN (SELECT event_id, employee_id, special_booking_instructions FROM uls_enrollments)e ON e.event_id = a.event_id
		LEFT JOIN uls_employee_work_info c ON e.employee_id = c.employee_id
		INNER JOIN uls_organization_master b ON b.organization_id = c.bu_id
		LEFT JOIN uls_location l ON l.location_id = b.location
		WHERE a.parent_org_id =".$CI->session->userdata('parent_org_id')." AND a.event_id IN (SELECT event_id FROM uls_event_creation WHERE year( event_start_date ) =".$year." ".$months.")
		   GROUP BY b.bu_type,b.org_name, e.event_id order by b.bu_type, l.location_name, b.org_name ASC";
		return UlsMenu::callpdo($query); 
	}
	
	//Trainer Feedback Report code 
	static function get_trainers(){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select d.res_trainer_id, d.res_type,d.name as tra_name from uls_resource_trainer d where d.parent_org_id=".$CI->session->userdata('parent_org_id')." and d.status='A'";
		return UlsMenu::callpdo($query); 
	}
	public static function trainerfeedbackreport($programname,$eventname,$trainername,$fromdate,$todate)
	{
	    $CI =& get_instance();
		$CI->load->library('session');
		$sql='';
		$sql.=$trainername!=""?' and rb.resource_id='.$trainername :'';
		$sql.=$eventname!=""? ' and e.event_id='.$eventname : "";
		$sql.=$programname!=''? ' and e.program_id='.$programname :'';
		$query="select rb.venue_rating,rb.trainer_rating,rb.overall_rating,rb.content_rating,rb.material_rating,rd.name as full_name, es.event_sess_id, es.session_name, p.program_name,e.program_id,e.event_id,e.event_name,e.event_start_date,e.event_end_date,es.sess_start_date,es.sess_end_date,rb.resource_id from uls_event_creation e 
		LEFT JOIN(select program_id,program_name from uls_program)p on p.program_id=e.program_id
		LEFT JOIN(select event_id,event_sess_id,session_name,sess_start_date,sess_end_date from uls_event_session)es on es.event_id=e.event_id
		LEFT JOIN(select resource_booking_id,resource_id,chat_id,forum_id,expert_topic_id,event_id,event_sess_id,trainer_rating,venue_rating,overall_rating,content_rating,material_rating from uls_resource_book where resource_type='TRA')rb on rb.event_id=e.event_id and (rb.event_sess_id=es.event_sess_id or rb.event_sess_id is null)and rb.chat_id is null and rb.forum_id is null and rb.expert_topic_id is null
		LEFT JOIN(select res_trainer_id,res_type,name from uls_resource_trainer)rd on (rd.res_trainer_id=rb.resource_id)
		where e.parent_org_id=".$CI->session->userdata('parent_org_id')." and ( e.event_start_date between '".date('Y-m-d',  strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."') ".$sql." group by e.event_id,es.event_sess_id";
		 
		 
		return UlsMenu::callpdo($query); 
	}
	
	//feedback report written by sravanthi 
	static function feedbackreport($programname,$eventname,$fromdate,$todate){
		$CI =& get_instance();
		$CI->load->library('session');
		$sql='';
		$sql.=$eventname!=""? ' and e.event_id='.$eventname : "";
		$sql.=$programname!=''? ' and e.program_id='.$programname :'';
		$query="select group_concat(distinct(upper(rd.name))) as full_name, group_concat(distinct(rd1.name)) as venue,p.program_name,l.location_name,av.value_name, utq.user_test_question_id, ua.test_id,es.event_sess_id,es.session_name,e.event_status,e.program_id,e.event_id,e.event_name,e.event_start_date,e.event_end_date,e.location_id,q.question_category ,round(avg(replace(utr.text , '-%', '' )),2) as rating from uls_event_creation e
		inner JOIN(select program_id,program_name from uls_program)p on p.program_id=e.program_id
		LEFT JOIN(select event_id,event_sess_id,session_name from uls_event_session)es on es.event_id=e.event_id
		inner JOIN(select location_id,location_name from uls_location)l on l.location_id=e.location_id
		inner JOIN(select value_code,value_name,master_code from uls_admin_values)av on av.value_code=e.event_status and av.master_code='EVENT_STATUS'
		LEFT JOIN(select resource_booking_id,resource_id,chat_id,forum_id,expert_topic_id,event_id,event_sess_id from uls_resource_book where resource_type='TRA' group by resource_booking_id)rb on rb.event_id=e.event_id and (rb.event_sess_id=es.event_sess_id or rb.event_sess_id is null)and rb.chat_id is null and rb.forum_id is null and rb.expert_topic_id is null
		LEFT JOIN(select res_trainer_id,res_type,name from uls_resource_trainer)rd on rd.res_trainer_id=rb.resource_id
		LEFT JOIN(select resource_booking_id,resource_id,chat_id,forum_id,expert_topic_id,event_id,event_sess_id from uls_resource_book where resource_type='VEN' group by resource_booking_id)rv on rv.event_id=e.event_id and (rv.event_sess_id=es.event_sess_id or rv.event_sess_id is null)and rv.chat_id is null and rv.forum_id is null and rv.expert_topic_id is null
		LEFT JOIN(select res_venue_id,res_type,name from uls_resource_venue)rd1 on rd1.res_venue_id=rv.resource_id
		LEFT JOIN(select event_id,event_sess_id,attempt_status,test_id,employee_id,score,correct_ans,test_type from uls_utest_attempts where test_type='FEED' and test_status='COM' group by attempt_id )ua on e.event_id=ua.event_id and (es.event_sess_id=ua.event_sess_id or ua.event_sess_id is null)
		inner JOIN(select id,employee_id,event_id,event_sess_id,test_type,user_test_question_id from uls_utest_questions
		where test_type='FEED')utq on ua.event_id=utq.event_id and (utq.event_sess_id=ua.event_sess_id or utq.event_sess_id
		is null)
		inner JOIN(select utest_question_id,user_test_question_id,test_type,text from uls_utest_responses where
		test_type='FEED' group by utest_question_id)utr on utr.utest_question_id=utq.id
		inner JOIN(select question_id,question_category from uls_questions)q on q.question_id=utr.user_test_question_id
		where  e.parent_org_id=".$CI->session->userdata('parent_org_id')." and e.program_id is not null and e.event_id is not null and
		q.question_category is not null and ( e.event_start_date between '".date('Y-m-d',  strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."') ".$sql ." group by e.program_id,e.event_id,es.event_sess_id,q.question_category";
		return UlsMenu::callpdo($query); 
	}
	
	static function testreport($programname,$eventname,$fromdate,$todate){
		$CI =& get_instance();
		$CI->load->library('session');
		$sql='';
		$sql.=$eventname!=""? ' and e.event_id='.$eventname : "";
		$sql.=$programname!=''? ' and e.program_id='.$programname :'';
		 $query="select
			ua.test_id as test,es.event_sess_id,e.event_start_date,e.program_id,e.event_id,e.event_name,ua.score,ua.test_type as type ,ua.correct_ans as correct ,ua.wrong_ans as wrong from uls_event_creation e 
			LEFT JOIN(select event_id,event_sess_id,session_name from uls_event_session)es on es.event_id=e.event_id
			LEFT JOIN(select event_id,event_sess_id,attempt_status,test_id,employee_id,score,correct_ans,wrong_ans,test_type from uls_utest_attempts where (test_type='PRE' or test_type='POST') and test_status='COM' and status='A' group by attempt_id) ua on e.event_id=ua.event_id
			and (es.event_sess_id=ua.event_sess_id or ua.event_sess_id is null)
		    where e.parent_org_id=".$CI->session->userdata('parent_org_id')." and e.program_id is not null and e.event_id is not null  and ( e.event_start_date between '".date('Y-m-d',  strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."') ".$sql ." group by ua.test_type,e.event_id,es.event_sess_id";
			return UlsMenu::callpdo($query); 
	}
	
	//written by sravanthi for showing session feedbacks at trainer side
	public static function trainerfeedback($event,$empid)
	{
	    $sql='';
		$sql.=$event!=""? ' and a.event_id='.$event : "";
		$sql.=$empid!=""?' and c.user_id='.$empid :'';
		$query="SELECT * FROM `uls_feedback` WHERE `event_id` =$event AND 
		`event_sess_id` IN (SELECT `event_sess_id` FROM `uls_resource_book` a INNER JOIN uls_resource_trainer b ON b.res_trainer_id = a.resource_id  WHERE a.`event_id` =$event and a.chat_id is null and a.event_sess_id is not null and a.forum_id is null and a.expert_topic_id is null AND b.user_id =$empid)";
		return UlsMenu::callpdo($query);
	}
	public static function trainereventfeedback($event,$empid)
	{
	    $sql='';
		$sql.=$event!=""? ' and a.event_id='.$event : "";
		$sql.=$empid!=""?' and c.user_id='.$empid :'';
		$query="SELECT * FROM `uls_feedback` WHERE `event_id` =$event AND 
		`event_id` IN (SELECT `event_id` FROM `uls_resource_book` a INNER JOIN uls_resource_trainer b ON b.res_trainer_id = a.resource_id  WHERE a.`event_id` =$event and a.chat_id is null and a.event_sess_id is null and a.forum_id is null and a.expert_topic_id is null AND b.user_id =$empid) and event_sess_id is NULL";
		return UlsMenu::callpdo($query);
	}
	public static function get_tests()
	{
		$tests="select test_id,parent_org_id,test_name from uls_test where parent_org_id=".$_SESSION['parent_org_id'];
		return UlsMenu::callpdo($tests); 
	}
	
	public static function questionanalysiseventreport($programname,$eventname,$testname,$trainername){
		$CI =& get_instance();
		$CI->load->library('session');
	    $sql='';
		$sql.=$programname!=""? ' and e.program_id='.$programname : "";
		$sql.=$eventname!=""? ' and e.event_id='.$eventname : "";
		$sql.=$testname!=""? ' and t.test_id='.$testname : "";
		$sql.=$trainername!=""?' and rb.resource_id='.$trainername :'';
		$query="select e.program_id,p.program_name,e.event_id,e.event_name,e.event_start_date as start_date,e.event_end_date as end_date,es.event_sess_id,es.session_name,e.parent_org_id,group_concat(distinct(upper(rd.name))) as full_name,l.location_name,u.test_id,u.test_type,t.test_name,uq.id,ur.user_test_question_id,q.question_name,ua.count,ua1.count1,r.correct,r1.wrong from uls_event_creation e 
		left join (select program_id,program_name from uls_program)p on p.program_id=e.program_id 
		left join(select event_id,event_sess_id,session_name from uls_event_session)es on es.event_id=e.event_id 
		left join(select resource_booking_id,resource_id,chat_id,forum_id,expert_topic_id,event_id,event_sess_id from uls_resource_book where resource_type='TRA' group by resource_booking_id)rb on rb.event_id=e.event_id and (rb.event_sess_id=es.event_sess_id or rb.event_sess_id is null)and rb.chat_id is null and rb.forum_id is null and rb.expert_topic_id is null 
		left join(select res_trainer_id,res_type,name from uls_resource_trainer)rd on (rd.res_trainer_id=rb.resource_id)
		left join(select location_id,location_name from uls_location)l on l.location_id=e.location_id 
		left join(select test_type,event_id,event_sess_id,test_id,evaluation_id,sess_evaluation_id,status from uls_utest_attempts where (test_type='PRE' or test_type='POST') and status='A' )u on u.event_id=e.event_id and (u.event_sess_id=es.event_sess_id or u.event_sess_id is null) 
		left join(select test_id,test_name from uls_test)t on t.test_id=u.test_id 
		left join(select event_id,event_sess_id,id,evaluation_id,sess_evaluation_id,employee_id from uls_utest_questions )uq on uq.evaluation_id=u.evaluation_id and (uq.sess_evaluation_id=u.sess_evaluation_id or uq.sess_evaluation_id is null) 
		left join(select utest_question_id,user_test_question_id from uls_utest_responses)ur on ur.utest_question_id=uq.id
	    left join(select question_id,question_name from uls_questions)q on q.question_id=ur.user_test_question_id
		left join(select count(correct_flag) as correct,evaluation_id,sess_evaluation_id,user_test_question_id,test_type from uls_utest_responses where (test_type='PRE' or test_type='POST') and correct_flag='C' group by user_test_question_id,evaluation_id)r on r.user_test_question_id=q.question_id and r.evaluation_id=uq.evaluation_id and (r.sess_evaluation_id=uq.sess_evaluation_id or r.sess_evaluation_id is null)
		left join(select count(correct_flag) as wrong,evaluation_id,sess_evaluation_id,user_test_question_id,test_type from uls_utest_responses where (test_type='PRE' or test_type='POST' ) and correct_flag='W' group by user_test_question_id,evaluation_id)r1 on r1.user_test_question_id=q.question_id and r1.evaluation_id=uq.evaluation_id and (r1.sess_evaluation_id=uq.sess_evaluation_id or r1.sess_evaluation_id is null)
		left join(select event_id,event_sess_id,count(distinct(employee_id)) as count,status from uls_utest_attempts where test_type='PRE'  and test_status='COM' and status='A' group by event_id,event_sess_id,test_id)ua on ua.event_id=e.event_id and (es.event_sess_id=ua.event_sess_id or ua.event_sess_id is null)
        left join(select event_id,event_sess_id,count(distinct(employee_id)) as count1,status from uls_utest_attempts where test_type='POST'  and test_status='COM' and status='A' group by event_id,event_sess_id,test_id)ua1 on ua1.event_id=e.event_id and (es.event_sess_id=ua1.event_sess_id or ua1.event_sess_id is null)		
		where e.parent_org_id=".$CI->session->userdata('parent_org_id')."".$sql." and t.test_id is not null and q.question_id is not null group by ur.user_test_question_id,e.program_id,e.event_id,u.test_id ,u.test_type order by e.event_id,es.event_sess_id,t.test_id";
		return UlsMenu::callpdo($query); 
	}
	
	public static function questionanalysissessionreport($programname,$eventname,$testname,$trainername){
		$CI =& get_instance();
		$CI->load->library('session');
		$sql='';
		$sql.=$programname!=""? ' and e.program_id='.$programname : "";
		$sql.=$eventname!=""? ' and e.event_id='.$eventname : "";
		$sql.=$testname!=""? ' and t.test_id='.$testname : "";
		$sql.=$trainername!=""?' and rb.resource_id='.$trainername :'';
		$query="select e.program_id,p.program_name,e.event_id,e.event_name,es.sess_start_date as start_date,es.sess_end_date as end_date,es.event_sess_id,es.session_name,e.parent_org_id,group_concat(distinct(upper(rd.name))) as full_name,l.location_name,u.test_id,u.test_type,t.test_name,uq.id,ur.user_test_question_id,q.question_name,ua.count,ua1.count1,r.correct,r1.wrong from uls_event_creation e 
		left join (select program_id,program_name from uls_program)p on p.program_id=e.program_id 
		left join(select event_id,event_sess_id,session_name,sess_start_date,sess_end_date from uls_event_session)es on es.event_id=e.event_id 
		left join(select resource_booking_id,resource_id,chat_id,forum_id,expert_topic_id,event_id,event_sess_id from uls_resource_book where resource_type='TRA' group by resource_booking_id)rb on rb.event_id=e.event_id and (rb.event_sess_id=es.event_sess_id or rb.event_sess_id is null)and rb.chat_id is null and rb.forum_id is null and rb.expert_topic_id is null 
		left join(select res_trainer_id,res_type,name from uls_resource_trainer)rd on (rd.res_trainer_id=rb.resource_id)
		left join(select location_id,location_name from uls_location)l on l.location_id=e.location_id 
		left join(select test_type,event_id,event_sess_id,test_id,evaluation_id,sess_evaluation_id,status from uls_utest_attempts where (test_type='PRE' or test_type='POST') and status='A' )u on u.event_id=e.event_id and (u.event_sess_id=es.event_sess_id or u.event_sess_id is null) 
		left join(select test_id,test_name from uls_test)t on t.test_id=u.test_id 
		left join(select event_id,event_sess_id,id,evaluation_id,sess_evaluation_id,employee_id from uls_utest_questions )uq on uq.event_id=u.event_id and uq.sess_evaluation_id=u.sess_evaluation_id 
		left join(select utest_question_id,user_test_question_id from uls_utest_responses)ur on ur.utest_question_id=uq.id
	    left join(select question_id,question_name from uls_questions group by question_id)q on q.question_id=ur.user_test_question_id
		left join(select count(correct_flag) as correct,evaluation_id,sess_evaluation_id,event_id,user_test_question_id,test_type from uls_utest_responses where (test_type='PRE' or test_type='POST') and correct_flag='C' group by user_test_question_id,sess_evaluation_id)r on r.user_test_question_id=q.question_id and r.sess_evaluation_id=uq.sess_evaluation_id 
		left join(select count(correct_flag) as wrong,evaluation_id,sess_evaluation_id,event_id,user_test_question_id,test_type from uls_utest_responses where (test_type='PRE' or test_type='POST' ) and correct_flag='W' group by user_test_question_id,sess_evaluation_id)r1 on r1.user_test_question_id=q.question_id and r1.event_id=uq.event_id and r1.sess_evaluation_id=uq.sess_evaluation_id
		left join(select event_id,event_sess_id,count(distinct(employee_id)) as count,sess_evaluation_id,status from uls_utest_attempts where test_type='PRE'  and test_status='COM' and status='A' group by event_id,event_sess_id,test_id,sess_evaluation_id)ua on ua.event_id=e.event_id and es.event_sess_id=ua.event_sess_id and ua.sess_evaluation_id=uq.sess_evaluation_id
        left join(select event_id,event_sess_id,count(distinct(employee_id)) as count1,sess_evaluation_id,status from uls_utest_attempts where test_type='POST'  and test_status='COM' and status='A' group by event_id,event_sess_id,test_id,sess_evaluation_id)ua1 on ua1.event_id=e.event_id and es.event_sess_id=ua1.event_sess_id and ua1.sess_evaluation_id=uq.sess_evaluation_id
		where e.parent_org_id=".$CI->session->userdata('parent_org_id')."".$sql." and t.test_id is not null and q.question_id is not null group by ur.user_test_question_id,e.program_id,e.event_id,u.test_id ,u.test_type order by e.event_id,es.event_sess_id,t.test_id";
		return UlsMenu::callpdo($query); 
	}
	
    public static function getorgsbylocation($locid){
		$roledata=Doctrine_Core::getTable("UlsRoleCreation")->findOneByRole_id($_SESSION['Role_id']);
		$menucreation=Doctrine_Core::getTable("UlsMenuCreation")->findOneByMenu_creation_id($roledata->menu_id);
		$parentorg="";
		//echo "hello".$menucreation->system_menu_type;
		if($menucreation->system_menu_type=='mngr'){
			//echo $roledata->security_org;
			if(!empty($roledata->security_org) and !empty($roledata->hierarchy_id)){
				$orgidsdata=UlsOrganizationMaster::getchildorgsdata_report($roledata->security_org);
				$orgids=$orgidsdata;
				$parentorg=" organization_id in (".$orgids.") ";
			}
			else if(!empty($roledata->security_org) and empty($roledata->hierarchy_id)){
				$parentorg=" parent_org_id in (".$roledata->parent_org_id.") ";
			}
			else{
				$parentorg=" parent_org_id in (".$roledata->parent_org_id.") ";
			}
		}
		else {
			$parentorg=" parent_org_id in (".$roledata->parent_org_id.") ";
		}
		// echo $parentorg;
		$orgs=Doctrine_Query::Create()->select('organization_id,org_name')->from('UlsOrganizationMaster')->where("$parentorg and location=".$locid)->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
		return $orgs;
	}
	//For NHO FEEDBACK
	
	public static function nhofeedback($programs,$event,$feedbacktemplate,$fromdate,$todate){
		$CI =& get_instance();
		$CI->load->library('session');
		$sql="";
		$sql.=$programs!=''?' and e.program_id='.$programs : " ";
		$sql.=$event!=''?' and e.event_id='.$event : " ";
		$query="SELECT e.parent_org_id,l.location_name, p.program_name, e.event_id, e.event_name, ss.event_sess_id,ss.session_name,e.event_end_date, e.event_start_date, DATEDIFF(e.event_end_date,e.event_start_date) as duration, uq.user_test_question_id, ur.`sess_evaluation_id` , ur.`evaluation_id` , ur.utest_question_id, round(avg(replace( ur.text , '-%', '' )),2) as avgr FROM uls_utest_responses ur
		INNER JOIN uls_utest_questions uq ON ur.utest_question_id = uq.id
		INNER JOIN uls_questions u ON u.question_id = uq.user_test_question_id
		INNER JOIN uls_event_creation e ON ur.event_id = e.event_id
		Inner Join uls_program p on p.program_id=e.program_id
		left join uls_location l on e.location_id=l.location_id
		left join uls_event_session ss on e.event_id=ss.event_id and ss.event_sess_id=uq.event_sess_id
		WHERE e.parent_org_id=".$CI->session->userdata('parent_org_id')."  and e.event_start_date between '".date('Y-m-d',strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."'  AND u.question_category != 'T' AND ur.test_type = 'FEED' AND uq.test_id =".$feedbacktemplate." $sql GROUP BY ur.user_test_question_id,  ur.`evaluation_id` , ur.`sess_evaluation_id` order by e.event_id,ss.event_sess_id";
		return UlsMenu::callpdo($query);
	}
	
    static function getnhoevents($feedid){
		$CI =& get_instance();
		$CI->load->library('session');
		$event="select e.event_name,ev.parent_org_id,ev.test_id,ev.evaluation_id,ev.event_id from uls_events_evaluation ev 
		left join(select event_id,event_name from uls_event_creation)e on e.event_id=ev.event_id where ev.test_id=".$feedid." and ev.parent_org_id=".$CI->session->userdata('parent_org_id');
		return UlsMenu::callpdo($event);
	}
	
	static function getnhoprogramevents($feedid,$programs){
		$CI =& get_instance();
		$CI->load->library('session');
		$event="select e.event_name,ev.parent_org_id,ev.test_id,ev.evaluation_id,ev.event_id from uls_events_evaluation ev 
		left join(select program_id,event_id,event_name from uls_event_creation)e on e.event_id=ev.event_id and e.program_id=".$programs."
		where ev.test_id=".$feedid." and ev.parent_org_id=".$CI->session->userdata('parent_org_id');
		return UlsMenu::callpdo($event);
	}
	
	static function getnhoevent($feedid,$events){
		$CI =& get_instance();
		$CI->load->library('session');
		$event="select e.event_name,ev.parent_org_id,ev.test_id,ev.evaluation_id,ev.event_id from uls_events_evaluation ev 
		left join(select program_id,event_id,event_name from uls_event_creation)e on e.event_id=ev.event_id 
		where ev.test_id=".$feedid." and ev.event_id=".$events." and ev.parent_org_id=".$CI->session->userdata('parent_org_id');
		return UlsMenu::callpdo($event);
	}
	
	static function getnhoeventnew($feedid,$programs,$events){
		$CI =& get_instance();
		$CI->load->library('session');
		$event="select e.event_name,ev.parent_org_id,ev.test_id,ev.evaluation_id,ev.event_id from uls_events_evaluation ev 
		left join(select program_id,event_id,event_name from uls_event_creation)e on e.event_id=ev.event_id 
		where ev.test_id=".$feedid." and e.program_id=".$programs." and ev.event_id=".$events." and ev.parent_org_id=".$CI->session->userdata('parent_org_id');
		return UlsMenu::callpdo($event);
	}
	
	//written by sravanthi for getting freetext question in report output
	static function get_freetext_questions($eve){
		$CI =& get_instance();
		$CI->load->library('session');
		$questions="select ev.test_id, ev.event_id, ev.parent_org_id, ev.evaluation_type, q.question_id, q.question_type, q.question_name from uls_events_evaluation ev 
		left join(select test_id,question_id from uls_test_questions)tq on tq.test_id=ev.test_id
		left join(select question_id,question_name,question_type from  uls_questions)q on q.question_id=tq.question_id
		where ev.parent_org_id=".$CI->session->userdata('parent_org_id')." and ev.evaluation_type='FEED' and q.question_type='FT' and ev.event_id=".$eve;
		return UlsMenu::callpdo($questions);
	}
	
	static function get_session_freetext_questions($sessid){
		if(isset($sessid)){
			$CI =& get_instance();
			$CI->load->library('session');
			$questions="select ev.test_id,ev.event_sess_id,ev.parent_org_id,ev.sess_evaluation_type,q.question_id,q.question_type,q.question_name from uls_event_sess_evaluation ev 
			left join(select test_id,question_id from uls_test_questions)tq on tq.test_id=ev.test_id
			left join(select question_id,question_name,question_type from  uls_questions)q on q.question_id=tq.question_id
			where ev.parent_org_id=".$CI->session->userdata('parent_org_id')." and ev.sess_evaluation_type='FEED' and q.question_type='FT' and ev.event_sess_id=".$sessid;
			return UlsMenu::callpdo($questions);
		}
	}
	
	public static function check_sessions($prog){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="select es.event_sess_id,e.event_id,e.program_id from uls_event_creation e 
		inner join(select event_id,event_sess_id from uls_event_session)es on es.event_id=e.event_id where e.parent_org_id=".$CI->session->userdata('parent_org_id') ." and e.program_id=".$prog;
		return UlsMenu::callpdo($query);
	}
	
	public static function get_sessions($prog,$eve,$location,$fromdate,$todate){
		$CI =& get_instance();
		$CI->load->library('session');
		$sql="";
		$sql.=$eve!=''?' and e.event_id='.$eve : " ";
		$sql.=$location!=''?' and e.location_id='.$location : " ";
		$query="select e.event_id, e.program_id, e.parent_org_id, e.event_start_date, es.event_sess_id, e.event_name, es.session_name, es.sess_start_date, es.sess_end_date from uls_event_creation e
		left join uls_event_session es on es.event_id=e.event_id where e.program_id=".$prog." and e.parent_org_id=".$CI->session->userdata('parent_org_id')." and (e.event_start_date between '".date('Y-m-d',  strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."') ".$sql;
		return UlsMenu::callpdo($query);
	}
	
	public static function get_events($prog,$eve,$location,$fromdate,$todate){
		$CI =& get_instance();
		$CI->load->library('session');
		$sql='';
		$sql.=$eve!=''?' and event_id='.$eve : " ";
		$sql.=$location!=''?' and location_id='.$location : " ";
		$query="select event_id,event_name,event_start_date,event_end_date from uls_event_creation where program_id=".$prog." and parent_org_id=".$CI->session->userdata('parent_org_id')." and event_start_date between '".date('Y-m-d',  strtotime($fromdate))."' and '".date('Y-m-d',  strtotime($todate))."'" .$sql;
		return UlsMenu::callpdo($query);
	}
	
	public static function freetextreport($eve){
		$query="SELECT ur.event_id, ur.employee_id, e.full_name, e.employee_number, ur.user_test_question_id, ur.text, ur.response_type_id, ur.test_type FROM uls_utest_responses ur
		left join(select employee_id,full_name,employee_number from uls_employee_master)e on e.employee_id=ur.employee_id WHERE ur.test_type = 'FEED' AND ur.response_type_id =  'FT' AND ur.event_id =".$eve;
		return UlsMenu::callpdo($query);
	}
	
	public static function sessionfreetextreport($session){
		if(isset($session)){
			$query="SELECT ur.event_id, ur.event_sess_id, ur.employee_id, e.full_name, e.employee_number, ur.user_test_question_id, ur.text, ur.response_type_id, ur.test_type FROM uls_utest_responses ur
			left join(select employee_id,full_name,employee_number from uls_employee_master)e on e.employee_id=ur.employee_id WHERE ur.test_type = 'FEED' AND ur.response_type_id =  'FT' AND ur.event_sess_id =".$session;
			return UlsMenu::callpdo($query);
		}
	}
	
	public static function getdepartments(){
		$CI =& get_instance();
		$CI->load->library('session');
		$roledata=Doctrine_Core::getTable("UlsRoleCreation")->findOneByRole_id($CI->session->userdata('Role_id'));
		$menucreation=Doctrine_Core::getTable("UlsMenuCreation")->findOneByMenu_creation_id($roledata->menu_id);
		$parentorg="";
		//echo "hello".$menucreation->system_menu_type;
		if($menucreation->system_menu_type=='mngr'){
			//echo $roledata->security_org;
			if(!empty($roledata->security_org) and !empty($roledata->hierarchy_id)){
				$orgidsdata=UlsOrganizationMaster::getchildorgsdata_report($roledata->security_org);
				$orgids=$orgidsdata;
				$parentorg=" organization_id in (".$orgids.") ";
			}
			else if(!empty($roledata->security_org) and empty($roledata->hierarchy_id)){
				$parentorg=" parent_org_id in (".$roledata->parent_org_id.") ";
			}
			else{
				$parentorg=" parent_org_id in (".$roledata->parent_org_id.") ";
			}
		}
		else {
			$parentorg=" parent_org_id in (".$roledata->parent_org_id.") ";
		}
		// echo $parentorg;
		$orgs=Doctrine_Query::Create()->select('organization_id,org_name')->from('UlsOrganizationMaster')->where("$parentorg and org_type='DEPART'")->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
		return $orgs;
	}
	
	/////// Knowledge bulletin REPORT Code ////////////////////	 
  
	static function getbulname(){
		$CI =& get_instance();
		$CI->load->library('session');
		$tna=Doctrine_Query::Create()->select('bulletin_id as id, bulletin_name as name')->from('UlsAdminBulletin')->where("parent_org_id=".$CI->session->userdata('parent_org_id'))->execute();
        return $tna;
	}
	
	static  function bulletinreport($orgname,$depart,$progloc,$level,$zone,$bul_name){
		$CI =& get_instance();
		$CI->load->library('session');
		$sql=" ";
		$sql.=$bul_name!=''?' and a.bulletin_id='.$bul_name : " ";
		$sql.=$orgname!=''?' and d.bu_id='.$orgname : " ";
		$sql.=$depart!=''?' and d.org_id='.$depart : " ";
		$sql.=$progloc!=''?' and d.location_id='.$progloc : " ";
		$sql.=$zone!=''?" and d.zone_id='".$zone."'" : " ";
		$sql.=$level!=''?' and d.grade_id='.$level : " ";
		$query="select a.bulletin_name,d.full_name,d.employee_number,f.score as prescore,f.correct_ans as precorr,f.wrong_ans as prewrong,f.version_number as preattempts,d.zone_name,d.grade_name,d.org_name,d.bu,d.location_name from uls_admin_bulletin a
		LEFT JOIN(select attempt_id, event_id, attempt_status, status, test_id, timestamp,employee_id,score,correct_ans,wrong_ans,version_number from uls_utest_attempts_quiz)f on (f.event_id=a.bulletin_id)
		INNER JOIN(select employee_id,full_name,employee_number,bu_id,org_id,zone_id,grade_id,location_id,zone_name,grade_name,org_name,	bu,location_name from employee_data group by employee_id)d on d.employee_id=f.employee_id
		where a.parent_org_id=".$CI->session->userdata('parent_org_id'). $sql."; SET SQL_BIG_SELECTS=1";
        $empdetail=UlsMenu::callpdo($query); 
        return $empdetail;
    }
	
	static  function assessmentreport($prog,$position_id,$fromdate,$todate){
		$sql='';
		$sql.=$prog!=""?' and a.assessment_id='.$prog : '';
		$sql.=$position_id!=""?' and a.position_id='.$position_id : '';
		$query="select t.test_id,tc.test_name as prename,gr.position_name,l.location_name,o.org_name,a.employee_id, b.assessment_id, b.assessment_name, d.full_name,d.employee_number,empw.employee_id as workempid, f.score as prescore,f.correct_ans as precorr,f.wrong_ans as prewrong,f.version_number as preattempts from uls_assessment_employees a
		INNER JOIN (select assessment_id,assessment_name from uls_assessment_definition group by assessment_id )b on a.assessment_id=b.assessment_id
		INNER JOIN(select employee_id,full_name,employee_number from uls_employee_master group by employee_id)d on d.employee_id=a.employee_id 
		INNER Join(select org_id,parent_org_id,position_id,status,grade_id,location_id,employee_id from uls_employee_work_info group by work_info_id )empw on ( a.employee_id=empw.employee_id and empw.status='A') 
		LEFT Join(select organization_id,org_name from uls_organization_master group by organization_id)o on empw.org_id=o.organization_id 
		LEFT Join(select location_id,location_name from uls_location group by location_id)l on l.location_id=empw.location_id 
		LEFT Join(select position_id,position_name from uls_position group by position_id)gr on gr.position_id=empw.position_id 
		LEFT JOIN(select attempt_id, event_id, attempt_status, status, test_id, timestamp,employee_id,score,correct_ans,wrong_ans,version_number,assessment_id from uls_utest_attempts_assessment)f on (f.employee_id=a.employee_id and f.assessment_id=a.assessment_id)
		LEFT JOIN(select test_id from uls_assessment_test)t on t.test_id=f.test_id
		LEFT JOIN(select test_name,test_id from uls_competency_test)tc on tc.test_id=t.test_id
		where a.parent_org_id=".$_SESSION['parent_org_id']. $sql."  group by a.assessment_pos_emp_id; SET SQL_BIG_SELECTS=1";
					  
		 
          $empdetail=UlsMenu::callpdo($query); 
          return $empdetail;
    }
}