<?php

/**
 * UlsReportGroups
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsReportGroups extends BaseUlsReportGroups
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
    
    public static function searchcount($reportg_name){
        $sq=!empty($report_name)? " and a.report_group_name like '%$reportg_name%'":"";
		$query="SELECT count(*) as numcount FROM uls_report_groups a
		WHERE 1 $sq ";
		$testcount=UlsMenu::callpdorow($query);		
		return $testcount['numcount'];
    }
    
   
	public static function search($start, $limit,$reportg_name){
		$sq=!empty($reportg_name)? " and a.report_group_name like '%$reportg_name%'":"";
		$query="SELECT  b.org_name,c.numreports,a.report_group_id,a.report_group_name FROM uls_report_groups a 
		LEFT JOIN (SELECT organization_id,org_name FROM uls_organization_master GROUP BY organization_id)b ON b.organization_id= a.parent_org_id 
                Left Join(select report_grp_details_id,report_group_id,count(report_group_id) as numreports from uls_report_group_details group by report_group_id )c on c.report_group_id=a.report_group_id
		WHERE 1  $sq limit $limit offset $start";
		$testdetails=UlsMenu::callpdo($query);
        return $testdetails;
    }  
    
    public static function get_groupdetails($id){
        $query="select a.report_group_id,a.report_group_name,a.parent_org_id,b.org_name,a.comments from uls_report_groups a "
                . " Left Join(select organization_id,org_name from  uls_organization_master group by organization_id)b on a.parent_org_id=b.organization_id"
                . "  Where a.report_group_id=".$id;
        $detials=UlsMenu::callpdorow($query);
        return $detials;
        
    }


    public static function get_groupreport_details($id){
        $query="select b.report_name,c.value_name,a.report_group_id  from uls_report_group_details a "
                . " Left Join(select report_id,report_name from  uls_reports group by report_id)b on a.report_id=b.report_id "
                  . " Left Join(select value_code,value_name,master_code from uls_admin_values group by value_id)c on a.visible=c.value_code and c.master_code='REPORT_STATUS'"
                  
                . "  Where a.report_group_id=".$id;
        $detials=UlsMenu::callpdo($query);
        return $detials;
        
        
    }
}