<?php

/**
 * UlsSelfAssessmentEmployees
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsSelfAssessmentEmployees extends BaseUlsSelfAssessmentEmployees
{
	function preInsert($event){
		 $CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_by=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
    }
	
	static function getselfassessmentemployees($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.employee_id,b.full_name, b.employee_number, b.org_name, b.position_name, a.* from uls_self_assessment_employees a
			left join (select employee_id,full_name,employee_number,org_name,position_name from employee_data group by employee_id)b on b.employee_id=a.employee_id
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id order by a.assessment_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	static function getselfassessment($assessment_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT * FROM `uls_position` WHERE `position_id` in (SELECT `position_id` FROM `uls_self_assessment_employees` WHERE `assessment_id`=$assessment_id and `employee_id`=".$_SESSION['emp_id'].")";
		$assessments=UlsMenu::callpdo($query);
		return $assessments;
	}
	
	static function getselfemployees_admin($assessment_id,$position_id){
		$query="SELECT * FROM `employee_data` WHERE `employee_id` in (SELECT `employee_id` FROM `uls_self_assessment_employees` WHERE position_id=$position_id and `assessment_id`=$assessment_id)";
		$assessments=UlsMenu::callpdo($query);
		return $assessments;
	}
	
	static function getassessmentemployees_position($emp_id,$id,$pos_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.full_name, b.employee_number, b.org_name, b.position_name, a.* from uls_self_assessment_employees a
			left join (select employee_id,full_name,employee_number,org_name,position_name from employee_data group by employee_id)b on b.employee_id=a.employee_id	where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.employee_id=".$emp_id." and a.position_id=".$pos_id." and a.assessment_id=".$id." order by a.assessment_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
}