<?php

/**
 * UlsSelfAssessmentTrainingNeeds
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsSelfAssessmentTrainingNeeds extends BaseUlsSelfAssessmentTrainingNeeds
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_by=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
    }
	
	static function getadminselftrainings($id,$pos_id,$emp_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select a.* from uls_self_assessment_training_needs a
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.assessment_id=$id and a.position_id=$pos_id and a.employee_id=$emp_id";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}

}