<?php

/**
 * UlsStates
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsStates extends BaseUlsStates
{
	static function get_states(){
        $states=Doctrine_Query::Create()->from('UlsStates')->setHydrationMode(Doctrine::HYDRATE_ARRAY)->execute();
        return $states;
    }
	
	static function states_details($state_id){
		 $query="SELECT s.state_id,s.state_name  FROM `uls_states` s WHERE s.state_id='".$state_id."'";
		$locations=UlsMenu::callpdorow($query);
        return $locations;
    }	
}