<?php

/**
 * UlsSelfAssessmentReportDevArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsSelfAssessmentReportDevArea extends BaseUlsSelfAssessmentReportDevArea
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_by=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_by=$CI->session->userdata('user_id');
    }
	
	static function getselfassessment_dev_summary($id,$pos_id,$emp_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="SELECT ac.*,b.value_name as review_value_name,c.value_name as reporting_value_name FROM `uls_self_assessment_report_dev_area` ac
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'DEV_PLAN' AND ac.review = b.value_code
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)c ON c.master_code = 'YES_NO' AND ac.reporting = c.value_code
			where ac.parent_org_id=".$CI->session->userdata('parent_org_id')."  and ac.assessment_id=$id and ac.position_id=$pos_id and ac.employee_id=".$emp_id;
			$compdef=UlsMenu::callpdorow($query);
		}
		return $compdef;
	}
}