<?php

/**
 * UlsTest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsTest extends BaseUlsTest
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
	    if($this->active_flag=='P')
		{
		$this->start_date_active=date('Y-m-d');
		$this->end_date_active=NULL;
		}
		if($this->active_flag=='N')
		{
		$this->start_date_active=date('Y-m-d');
		$this->end_date_active=date('Y-m-d');
		}
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
	    if($this->active_flag=='P')
		{
		$this->start_date_active=date('Y-m-d');
		$this->end_date_active=NULL;
		}
		if($this->active_flag=='N')
		{
		$this->start_date_active=date('Y-m-d');
		$this->end_date_active=date('Y-m-d');
		}
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
    
	public static function searchcount($test_name){
		$CI =& get_instance();
		$CI->load->library('session');
        $sq=!empty($test_name)? " and a.test_name like '%$test_name%'":"";
		$query="SELECT count(*) as numcount FROM uls_test a
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'PUBLISH_STATUS' AND a.active_flag = b.value_code 
		LEFT JOIN (SELECT count(*) as questioncount, test_id FROM uls_test_questions GROUP BY test_id)c ON c.test_id = a.test_id 
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq ";
		$testcount=UlsMenu::callpdorow($query);		
		return $testcount['numcount'];
    }
    
   
    public static function search($start, $limit,$test_name){
		$CI =& get_instance();
		$CI->load->library('session');
        $sq=!empty($test_name)? " and a.test_name like '%$test_name%'":"";
		$query="SELECT c.questioncount,b.value_name as publish_status, a. * FROM uls_test a
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)b ON b.master_code = 'PUBLISH_STATUS' AND a.active_flag = b.value_code 
		LEFT JOIN (SELECT count(*) as questioncount, test_id FROM uls_test_questions GROUP BY test_id)c ON c.test_id = a.test_id 
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq limit $limit offset $start";
		$testdetails=UlsMenu::callpdo($query);
        return $testdetails;
    }  
	static function get_test(){
		$CI =& get_instance();
		$CI->load->library('session');
		$org_values= Doctrine_Query::create()->select('test_name as tname,test_id as tid,active_flag as pub,start_date_active as stdate,end_date_active as endate')->from('UlsTest')->where('parent_org_id='.$CI->session->userdata('parent_org_id'))->execute();      
		//$pdo = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
		//$emp_data="select count(b.test_quest_id) as coun, a.test_name as tname,a.test_id as tid,a.active_flag as pub,a.start_date_active as stdate,a.end_date_active as endate FROM uls_test a, uls_test_questions b where a.test_id=b.test_id  group by b.test_id";
		//$stmt = $pdo->prepare($emp_data);
		//$stmt->execute();
		//$org_values=$stmt->fetchAll();
		return $org_values;         
	}
      
	static function getquestionbanknames(){ 
		$CI =& get_instance();
		$CI->load->library('session');
        $qnames= Doctrine_Query::create()->select('question_bank_id as qid,name as qname')->from('UlsQuestionbank')->where("type='".$_REQUEST['test_type']."' and ((end_date_active >= CURDATE()) or (end_date_active is null)) and parent_org_id=".$CI->session->userdata('parent_org_id'))->execute();
		return $qnames;
	}
      
	static function get_test_details($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$test=Doctrine_Query::Create()->from('UlsTest')->where('test_id='.$id." and parent_org_id=".$CI->session->userdata('parent_org_id'))->execute();
		return $test;
	}
      
	static function get_test_view_details($id){
        // $query="call gettestquestions(".$id.")"; 
		 $query="SELECT b. * FROM `uls_questions` b
        WHERE b.`question_id`
    		IN (
    
                    SELECT `question_id`
                    FROM `uls_test_questions`
                    WHERE `test_id`
                    IN (
                    
                    SELECT `test_id`
                    FROM uls_test
                    WHERE test_id =".$id."
                )
		);";
	   return  UlsMenu::callpdo($query);
      
      }
      
      //Function to get test names based on test type and parent organization which are active
	static function test_details($testtyp){
		$CI =& get_instance();
		$CI->load->library('session');
		if(!empty($testtyp)){
			//$testtyp=($testtyp=='PRE' || $testtyp=='POST')?'T':'F';
			if($testtyp=='PRE' || $testtyp=='POST'){
				$testtyp='T';
			}else if($testtyp=='PRE_EVAL' || $testtyp=='POST_EVAL'){
				$testtyp='PROG_EVAL';
			}
			else if($testtyp=='E_LEARNING'){
				$testtyp='E_LEARNING';
			}
			else{
				$testtyp='F';
			}
			$testname=Doctrine_Query::Create()->from('UlsTest')->where("test_type_flag='".$testtyp."' and parent_org_id=".$CI->session->userdata('parent_org_id')." and ((CURDATE() between start_date_active and end_date_active) or (start_date_active is null or end_date_active is null))")->execute();
			return $testname;
		}
	}
    //for getting test details to show in test print
	static function get_test_details1($id){
		$CI =& get_instance();
		$CI->load->library('session');
        $test=Doctrine_Query::Create()->from('UlsTest')->where('test_id='.$id." and parent_org_id=".$CI->session->userdata('parent_org_id'))->fetchOne();
		return $test;
    }
	
	static function get_test_survey(){
		$CI =& get_instance();
		$CI->load->library('session');
		$org_values= Doctrine_Query::create()->select('test_name as tname,test_id as tid,active_flag as pub,start_date_active as stdate,end_date_active as endate')->from('UlsTest')->where("parent_org_id=".$CI->session->userdata('parent_org_id')." and test_type_flag='S'")->execute(); 
		return $org_values;         
	}
	
	public static function test_count($id){
		$query="SELECT c.questioncount, a.bulletin_id,d.max_attempts,d.test_id,a.parent_org_id FROM uls_admin_bulletin a
		LEFT JOIN(SELECT test_id,max_attempts FROM uls_test) d on a.test_id=d.test_id
		LEFT JOIN (SELECT count(*) as questioncount, test_id FROM uls_test_questions GROUP BY test_id)c ON c.test_id = a.test_id 
		WHERE a.bulletin_id=".$id;
		$testdetails=UlsMenu::callpdorow($query);
        return $testdetails;
    }  
}