<?php

/**
 * UlsUserRole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsUserRole extends BaseUlsUserRole
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session'); 
		$this->parent_org_id=$_SESSION['parent_org_id'];
        $this->created_by=$_SESSION['username'];
        $this->created_date=date('Y-m-d');
        $this->modified_by=$_SESSION['username'];        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$_SESSION['user_id'];
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session'); 
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
    // To get Organizatio Hierarchy id  writen by Prasad  
    public static function get_hierarchy(){
		$CI =& get_instance();
		$CI->load->library('session'); 
		$rolcreation1=Doctrine_Query::Create()->select('hierarchy_name as hname , hierarchy_id as hid')->from('UlsHeirarchyMaster')->where('parent_org_id='.$CI->session->userdata('parent_org_id'))->execute();			
        return $rolcreation1;
    }
	//Modified by Nagaraj.// Modified if there is no emp_id in the user creation table.
	public static function fetchroledet(){
		if(!empty($_REQUEST['emp_id'])){
			$empuse=Doctrine::getTable('UlsUserCreation')->findOnebyEmployeeId($_REQUEST['emp_id']);
			$empdetails=(!empty($empuse->user_id))?Doctrine_Query::Create()->from('UlsUserRole')->where("user_id=".$empuse->user_id)->execute():'';
			return $empdetails;
		}
	}
	//Function to get last added trainer role to the user from resource definition based on user id.
	public static function lastRoleData($userid){
		if(!empty($userid)){
			$CI =& get_instance();
			$CI->load->library('session'); 
			$tra_role="select ur.start_date, ur.end_date, r.role_name from uls_user_role ur
			INNER JOIN uls_role_creation r on r.role_id=ur.role_id 
			INNER JOIN uls_menu_creation m on m.menu_creation_id=r.menu_id and m.system_menu_type='tra'
			where ur.user_id=".$userid." and ur.parent_org_id=".$CI->session->userdata('parent_org_id');
			return UlsMenu::callpdorow($tra_role);
		}
	}
	
	//Function to get last added Employee role to the user for TNA on user id.
	public static function lastRoleData_emp($userid){
		if(!empty($userid)){
			$CI =& get_instance();
			$CI->load->library('session'); 
			$tra_role="select ur.start_date, ur.end_date, r.role_name,ur.role_id from uls_user_role ur
			INNER JOIN uls_role_creation r on r.role_id=ur.role_id 
			INNER JOIN uls_menu_creation m on m.menu_creation_id=r.menu_id and m.system_menu_type='emp'
			where ur.user_id=".$userid." and ur.parent_org_id=".$CI->session->userdata('parent_org_id');
			return UlsMenu::callpdorow($tra_role);
		}
	}
}