<?php

/**
 * UlsUserCreation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsUserCreation extends BaseUlsUserCreation
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
		$username=$CI->session->userdata('username');
		$user_id=$CI->session->userdata('user_id');
        !empty($username)?$this->modified_by=$CI->session->userdata('username'):"";
        !empty($user_id)?$this->last_modified_id=$CI->session->userdata('user_id'):"";
    }
    
    static function employees(){
        $employees= UlsMenu::callpdo("select * from uls_employee_master where employee_id in(SELECT distinct(`employee_id`) FROM `uls_user_creation`)");
        return $employees;        
    }
    static function searchcount($username=""){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq=($CI->session->userdata('username')=='unitol_admin' && $CI->session->userdata('parent_org_id')==1)? "1 and parent_org_id=".$CI->session->userdata('parent_org_id'): "1 and parent_org_id=".$CI->session->userdata('parent_org_id');
        $sq.=!empty($username)? " and user_name like '%$username%'":"";
        /*$sq.=!empty($empname)? " and Employee_id ='$empname'":"";
        $sq.=!empty($usertype)? " and user_type ='$usertype'":"";*/
        $roles= Doctrine_Query::create()->select("count(*) as numcount")->from('UlsUserCreation')->where($sq)->setHydrationMode(Doctrine::HYDRATE_ARRAY)->fetchOne();
        return $roles['numcount'];
    }
    
    static function search($start, $limit,$username=""){
		$CI =& get_instance();
		$CI->load->library('session');
		$sq=($CI->session->userdata('username')=='unitol_admin' && $CI->session->userdata('parent_org_id')==1)? "1 and parent_org_id=".$CI->session->userdata('parent_org_id'): "1 and parent_org_id=".$CI->session->userdata('parent_org_id');
        $sq.=!empty($username)? " and user_name like '%$username%'":"";
        /*$sq.=!empty($empname)? " and Employee_id ='$empname'":"";
        $sq.=!empty($usertype)? " and user_type ='$usertype'":"";*/
        $users=Doctrine_Query::create()->from('UlsUserCreation')->where($sq)->limit($limit)->offset($start)->execute();
        return $users;
    }
	
	static function viewuser($id){
		$query="SELECT c.name as actor,b.employee_id, b.full_name, b.email, b.employee_number, a. * FROM `uls_user_creation` a
		LEFT JOIN (SELECT employee_id, full_name, email, employee_number FROM uls_employee_master GROUP BY employee_id)b ON a.employee_id = b.employee_id
		LEFT JOIN (SELECT name, type FROM uls_actors GROUP BY TYPE)c ON a.user_type = c.type where user_id=$id";
		$role=UlsMenu::callpdorow($query);
		
		$queryrole="SELECT a.*,b.role_name FROM uls_user_role a left join(select role_name,role_id from uls_role_creation group by role_id)b on b.role_id=a.role_id WHERE user_id=$id";
		$userrole=UlsMenu::callpdo($queryrole);
		$role['userrole']=$userrole;
		/* echo "<pre>";
		print_r($role); */
		return $role;
	}
	
	static function fetchempdet(){
		if(!empty($_REQUEST['emp_id'])){
			$empdetails=Doctrine::getTable('UlsUserCreation')->findOnebyEmployee_id($_REQUEST['emp_id']);
			return $empdetails;
		}
	}
	
	static function fetchempdet_details($emp){
		$empdetails=Doctrine::getTable('UlsUserCreation')->findOnebyEmployee_id($emp);
		return $empdetails;
		
	}
	
	
	//Function to check an employee has user or not based on employee id for adding role in the resource definition
	public static function checkUser(){
		if(isset($_REQUEST['empid'])){
			$CI =& get_instance();
			$CI->load->library('session');
			$user="select u.user_id,ur.menu_id, r.role_id as rid,r.role_name as rname,ur.start_date as sd,ur.end_date as ed,u.start_date, u.end_date, m.system_menu_type from uls_user_creation u
			INNER JOIN uls_user_role ur on ur.user_id=u.user_id
			INNER JOIN uls_role_creation r on r.role_id=ur.role_id
			INNER JOIN uls_menu_creation m on m.menu_creation_id=r.menu_id
			where u.employee_id='".$_REQUEST['empid']."' and u.parent_org_id=".$CI->session->userdata('parent_org_id');
			return UlsMenu::callpdo($user);
		}
	}
	//Function to check trainer role exists for session parent org id for adding role in the resource definition
	public static function checkTraRole(){
		$CI =& get_instance();
		$CI->load->library('session');
		$parent_org_id=$CI->session->userdata('parent_org_id');
		if(!empty($parent_org_id)){
			$user="select r.role_name, r.role_id, group_concat(mn.menu_id) as menu_id from uls_role_creation r 
			INNER JOIN uls_menu_creation m on m.menu_creation_id=r.menu_id and m.system_menu_type='tra'
			INNER JOIN uls_menu	mn on mn.menu_creation_id=m.menu_creation_id
			where r.parent_org_id=".$CI->session->userdata('parent_org_id');
			return UlsMenu::callpdorow($user);
		}
	}
	
	//Function to check Assessor role exists for session parent org id for adding role in the Assessor master
	public static function checkAssRole(){
		$CI =& get_instance();
		$CI->load->library('session');
		$parent_org_id=$CI->session->userdata('parent_org_id');
		if(!empty($parent_org_id)){
			$user="select r.role_name, r.role_id, group_concat(mn.menu_id) as menu_id from uls_role_creation r 
			INNER JOIN uls_menu_creation m on m.menu_creation_id=r.menu_id and m.system_menu_type='asr'
			INNER JOIN uls_menu	mn on mn.menu_creation_id=m.menu_creation_id
			where r.parent_org_id=".$CI->session->userdata('parent_org_id');
			return UlsMenu::callpdorow($user);
		}
	}
	//Function to get last added user and trainer role from resource definition based on user id.
	public static function lastUserData($userid){
		if(!empty($userid)){
			$CI =& get_instance();
			$CI->load->library('session');
			$tra_role="select u.user_id, u.user_name, u.password, u.start_date, u.end_date,r.role_id, r.role_name from uls_user_creation u
			INNER JOIN uls_user_role ur on ur.user_id=u.user_id
			INNER JOIN uls_role_creation r on r.role_id=ur.role_id 
			INNER JOIN uls_menu_creation m on m.menu_creation_id=r.menu_id and m.system_menu_type='tra'
			where ur.user_id=".$userid." and ur.parent_org_id=".$CI->session->userdata('parent_org_id');
			return UlsMenu::callpdorow($tra_role);
		}
	}
	
	
	/* fetching the user type and status using username and password*/
	static function user_details($user,$pass){
		$user=Doctrine_Query::Create()->from('UlsUserCreation')->where("user_name='".$user."' and  password='".$pass."'")->setHydrationMode(Doctrine::HYDRATE_ARRAY)->fetchOne();
		return $user;
	}
	
	static function user_info($id){
		$query="select * from uls_user_creation where user_id=".$id;
		$user=UlsMenu::callpdorow($query);
		return $user;
	}
}