<?php

/**
 * UlsValidationPositions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsValidationPositions extends BaseUlsValidationPositions
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
        $this->parent_org_id=$CI->session->userdata('parent_org_id');
    }
	
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	static function getvalidationpositions($id){
		$CI =& get_instance();
		$CI->load->library('session');
		$compdef=array();
		if(!empty($id) && is_numeric($id)){
			$query="select b.position_id as position_id,b.position_name as position_name, c.value_name as val_status, a.*,b.position_desc from uls_validation_positions a
			left join (select position_id,position_name,position_desc from uls_position group by position_id)b on b.position_id=a.position_id
			LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)c ON c.master_code = 'STATUS' AND c.value_code=a.status
			where 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.val_id=$id order by a.position_id asc";
			$compdef=UlsMenu::callpdo($query);
		}
		return $compdef;
	}
	
	public static function get_val_position_info_emp($id,$val_id){
		$query="SELECT a.*,b.`position_validation_name`,b.end_date FROM uls_validation_positions a
		left join(SELECT `val_id`,`position_validation_name`,end_date FROM `uls_validation_position_definition`) b on a.val_id=b.val_id
		WHERE a.position_id=".$id." and a.val_id=".$val_id;
		$testdetails=UlsMenu::callpdorow($query);
        return $testdetails;
    } 
	
	
}