<?php

/**
 * UlsZoneMap
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsZoneMap extends BaseUlsZoneMap
{
	function preInsert($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->created_by=$CI->session->userdata('username');
		$this->parent_org_id=$CI->session->userdata('parent_org_id');
        $this->created_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');        
        $this->modified_date=date('Y-m-d');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
    function preUpdate($event){
		$CI =& get_instance();
		$CI->load->library('session');
        $this->modified_date=date('Y-m-d');
        $this->modified_by=$CI->session->userdata('username');
        $this->last_modified_id=$CI->session->userdata('user_id');
    }
	
	static function searchcount($zone_name=""){
		$CI =& get_instance();
		$CI->load->library('session');
        $sq=!empty($zone_name)? " and zone_id like '%$zone_name%'":"";
        $locations= Doctrine_Query::create()->select("count(*) as numcount")->from("UlsZoneMap")->where("1 and parent_org_id=".$CI->session->userdata('parent_org_id')." ". $sq)->setHydrationMode(Doctrine::HYDRATE_ARRAY)->fetchOne();
        return $locations['numcount'];
    }
	
	static function search($start, $limit,$zone_name=""){
		$CI =& get_instance();
		$CI->load->library('session');
        $sq=!empty($zone_name)? " and a.zone_id like '%$zone_name%'":"";
		$query="SELECT d.value_name,s.state_name, a. * FROM uls_zone_map a
		LEFT JOIN (SELECT value_id, master_code, value_code, value_name FROM uls_admin_values GROUP BY value_id)d ON master_code = 'LOCATION_ZONES' AND a.zone_id = d.value_code 
		LEFT JOIN (SELECT state_id,state_name FROM `uls_states` )s on s.state_id=a.state_id
		WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq limit $limit offset $start";
		$locations=UlsMenu::callpdo($query);
		/*echo "<pre>";
		print_r($locations);*/
        return $locations;
    }
	
	static function zone_states($zone_id){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT a.* FROM uls_zone_map a WHERE a.zone_id='".$zone_id."' and a.parent_org_id=".$CI->session->userdata('parent_org_id');
		$locations=UlsMenu::callpdo($query);
        return $locations;
    }	
	
	
	static function zones_states($zone_name){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT a.state_id,s.state_name FROM uls_zone_map a
		LEFT JOIN (SELECT state_id,state_name FROM `uls_states` )s on s.state_id=a.state_id
		WHERE a.zone_id='".$zone_name."' and a.parent_org_id=".$CI->session->userdata('parent_org_id');
		$locations=UlsMenu::callpdo($query);
        return $locations;
    }	
}