<?php

/**
 * UlsZone
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UlsZone extends BaseUlsZone
{
	
	static function searchcount($zonename=""){
		$CI =& get_instance();
		$CI->load->library('session');
        $sq=!empty($zonename)? " and a.zone_name like '%$zonename%'":"";
        $query="SELECT count(*) as numcount FROM uls_zone a WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq";
		$locations=UlsMenu::callpdorow($query);
		return $locations['numcount'];
    }
    
    static function search($start, $limit,$zonename=""){
		$CI =& get_instance();
		$CI->load->library('session');
        $sq=!empty($zonename)? " and a.zone_name like '%$zonename%'":"";	
		$query="SELECT a.* FROM uls_zone a WHERE 1 and a.parent_org_id=".$CI->session->userdata('parent_org_id')." $sq limit $limit offset $start";
		$locations=UlsMenu::callpdo($query);
        return $locations;
    }
	
	static function zone_view($locid){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT a.* from uls_zone a WHERE a.parent_org_id=".$CI->session->userdata('parent_org_id')." and a.zone_id=".$locid;
		$zone=UlsMenu::callpdorow($query);		
		return $zone;	
	}
	
	static function getzones(){
		$CI =& get_instance();
		$CI->load->library('session');
		$query="SELECT zone_id, zone_name FROM uls_zone WHERE parent_org_id =".$CI->session->userdata('parent_org_id');
		$locations=UlsMenu::callpdo($query);
		return $locations;
    }
}